### ISSUE TITLE
build-dl4j-stack.sh not working

### ISSUE THREAD

**Issue by danimateos** [deeplearning4j/deeplearning4j#2809] opened 2017-02-01 15:21 UTC
* Syntax errors
* not passing properly arguments to libnd4h/buildnativeoperations.sh: https://gist.github.com/danimateos/31b3a484824e0587facf6e477f9d5e50

**Comment by raver119** [comment] 2017-02-01 16:06
It's "as intended". When you build from sources - you have to build both cpu & cuda versions. CPU gets built first.

**Comment by danimateos** [comment] 2017-02-01 16:20
ok, I see. What about the syntax errors?

**Comment by danimateos** [comment] 2017-02-01 16:48
@raver119 I made a PR to fix the syntax errors (#2810)

I'm not convinced that it is fully working though; when I use it, it tries to compile  agains all cuda ccs rather than the one I tell it to- it does not seem to be calling `buildnativeoperations.sh` quite right

**Comment by raver119** [comment] 2017-02-01 16:52
Merged, thanks

**Closed by raver119** 2017-02-01 16:52 UTC
