### ISSUE TITLE
Op [hashcode] failed check for output [0], DataType: [FLOAT];

### ISSUE THREAD

**Issue by frakc** [deeplearning4j/deeplearning4j#8576] opened 2019-12-25 22:45 UTC
#### Issue Description
When running ticktoe example I encounter the following error.  Interesting thing - I don't have drive D

INFO: Data Processing Started
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for linear algebra: 4
o.n.l.c.n.CpuNDArrayFactory - *********************************** CPU Feature Check Warning ***********************************
o.n.l.c.n.CpuNDArrayFactory - Warning: Initializing ND4J with Generic x86 binary on a CPU with AVX/AVX2 support
o.n.l.c.n.CpuNDArrayFactory - Using ND4J with AVX/AVX2 will improve performance. See deeplearning4j.org/cpu for more details
o.n.l.c.n.CpuNDArrayFactory - Or set environment variable ND4J_IGNORE_AVX=true to suppress this warning
o.n.l.c.n.CpuNDArrayFactory - *************************************************************************************************
o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 4
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [7,1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
Op [hashcode] failed check for output [0], DataType: [FLOAT];
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op hashcode. Attempted to execute with 1 inputs, 1 outputs, 0 targs,0 bargs and 0 iargs. Inputs: [(FLOAT,[1,9],c)]. Outputs: [(FLOAT,[],c)]. tArgs: -. iArgs: -. bArgs: -. Op own name: "91decc42-7145-4e8a-9bba-52eac91a131a" - Please see above message (printed out from c++) for a possible cause of error.
дек 26, 2019 12:38:23 AM org.deeplearning4j.examples.tictactoe.TicTacToeData main
SEVERE: java.lang.RuntimeException: Op [hashcode] execution failed
дек 26, 2019 12:38:23 AM org.deeplearning4j.examples.tictactoe.TicTacToeData main
INFO: Total time = 1417
Validation error at D:/jenkins/ws/dl4j-deeplearning4j-1.0.0-beta6-windows-x86_64-cpu/libnd4j/include/ops/declarable/impl/DeclarableOp.cpp:515 code=34() "this->validateDataTypes(*block)" 

Process finished with exit code 0

#### Version Information

    <parent>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-examples-parent</artifactId>
        <version>1.0.0-beta6</version>
    </parent>

**Comment by saudet** [comment] 2019-12-26 02:09
Duplicate of #8554

**Comment by saudet** [comment] 2019-12-26 02:10
Sorry, I thought this was related to the AVX warning, but maybe it's not related @raver119 ?

**Comment by raver119** [comment] 2019-12-26 04:43
It's a bug, described here: https://github.com/eclipse/deeplearning4j/issues/8566
Already fixed on master. Will be available in snapshots shortly.

**Closed as completed by raver119** 2019-12-26 04:43 UTC
Labels: Duplicate, ND4J
