### ISSUE TITLE
Keras optimizers not recognized

### ISSUE THREAD

**Issue by Nrojt** [deeplearning4j/deeplearning4j#9911] opened 2023-02-14 22:23 UTC
#### Issue Description
I am trying to load an exported keras/tensorflow model (made in python), with the optimizer Adam, but it gives an error saying custom optimizers are not supported.

https://deeplearning4j.konduit.ai/deeplearning4j/how-to-guides/keras-import/supported-features/optimizers lists it as compatible.
I use the following python code:
  ```
import tensorflow as tf
  from tensorflow import keras
  
  
  model = tf.keras.Sequential()
  model.add(keras.layers.Dense(16, activation='relu', input_shape=(17,)))
  model.add(keras.layers.Dense(1, activation='relu'))
  
  model.compile(loss='mean_squared_error', optimizer='adam')
  
  history = model.fit(X_train_scaled, y_train, epochs=50)

  model.save("exported_models/h5/BetterAntiCheatMovementModelh5.h5")
```
This model works in python, but when I try to load it in Java with the following code, it gives the following error:
```
import org.deeplearning4j.nn.modelimport.keras.KerasModelImport;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.nd4j.common.io.ClassPathResource;

public class MovementModel {
    public static void main(String[] args) throws Exception {
        String fullModel = new ClassPathResource("Model/BetterAntiCheatMovementModelh5.h5").getFile().getPath();
        MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights(fullModel);
    }
}
```

The error:
```
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Optimizer with name Custom>Adamcan not bematched to a DL4J optimizer. Note that custom TFOptimizers are not supported by model import. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasOptimizerUtils.mapOptimizer(KerasOptimizerUtils.java:151)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.importTrainingConfiguration(KerasModel.java:395)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:139)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:55)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:326)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:218)
	at me.Michielo.BetterAnticheat.algorithms.MovementModel.main(MovementModel.java:11)

```

#### Version Information
*Tensorflow 2.11
* Deeplearning4j version 1.0.0-M2.1
* Windows 11
* IntelliJ IDEA

#### Additional information
I have also tried to use different optimizers, but it gives the same error (but then with the name of that optimizer instead of Adam)
```
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-M2.1</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>1.0.0-M2.1</version>
        </dependency>
```

**Comment by Nrojt** [comment] 2023-02-15 12:28
It works if I put the path to the model directly in the modelimport instead of the ClassPathResource.

**Comment by agibsonccc** [comment] 2023-02-15 12:43
@Nrojt  hmm..I wonder if this is due to a more recent keras version issue. They might have changed the underlying format and we're not detecting it. I've seen some issues pop up in keras 2.11. This might be one of them. Let me take a look. Minor format changes like this should be a simple fix.

**Comment by agibsonccc** [comment] 2023-02-15 12:47
@Nrojt could you try snapshots? I just tried your code and it works fine now: https://deeplearning4j.konduit.ai/multi-project/explanation/snapshots Closing this. Please reopen if you have issues after snapshots. Thanks!
Note that custom optimizers and the like would still be an issue. I will not be supporting that in the scope of this issue given your reproducer. Feel free to explicitly ask for that in a separate issue if it's critical for you. Thanks!

@Nrojt  also of note...I'm not sure what your issue was here but we for sure already had tests explicitly covering this:. You can find this here: https://github.com/deeplearning4j/deeplearning4j/blob/fd91c9c66e8f769bbceabcdbac33a2ba616d99cd/platform-tests/src/test/java/org/eclipse/deeplearning4j/frameworkimport/keras/optimizers/TestOptimizerImport.java#L60

**Closed as completed** 2023-02-15 12:48 UTC
Labels: DL4J Keras
