### ISSUE TITLE
Different result of max pooling layer using cpu and gpu backend

### ISSUE THREAD

**Issue by StefanoSamele** [deeplearning4j/deeplearning4j#4071] opened 2017-09-14 15:04 UTC
We used the following simple network to test the max pooling layer effect with different backends:
https://gist.github.com/StefanoSamele/93a3d602d3c55585cf79d8f4c807da75

Using cpu native backend we got the following output:
[[[[108.00,  135.00,  162.00,  189.00,  216.00],  
   [135.00,  162.00,  189.00,  216.00,  243.00],  
   [162.00,  189.00,  216.00,  243.00,  270.00],  
   [189.00,  216.00,  243.00,  270.00,  297.00],  
   [216.00,  243.00,  270.00,  297.00,  324.00]]]]

Using CUDA backend we got:
[[[[81.00,  108.00,  135.00,  162.00,  189.00],  
   [108.00,  135.00,  162.00,  189.00,  216.00],  
   [135.00,  162.00,  189.00,  216.00,  243.00],  
   [162.00,  189.00,  216.00,  243.00,  270.00],  
   [189.00,  216.00,  243.00,  270.00,  297.00]]]]

It looks like the CUDA output is somehow "shifted".
We also did a test comparing a Keras net output (involving max pooling operations), with the same net imported in DL4J. The cpu output matched the keras output, while the CUDA output didn't.

**Comment by raver119** [comment] 2017-09-14 15:07
Is CUDNN used?

**Comment by raver119** [comment] 2017-09-14 15:12
And yes, that's strange. Dl4j pooling 2d uses the same code for cpu & CUDA...

**Comment by StefanoSamele** [comment] 2017-09-14 15:14
So, we noticed we didn't have the following dependency:
<dependency>
   <groupId>org.deeplearning4j</groupId>
   <artifactId>deeplearning4j-cuda-8.0</artifactId>
   <version>${dl4j.version}</version>
 </dependency>

We will immediately try again.

**Comment by raver119** [comment] 2017-09-14 15:15
hm, so it gives different result without cuDNN. Now i'm really surprised...

**Comment by raver119** [comment] 2017-09-14 15:27
Can you please also check Convolution layer output on different backends? Maybe that's the place where  difference comes from?

**Comment by StefanoSamele** [comment] 2017-09-14 15:28
No, we checked it. It appears to be the same.

**Comment by raver119** [comment] 2017-09-14 15:33
Amazing…

**Comment by StefanoSamele** [comment] 2017-09-14 15:43
We had the chance to use cuDNN, and it gives the same result.

**Comment by StefanoSamele** [comment] 2017-09-14 17:17
Unfortunately with cuDNN, we noticed that Atrous Convolution (dilated) no longer works correctly. Should we open another issue?

**Comment by raver119** [comment] 2017-09-14 17:55
Yes, file new issue please.

**Comment by AlexDBlack** [comment] 2017-12-05 08:29
I'm going to close this: I'm unable to reproduce it. There have been a number of changes/fixes since this issue was opened.

```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
[[[[108.00,  135.00,  162.00,  189.00,  216.00],  
   [135.00,  162.00,  189.00,  216.00,  243.00],  
   [162.00,  189.00,  216.00,  243.00,  270.00],  
   [189.00,  216.00,  243.00,  270.00,  297.00],  
   [216.00,  243.00,  270.00,  297.00,  324.00]]]]
   
     
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
[[[[108.00,  135.00,  162.00,  189.00,  216.00],  
   [135.00,  162.00,  189.00,  216.00,  243.00],  
   [162.00,  189.00,  216.00,  243.00,  270.00],  
   [189.00,  216.00,  243.00,  270.00,  297.00],  
   [216.00,  243.00,  270.00,  297.00,  324.00]]]]
```

**Closed by AlexDBlack** 2017-12-05 08:29 UTC
Labels: bug
