### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by atechnicolorskye** [deeplearning4j/deeplearning4j#187] opened 2015-03-05 07:30 UTC
Hi,

I'm getting the following issue for Word2Vec which prevents it from plotting (when testing Word2VecExample):

Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeTsneFormat(WordVectorSerializer.java:364)
	at org.deeplearning4j.word2vec.Word2VecExample.main(Word2VecExample.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

My default settings are those prescribed in https://github.com/deeplearning4j/dl4j-0.0.3.3-examples 

Thanks

**Comment by nouramoubayed** [comment] 2015-03-05 14:08
I do have the exact problem!

**Comment by nouramoubayed** [comment] 2015-03-05 14:53
the problem is with the following line
  WordVectorSerializer.writeTsneFormat(vec, tsne.getY(), new File("coords.csv"));
tsne.getY() is always null. 

any suggestions? help?

**Comment by agibsonccc** [comment] 2015-03-06 00:56
I added a test for this here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/test/java/org/deeplearning4j/models/word2vec/Word2VecTests.java#L122

This was because tsne wasn't trained. plotVocab calls train and everthing. I updated the examples to reflect this. I'm going to close this.

**Closed by agibsonccc** 2015-03-06 00:56 UTC
