### ISSUE TITLE
Keras Bidirectional does not work with Last Time Step

### ISSUE THREAD

**Issue by mboyanov** [deeplearning4j/deeplearning4j#4445] opened 2017-12-21 09:39 UTC
#### Issue Description

When importing a keras model with Bidirectional(LSTM (..return_sequences = False )) an exception is thrown due to the following check: 
```
    public Bidirectional(@NonNull Mode mode, @NonNull Layer layer){
        if(!(layer instanceof BaseRecurrentLayer)){
            throw new IllegalArgumentException("Cannot wrap a non-recurrent layer: config must extend BaseRecurrentLayer. " +
                    "Got class: " + layer.getClass());
        }
        ...
    }

```
stacktrace: 
```
Caused by: java.lang.IllegalArgumentException: Cannot wrap a non-recurrent layer: config must extend BaseRecurrentLayer. Got class: class org.deeplearning4j.nn.conf.layers.recurrent.LastTimeStep
	at org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional.<init>(Bidirectional.java:78)
	at org.deeplearning4j.nn.modelimport.keras.layers.wrappers.KerasBidirectional.<init>(KerasBidirectional.java:128)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:192)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.9.2-SNAPSHOT
* platform information (OS, etc)

**Comment by maxpumperla** [comment] 2017-12-21 09:48
thanks for reporting. will look into it

**Comment by maxpumperla** [comment] 2018-01-19 14:42
closed this accidentally, doesn't quite work yet. :/

**Comment by EgoLaparra** [comment] 2018-03-19 02:09
Hi,

I'm getting an exception that I think it is related to this issue, so I have preferred not to open a new one. Sorry, if I am wrong.

The following exception is thrown when importing a keras model with Bidirectional(LSTM (..return_sequences = True )) :

```
Exception in thread "main" java.lang.ClassCastException: org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional cannot be cast to org.deeplearning4j.nn.conf.layers.FeedForwardLayer
	at org.deeplearning4j.nn.graph.ComputationGraph.summary(ComputationGraph.java:3590)
	at org.deeplearning4j.nn.graph.ComputationGraph.summary(ComputationGraph.java:3527)
```

Is it caused by the same problem discussed here?

**Comment by AlexDBlack** [comment] 2018-03-19 02:52
@EgoLaparra Can you post the keras configuration and some DL4J code you are using, so we can reproduce this?

**Comment by EgoLaparra** [comment] 2018-03-19 04:49
Keras version: 1.2.2
Keras backend: theano
Deeplearning4j version: 0.9.2-SNAPSHOT

This is the snippet to create the keras model:
```
inputs = Input((5, 784, ))
x = Bidirectional(LSTM(64, activation='relu', return_sequences=True, name='bidirectional_1'))(inputs)
predictions = TimeDistributed(Dense(10, activation='softmax', name='timedistributed_1'))(x)
model = Model(input=inputs, output=predictions)
model.compile(optimizer='rmsprop',
             loss='categorical_crossentropy',
             metrics=['accuracy'])
```
And this is the DL4J code that throws the exception, specifically the line with the call to _network.summary()_ :
```
public static void main( String[] args ) throws Exception {
  ComputationGraph network = KerasModelImport.importKerasModelAndWeights(args[0], false);
  System.out.println(network.summary());
}
```

**Closed** 2018-06-12 19:57 UTC
Labels: Bug, DL4J Keras
