### ISSUE TITLE
How to import word2vec model into seq2seq?

### ISSUE THREAD

**Issue by luyunfan** [deeplearning4j/deeplearning4j#4076] opened 2017-09-15 10:16 UTC
I‘m playing with the sequence to sequence model, like AdditionRNN.java and EncoderDecoderLSTM.java.
And I noticed that the input vector is a one-hot vector, I was wondering could I import a word2vec model as the seq2seq input? Rather than using the one-hot vector in this case, and How?

I'm trying to use the word2vec model as the input vectors but get a model like this:

![pic1](https://user-images.githubusercontent.com/16959173/30478052-0090cfa2-9a42-11e7-97a5-16839a03b53f.PNG)
![pic](https://user-images.githubusercontent.com/16959173/30478053-0093e502-9a42-11e7-8acb-f9742e00b9e2.PNG)

What should I do now?

### Thank you very much!

**Comment by tomthetrainer** [comment] 2017-09-16 21:13
I am not sure, perhaps @eraly the author of our seq2seq example has some input

**Comment by eraly** [comment] 2017-09-20 16:12
You can use a one hot vector as input. You could also try to have the network learn the embedding which I think can happen quite well as well especially if your vocab is not so big. We have a very good example of this here:
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/encdec/EncoderDecoderLSTM.java#L252
This might be what you are looking for.

I am closing since this is more of question about tuning/improving the network and not a bug or feature add.

**Closed by eraly** 2017-09-20 16:12 UTC
