### ISSUE TITLE
Off by 1 error in confusion matrix. (at least in the UCISequenceClassificationExample )

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#4485] opened 2018-01-08 02:13 UTC
#### Issue Description
(from https://github.com/deeplearning4j/dl4j-examples/issues/593 ).
The UCISequenceClassificationExample has 150 rows of test data. The confusion matrix returns a count of 151.

Here is a gist with a unit test reproducing the issue. (You need to run the original example to download the data).
https://gist.github.com/RobAltena/7d99cbcb7f8b8717e08d50ecf32749ba

**Comment by AlexDBlack** [comment] 2018-01-12 09:48
Thanks for reporting.
I am able to reproduce this on 0.9.1, however it appears to be fixed on master (the test passes there).
I'm not sure exactly when it would have been fixed, but there have been a number of smaller tweaks to RecordReader(Multi)DataSetIterator and the evaluation classes since 0.9.1.

**Closed by AlexDBlack** 2018-01-12 09:48 UTC
