### ISSUE TITLE
Setting image pipeline for object segmentation

### ISSUE THREAD

**Issue by ioannisbaptista** [deeplearning4j/deeplearning4j#6472] opened 2018-09-20 10:04 UTC
Hi guys,

I'm working on the segmentation of road network in aerial RGB images (TIFF, 1024 x 1024 px). I intend to use a CNN (implemented using DL4J) with supervised learning to detect which pixels in the image correspond to an avenue or asphalted street.

I've created a database containing 100 TIFF images of the top-view urban landscape of my city (just to getting started, I can add more images to database if needed). For each image, I generated a PNG image with same dimensions, whose pixels have a black color if they correspond to a street or a paved avenue, or transparent otherwise. It's a similar job to issue #1246 , except that I wasn't able to figure out how did he set the implementation.

![image](https://user-images.githubusercontent.com/37843996/45811370-3f26d200-bca3-11e8-81c4-52f68dbde02f.png)

My idea is to split the database into 80% training-20% test. CNN would use the PNGs to learn which pixels must compose the segmentated area. To evaluate the accuracy, I would implement an algorithm that computes the Jaccard Index to compare what CNN thought was a road to what CNN should have thought so.

I found many examples and documentations on image recognition, but almost nothing about image segmentation. I found some papers, I got the idea, but they don't go into implementation details (I'm a truly beginner on this), specially DL4J. I'm really having trouble to set this pipeline, and that's what I really need you guys help me with. Please show me how to implement or point me to some reference with which I can learn how to do this.

Can anyone help? Thanks in advance.

**Comment by HGuillemet** [comment] 2018-09-20 23:02
I would try a pure CNN networks, with several layers of CCN, and a CnnLossLayer. And feed your segmented images as the expected output (maybe after convolution by a smoothing filter). I don't know if it has been tried elsewhere for segmentation.

**Comment by AlexDBlack** [comment] 2018-09-20 23:41
Right, @HGuillemet is correct regarding the architecture. You want a fully convolutional net (i.e., no dense layers) with a CnnLossLayer.

As far as the data pipeline, it's a standard ImageRecordReader with a custom PathLabelGenerator:
https://github.com/deeplearning4j/deeplearning4j/blob/master/datavec/datavec-api/src/main/java/org/datavec/api/io/labels/PathLabelGenerator.java

The idea for the PathLabelGenerator is that:
1. Path to the input (feature) image is an argument to the method
2. Map that path to the label image file (i.e., work out the label that corresponds to that the input image file)
3. Use NativeImageLoader to load the label image for the appropriate size
4. Return as an NDArrayWritable

**Comment by ioannisbaptista** [comment] 2018-09-23 16:11
Let me see if I got it right:

1) @AlexDBlack, I implemented the custom PathLabelGenerator like this:

```
public Writable getLabelForPath(String path)
{
	NativeImageLoader imageLoader = new NativeImageLoader(1024, 1024, 3);
		
	try
	{
		return new NDArrayWritable(imageLoader.asMatrix(new File(path).getName()));
	}
	catch(IOException ioe)
	{
		ioe.printStackTrace();
		return null;
	}
}
```

Is that correct?

2) @AlexDBlack, in the issue #1246, which concerns to a very similar problem, you said _"use two separate image record readers, and manually create a new DataSet from them... so the first would give you your input, and the second would give you your labels. Input and labels would be in completely separate directories"_. Ok, I have my 100 **Tif** images in the "\img\images" directory and the 100 **gif** segmented images in the "\img\ROIs" directory. My idea is to take 80% for training and 20% for testing. I'm still on training implementation stage. So I did:

```
// Process images
MyPathLabelGenerator images = new MyPathLabelGenerator();
FileSplit imageSplit = new FileSplit(new File(imagesPath), extensions, randomNumber);
BalancedPathFilter imagesPathFilter = new BalancedPathFilter(randomNumber, extensions, images);
InputSplit[] imageSplits = imageSplit.sample(imagesPathFilter, 80, 20);
InputSplit imageTrainingData = imageSplits[0];
InputSplit imageTestingData = imageSplits[1];
ImageRecordReader imageRecordReader = new ImageRecordReader(height, width, numberOfChannels, images);
imageRecordReader.initialize(imageTrainingData);
DataSetIterator imageDataSet = new RecordReaderDataSetIterator(imageRecordReader, batchSize, 1, outputNum);
scaler.fit(imageDataSet);
imageDataSet.setPreProcessor(scaler);

// Process labels
MyPathLabelGenerator ROIs = new MyPathLabelGenerator();
FileSplit ROISplit = new FileSplit(new File(ROIsPath), extensions, new Random(seed));
BalancedPathFilter ROIsPathFilter = new BalancedPathFilter(randomNumber, extensions, ROIs);
InputSplit[] ROIsSplits = ROISplit.sample(ROIsPathFilter, 80, 20);
InputSplit ROITrainingData = ROIsSplits[0];
InputSplit ROITestingData = ROIsSplits[1];
ImageRecordReader ROIRecordReader = new ImageRecordReader(height, width, numberOfChannels, ROIs);
ROIRecordReader.initialize(ROISplit);
DataSetIterator ROIDataSet = new RecordReaderDataSetIterator(ROIRecordReader, batchSize, 1, outputNum);
scaler.fit(ROIDataSet);
ROIDataSet.setPreProcessor(scaler);

// Merge 80%-training-inputs with its corresponding labels
DataSet trainingData;
while(imageRecordReader.hasNext()) //this loop is going to happen just once, right?
{
	DataSet imageSet = imageDataSet.next();
	DataSet ROISet = ROIDataSet.next();
	trainingData = new DataSet(imageSet.getFeatures(), ROISet.getFeatures());
}
```
Is that what you meant? Did I make it right?

3) I tried to run it just to check the consistency of the code, but when it reads the "tipo2_1_3_0.Tif" (63rd image in the set) the following error is fired:

_Exception in thread "main" java.lang.NullPointerException
	at org.datavec.api.writable.NDArrayWritable.toString(NDArrayWritable.java:210)
	at org.datavec.api.io.filters.BalancedPathFilter.filter(BalancedPathFilter.java:112)
	at org.datavec.api.split.BaseInputSplit.sample(BaseInputSplit.java:104)
	at br.uema.pecs.tcc.cnn.RoadCNN.main(RoadCNN.java:118)_

The 118th line of `RoadCNN.java` is the instruction `InputSplit[] imageSplits = imageSplit.sample(imagesPathFilter, 80, 20);`. The debugger shows the field `array` in the `NDArrayWritable` class is **null**, but it doesn't happen with the previous images. I've been on this last 24 hours and couldn't find out why. =(

Sorry guys if my questions are too obvious, but I really wasn't any lucky on finding any solution on Google or relationed books.
Thanks on advance!

**Comment by ioannisbaptista** [comment] 2018-09-24 02:10
@AlexDBlack 

> that's inefficient

yes, now I see that 😄 I just fixed it.

> make sure you return false for inferLabelClasses()

Done.

> Try loading that specific image outside of your data pipeline

I did and honestly it was very weird. When I wrote the loader, I got permission errors. So I had to use `file.getName()` instead of `file` in the `asMatrix()` method. It worked, except for the 63rd image (I checked it out). But when I tried it individually, it didn't work for any of them. So I took the "getName" off. It worked to all the images (including the CNN class) and got no permission errors. Mistery.

--
Now what really matters: the images loading and splitting were fine. I got 4 InputSplits:
1) `imageTrainingData` = the 80% images to feed the training;
2) `ROITrainingData` = the 80% segmented images to be the expected output of the CNN in the training;
3) `imageTestingData` = the 20% images to evaluate the testing;
4) `ROITestingData` = the 20% segmented images to be compared to the outputs during the tests.

My question is how to use 1) and 2) to assemble the DataSet that will be the parameter to `cnn.fit(dataSet)`.
Thanks in advance!

**Comment by AlexDBlack** [comment] 2018-09-24 12:06
OK, so you'll want to use RecordReaderDataSetIterator.
It should be something like this:
```
RecordReader rr = new ImageRecordReader(...);
int batch = 32;
int labelIndex = 1;     //You have 2 Writables ("columns") - index 0 is features image NDArrayWritable, index 1 is labels image NDArrayWritable
DataSetIterator iter = new RecordReaderDataSetIterator(rr, batch, labelIndex, labelIndex, true);
```
(Note the "regression=true" arg there just means "don't try to convert label to a one-hot array" like you need for classification)
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-data/deeplearning4j-datavec-iterators/src/main/java/org/deeplearning4j/datasets/datavec/RecordReaderDataSetIterator.java#L159

**Comment by ioannisbaptista** [comment] 2018-09-24 14:09
@AlexDBlack sorry but I didn't get it... 😞 

Correct me if I'm wrong: I have to assemble two dataSets: a training one to use in `cnn.fit(trainingDataSet)` and a testing one, to use in `evaluation.evaluate(testingDataSet)`. 
Since I've got 2 InputSplits for each case (i.e., training and testing), I suppose I need to create a RecordReader containing 1 + 2, and another one containing 3 + 4. Right?

In the example you gave me I understood the `ImageRecordReader(...)` created already contains 1 + 2. But it turns out that this is just my question: I still don't know how to do that.

**Comment by AlexDBlack** [comment] 2018-09-25 00:10
OK, I went back and re-read your last post. I can see how you are confused.

> Since I've got 2 InputSplits for each case (i.e., training and testing)

This isn't the approach you want.
You need only *2* input splits, not 4 - one for train, one for test. These splits are for your input images (not your labels/segmented images, you don't want/need an input split for those).
The labels/segmented images are loaded/provided by the PathLabelGenerator - not via an input split.
So, for your 4 splits, you only want numbers 1 and 3.

**Comment by ioannisbaptista** [comment] 2018-09-25 02:55
@AlexDBlack If I got yout hint, I only need the `imageTrainingData` (80% images) and the `imageTestingData` (20% images). I'll put here a preview of my code (just the part that concerns to this part of the problem), so we can be in tune:

```
// The original images directory
private static final String imagesPath = projectPath + "\\img\\images\\";
// The segmented images directory
private static final String ROIsPath = projectPath + "\\img\\ROIs\\";

int height = 1024;
int width = 1024;
int numberOfChannels = 3;
int outputNum = 2; // 0 = Not a road; 1 = Is a road
int batchSize = 32;

int seed = 1234;
Random randomNumber = new Random(seed);
String[] extensions = {"TIFF", "Tiff", "tiff", "TIF", "Tif", "tif", "PNG", "Png", "png"};
DataNormalization scaler = new ImagePreProcessingScaler(0, 1);

MyPathLabelGenerator labeler= new MyPathLabelGenerator();
FileSplit imageSplit = new FileSplit(new File(imagesPath), extensions, randomNumber);
BalancedPathFilter imagesPathFilter = new BalancedPathFilter(randomNumber, extensions, labeler);

InputSplit[] imageSplits = imageSplit.sample(imagesPathFilter, 80, 20);
InputSplit imageTrainingInputSplit = imageSplits[0]; // 1: 80% for training
InputSplit imageTestingInputSplit = imageSplits[1]; // 3: 20% for testing

ImageRecordReader imageRecordReader = new ImageRecordReader(height, width, numberOfChannels, labeler);
imageRecordReader.initialize(imageTrainingInputSplit);

DataSetIterator imageDataSetIterator = new RecordReaderDataSetIterator(imageRecordReader, batchSize, 1, outputNum);
scaler.fit(imageDataSetIterator);
imageDataSetIterator.setPreProcessor(scaler);
```

Of course, it's just a sketch. But there are two things I still don't get:

1) >  The labels/segmented images are loaded/provided by the PathLabelGenerator - not via an input split

How the PathLabelGenerator "knows" where the segmented images are? The `imagesPath` param only "tells" it the images folder.
(This one is the most important)

2) > You need only 2 input splits, not 4 - one for train, one for test. These splits are for your input images

At the begining, I thought I could use the InputSplits as arguments to the ImageRecordReaders, but I still couldn't figure how. I just looked into the `ImageRecordReader` class, and looks like the `imageRecordReader.initialize(imageTrainingInputSplit);` instruction feeds the ImageRecordReader with the InputSplit data. Did I understand it correctly?

**Comment by AlexDBlack** [comment] 2018-09-26 00:03
OK, so for that exception: I think the problem here is that you are configuring the RecordReaderDataSetIterator wrong.
Specifically: re-read the configuration I posted here: note it's a different constructor than whan you are using.
https://github.com/deeplearning4j/deeplearning4j/issues/6472#issuecomment-423952443

Note that using that you will need to use a Convolution layer with nOut=1 and CnnLossLayer with sigmoid + xent activation function.
That is, you're doing "single output binary classification" (sigmoid/xent) not "2-output binary classification" (softmax/mcxent)

**Comment by ioannisbaptista** [comment] 2018-09-26 00:27
@AlexDBlack thanks, I just fixed it. My confusion is now I'm not sure of how to infer from nOut being 1. I thought it should be 2 for having road/non-road possibilities. Is it correct to assume that the nOut is going to give me a probability of a pixel be or nor a road, so I must define a threshold in my application?

Besides, I got a new Exception fired in the `cnn.fit(imageDataSetIterator);` instruction:
_Exception in thread "main" java.lang.IllegalArgumentException: Labels and preOutput must have equal shapes: got shapes [4, 3, 1024, 1024] vs [4, 1]
	at org.nd4j.base.Preconditions.throwEx(Preconditions.java:621)
	at org.nd4j.linalg.lossfunctions.impl.LossMCXENT.computeGradient(LossMCXENT.java:155)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:182)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:154)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1805)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2594)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2545)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:51)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fitHelper(MultiLayerNetwork.java:1581)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1500)
	at br.uema.pecs.tcc.cnn.RoadCNN.main(RoadCNN.java:263)_

Sounds like the segmented images were 1-channel, but I just checked and they are also 3-channel, and all they have the same size. Any clue?

**Comment by AlexDBlack** [comment] 2018-09-26 00:33
> My confusion is now I'm not sure of how to infer from nOut being 1. I thought it should be 2 for having road/non-road possibilities.

There's different ways of doing it.
I'm suggesting you need to use NativeImageLoader with channels set to 1: I missed the fact that you had set it to 3 in your earlier code
> NativeImageLoader imageLoader = new NativeImageLoader(1024, 1024, 3);
i.e., that should be ```new NativeImageLoader(1024, 1024, 1)```
That'll give you [1, 1, 1024, 1024]``` shaped labels - 1 example in minibatch, 1 channel, 1024x1024.
Each label pixel will have value 0 for black input (road), 1 for white input (not road).

**Comment by ioannisbaptista** [comment] 2018-09-26 01:16
> I'm suggesting you need to use NativeImageLoader with channels set to 1: I missed the fact that you had set it to 3 in your earlier code

But if I set to `NativeImageLoader(1024, 1024, 1);`, isn't it going to load just the 1st channel of the images?

> Each label pixel will have value 0 for black input (road), 1 for white input (not road).

Actually is **blank** (transparent), not white. Black for road, transparent for non-road. Does it make difference to the net?

> I'll need to see your network config.
```
Map<Integer, Double> learningScheduleMap = new HashMap<>();
learningScheduleMap.put(0, 0.06);
learningScheduleMap.put(200, 0.05);
learningScheduleMap.put(600, 0.028);
learningScheduleMap.put(800, 0.0060);
learningScheduleMap.put(1000, 0.001);

MultiLayerConfiguration architecture = new NeuralNetConfiguration.Builder()
      .seed(seed)
      .l2(0.0005)
      .updater(new Nesterovs(new MapSchedule(ScheduleType.ITERATION, learningScheduleMap)))
      .weightInit(WeightInit.XAVIER)
      .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
      .updater(Updater.NESTEROVS)
      .list()
      // Features detection mask 5 x 5
      .layer(0, new ConvolutionLayer.Builder(5, 5)
            .nIn(numberOfChannels)
            .stride(1, 1)
            .nOut(10) // Número de kernels (objetos a serem classificados)
            .activation(Activation.RELU).build())
      // Pooling layer with MAX Pooling spatial invariance
      .layer(1, new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
            .kernelSize(2, 2)
            .stride(2, 2)
            .build())
      .layer(2, new ConvolutionLayer.Builder(5, 5)
      		.stride(1, 1)
      		.nOut(50)
            .activation(Activation.RELU).build())
      .layer(3, new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
            .kernelSize(2, 2)
            .stride(2, 2)
            .build())
      .layer(4, new CnnLossLayer())
      .layer(5, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
            .nOut(outputNum)
            .activation(Activation.SOFTMAX)
      .build())
      .setInputType(InputType.convolutionalFlat(1024, 1024, 3))
      .backprop(true)
      .pretrain(false)
      .build();
```
Like I said, this is just a sketch. At the moment, I was more concerned with implementing data input.

**Comment by AlexDBlack** [comment] 2018-09-26 01:55
> But if I set to NativeImageLoader(1024, 1024, 1);, isn't it going to load just the 1st channel of the images?

No, it's going to convert

> Actually is blank (transparent), not white. Black for road, transparent for non-road. Does it make difference to the net?

TBH I'm not sure exactly how it'll handle that during conversion (it should in theory still do what I mentioned though). I'd suggest double checking the values after loading.

```
      .layer(4, new CnnLossLayer())
      .layer(5, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
            .nOut(outputNum)
            .activation(Activation.SOFTMAX)
      .build())
      .setInputType(InputType.convolutionalFlat(1024, 1024, 3))
```

This should be:
```
      .layer(4, new CnnLossLayer.Builder().activationActivation.SIGMOID).lossFunction(LossFunction.XENT).build)
      .build())
      .setInputType(InputType.convolutionalFlat(1024, 1024, 3))
```

No OutputLayer (that's for 2d classification, it's inappropriate here). And the loss/activation are wrong, as I've already explained.

Second: I note that you have 1024x1024x3 input. That's fine, but then your network downsamples. Which means your output size isn't 1024x1024 anymore - it's smaller.
You can check the output size after building your net using .summary(InputType...).
So either fix your net to keep 1024x1024 output (which is actually kinda huge) via .stride(1,1).convolutionMode(ConvolutionMode.Same) OR adjust your label size (in the path label provider) to match the actual network output size.
For understanding activation sizes, these might help:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/ConvolutionMode.java
http://cs231n.github.io/convolutional-networks/#layersizepat

**Comment by ioannisbaptista** [comment] 2018-09-26 23:49
@AlexDBlack first of all I'd like to thank you so much for the help you have given me. You have no idea of the difference you've made, thank you very much. 🙏 

Tonight I'm going to read the text you sent me, as well as other related papers, so I can indeed work on the net architecture (that one is just a sketch I took from another example, the inputing was my major concern). The code is still firing errors (this time is _"java.lang.IllegalArgumentException: Labels and preOutput must have equal shapes: got shapes [4194304, 1] vs [256036, 1]"_) but I suspect that's an configuration issue.

What really would help a lot is to understand some things that are still poorly clear to me
1) > That's the point of the PathLabelGenerator - given the input image path, your implementation works that out and provides the label array.

I just saw your edit at this previous post. The thing is I still don't get how the ImageRecordReader handles the labels **in my case**. I mean, in the way I see it, the PathLabelGenerator that you helped me to implement, looks like only returns the files from a given folder. In this case, the parameter is the images folder, and that's it. The segmented images are in another folder in the same directory level (i.e., these two folders share the same parent) and I'm still trying to understand how the segmented images are loaded if no information about they is provided in custom the PathLabelGenerator.

2) > No, it's going to convert

I'm not sure if this is clear to me... Convert to a 1-channel grayscale image? But doesn't it cause some kind of loss?

3) Where can I read about how the data is stocked in the DataSet?

Thanks a lot Alex!

**Comment by saudet** [comment] 2018-09-27 03:13
@ioannisbaptista You'll need to provide the logic as to where your labels as part of your custom PathLabelGenerator, that's the reason you need to subclass it!

**Comment by saudet** [comment] 2018-09-27 03:14
And if NativeImageLoader doesn't do exactly what you need, it's possible to pass it a custom ImageTransform that transforms the image in exactly the way you need it before being converted into NDArray.

**Comment by AlexDBlack** [comment] 2018-10-08 00:40
Closing this as resolved. We can re-open if required.

**Closed by AlexDBlack** 2018-10-08 00:40 UTC
