### ISSUE TITLE
ReluLayer cannot handle singleton dimensions

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9792] opened 2022-09-27 10:09 UTC
#### Issue Description

- expected behavior: if the input dimensions of the Nd4j and SameDiff `reluLayer` ops are consistent, they should return a result.
- encountered behavior: if `batchSize`, `nIn`, or `nOut` are equal to 1, i.e., if at least one input dimension is singleton, `reluLayer` throws an exception.

Example for the case `nIn = 1`:
```
int b = 2;
int n = 4;

INDArray res1 = Nd4j.nn.reluLayer(Nd4j.ones(b, 1), Nd4j.ones(1, n), Nd4j.zeros(n)); // throws exception
System.out.println(res1);

SameDiff sd = SameDiff.create();
SDVariable res2 = sd.nn.reluLayer(sd.one(null, b, 1), sd.one(null, 1, n), sd.zero(null, n)); // throws exception
System.out.println(res2.eval());
```

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

* Exception stack trace of Nd4j:
```
Error at [/home/runner/work/deeplearning4j/deeplearning4j/libnd4j/include/ops/declarable/generic/nn/relu_layer.cpp:32:0]:
relu_layer: x argument should be a 2D tensor, but got rank 2 instead!
[main] ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to execute op relu_layer. Attempted to execute with 3 inputs, 1 outputs, 0 targs,0 bargs and 0 iargs. Inputs: [(FLOAT,[2,1],c), (FLOAT,[1,4],c), (FLOAT,[4],c)]. Outputs: [(FLOAT,[2,4],f)]. tArgs: -. iArgs: -. bArgs: -. Op own name: "b5667942-476d-4d02-847b-e9a26521a6f0" - Please see above message (printed out from c++) for a possible cause of error.
Exception in thread "main" java.lang.RuntimeException: Op [relu_layer] execution failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1561)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6566)
	at org.nd4j.linalg.factory.ops.NDNN.reluLayer(NDNN.java:479)
	at Layers.main(Layers.java:24)
Caused by: java.lang.RuntimeException: Op with name b5667942-476d-4d02-847b-e9a26521a6f0 and op type [relu_layer] execution failed with message Op validation failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1905)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1540)
	... 4 more
```
* Exception stack trace of SameDiff:
```
Error at [/home/runner/work/deeplearning4j/deeplearning4j/libnd4j/include/ops/declarable/generic/nn/relu_layer.cpp:32:0]:
relu_layer: x argument should be a 2D tensor, but got rank 2 instead!
[main] ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to execute op relu_layer. Attempted to execute with 3 inputs, 1 outputs, 0 targs,0 bargs and 0 iargs. Inputs: [(FLOAT,[2,1],c), (FLOAT,[1,4],c), (FLOAT,[4],c)]. Outputs: [(FLOAT,[2,4],c)]. tArgs: -. iArgs: -. bArgs: -. Input var names: [sd_var, sd_var_1, sd_var_2]. Output var names: [relu_layer] - Please see above message (printed out from c++) for a possible cause of error.
Exception in thread "main" java.lang.RuntimeException: Op with name relu_layer and op type [relu_layer] execution failed with message Op validation failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1905)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6575)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.doExec(InferenceSession.java:805)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:255)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:68)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:533)
	at org.nd4j.autodiff.samediff.SameDiff.directExecHelper(SameDiff.java:2963)
	at org.nd4j.autodiff.samediff.SameDiff.batchOutputHelper(SameDiff.java:2892)
	at org.nd4j.autodiff.samediff.SameDiff.output(SameDiff.java:2857)
	at org.nd4j.autodiff.samediff.SameDiff.output(SameDiff.java:2830)
	at org.nd4j.autodiff.samediff.config.BatchOutputConfig.output(BatchOutputConfig.java:183)
	at org.nd4j.autodiff.samediff.SameDiff.output(SameDiff.java:2786)
	at org.nd4j.autodiff.samediff.SDVariable.eval(SDVariable.java:1456)
	at Layers.main(Layers.java:30)
```

**Comment by agibsonccc** [comment] 2022-09-27 12:23
@CompilerCrash looking at that I see how that's not very intuitive. The actual c++ op actually also has a  built in dense layer. That isn't a normal relu op. I'm not sure how to handle that...maybe rename it?

**Comment by treo** [comment] 2022-09-27 13:17
There is a difference between relu and reluLayer here. 

reluLayer is explicitly documented as being ` relu(mmul(in,w) + bias)` whereas relu is ` x > cutoff ? x : 0`. 

I'm not sure if any renaming is really necessary here.

**Comment by agibsonccc** [comment] 2022-09-27 13:20
Yeah that's what I was thinking which is why I wanted to just confirm where the issue is.

**Comment by agibsonccc** [comment] 2022-09-27 21:22
@CompilerCrash feel free to reopen this but otherwise I'll close this one.

**Closed as completed by agibsonccc** 2022-09-27 21:22 UTC

**Comment by CompilerCrash** [comment] 2022-09-27 22:00
@agibsonccc sorry, I should have been more clear on this one. In my understanding, the `reluLayer` op should be equivalent to the `linear` op, followed by the `relu` op. If you do this simple replacement, the code suddenly works without an exception. This discrepancy is why I wrote this issue. I'll leave it to your discretion whether or not this really needs to be fixed (can't reopen this issue anyway).

Here the code that's supposed to be equivalent to the example in the issue description:
```
int b = 2;
int n = 4;

INDArray res1 = Nd4j.nn.relu(Nd4j.nn.linear(Nd4j.ones(b, 1), Nd4j.ones(1, n), Nd4j.zeros(n)), 0);
System.out.println(res1);

SameDiff sd = SameDiff.create();
SDVariable res2 = sd.nn.relu(sd.nn.linear(sd.one(null, b, 1), sd.one(null, 1, n), sd.zero(null, n)), 0);
System.out.println(res2.eval());
```
