### ISSUE TITLE
Wrong Exception msg in INDarray.reshape()

### ISSUE THREAD

**Issue by sascha08-15** [deeplearning4j/deeplearning4j#8263] opened 2019-10-03 11:12 UTC
#### Issue Description
When I reshape with a different dimension, it shows me a wrong error message.

Please describe our issue, along with:
- expected behavior : `org.nd4j.linalg.exception.ND4JIllegalStateException:` New shape length doesn't match original length: [60] vs [70]. Original shape: [14, 5] New Shape: [12, `5]`
- encountered behavior
`org.nd4j.linalg.exception.ND4JIllegalStateException:` New shape length doesn't match original length: [60] vs [70]. Original shape: [12, 5] New Shape: [12, 5]

	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3811)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3756)
	at `org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3877)`

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0-Beta5
* Platform information (OS, etc) Windows 10 latest

#### Additional Information
Minor bug and behavior as such seems to make sense; however, the error msg does contain wrong values (i.e. it uses 2x the new shape information instead of old vs new)

**Comment by AlexDBlack** [comment] 2019-10-03 11:51
thanks for reporting, but I'm not able to reproduce this on 1.0.0-beta5, using nd4j-native (CPU) backend.

Here's a simple test:
```
INDArray arr = Nd4j.create(DataType.FLOAT, 14, 5);
arr.reshape(12,5);
```

```
Caused by: org.nd4j.linalg.exception.ND4JIllegalStateException: New shape length doesn't match original length: [60] vs [70]. Original shape: [14, 5] New Shape: [12, 5]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3811)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.reshape(BaseNDArray.java:3756)
```

What backend are you using? Are you able to provide a way to reproduce this?

**Comment by sascha08-15** [comment] 2019-10-03 16:44
Thanks for the quick reply. I've isolated the problem and put it in a JUnit test. Here you go:

  ```
    @Test
    public void testBug8263() {

        double[][] data = {//
                {1d, 1d, 2d, 9d, 0d}, //
                {2d, 2d, 3d, 8d, 1d}, //
                {3d, 4d, 5d, 7d, 2d}, //
                {4d, 6d, 7d, 6d, 3d}, //
                {5d, 2d, 3d, 8d, 4d}, //
                {0d, 4d, 5d, 7d, 5d}, //
                {0d, 6d, 7d, 6d, 6d}, //
                {0d, 1d, 2d, 9d, 7d}, //
                {0d, 2d, 3d, 8d, 8d}, //
                {0d, 4d, 5d, 7d, 9d}, //
                {0d, 6d, 7d, 6d, 10d}, //
                {0d, 2d, 3d, 8d, 11d}, //
                {0d, 4d, 5d, 7d, 12d}, //
                {99d, 6d, 7d, 6d, 13d}};
        arr = Nd4j.create(data);
        System.out.println(arr);
        long[] shape = arr.shape();
        long[] stride = arr.stride();
        System.out.println(ArrayUtils.toString(shape));
        shape[0] = shape[0] - 2;

        Assertions.assertThrows(ND4JIllegalStateException.class, () -> {
            try {
                INDArray newArr = arr.reshape(shape);
            } catch (ND4JIllegalStateException e) {
                assertEquals("New shape length doesn't match original length: [60] vs [70]. Original shape: [14, 5] New Shape: [12, 5]", e.getMessage());
                throw e;
            }
        });
    }
```
Am using the CPU Backend, can tell in a couple of minutes if that happens on GPU as well.

**Comment by RobAltena** [comment] 2019-10-04 00:08
To reshape an array instead of:
` shape[0] = shape[0] - 2;`

try:
`arr.reshape(...);`

**Comment by AlexDBlack** [comment] 2019-10-04 13:25
Looks like this is the same issue as here: https://github.com/eclipse/deeplearning4j/issues/7091
Essentially, it's not safe to modify the java long[] shape array, and there's no good reason to do that.
We have reshape methods etc which you should use instead.

Thanks for the issue, but I'll close this as a duplicate. of the aforementioned issue. And as per that issue, I'm still in favor of no change - our options are a major breaking API change or a lot of garbage generation, that's not going to help avoid problems in 99.9% of cases.

**Closed as completed by AlexDBlack** 2019-10-04 13:25 UTC
