### ISSUE TITLE
Received Mask Array Exception

### ISSUE THREAD

**Issue by iihusseinali** [deeplearning4j/deeplearning4j#3770] opened 2017-07-31 15:20 UTC
#### Issue Description
 I get the following error when I try to run my RNN:

Exception in thread "main" java.lang.IllegalArgumentException: Received mask array with shape [200, 360]; expected vector.
	at org.deeplearning4j.nn.conf.preprocessor.CnnToRnnPreProcessor.feedForwardMaskArray(CnnToRnnPreProcessor.java:125)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardMaskArray(MultiLayerNetwork.java:2042)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setLayerMaskArrays(MultiLayerNetwork.java:2368)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:993)
	at com.ads.lcpt.LCPT2.main(LCPT2.java:148)

NN Configuration is here: https://gist.github.com/iihusseinali/a86a7dcfbf9cb8c348af87aeac58d714

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc): Intel
* CUDA version, if used: Not used
* NVIDIA driver version, if in use: Not used.

#### Contributing

Please see gist link above. Would love to do what I can to help.

**Comment by AlexDBlack** [comment] 2017-08-18 11:33
We will need the data pipeline in order to reproduce this... how exactly are you producing your DataSetIterator?

**Comment by AlexDBlack** [comment] 2017-11-24 07:30
Closing this due to no reply (unable to reproduce without more info).

**Closed by AlexDBlack** 2017-11-24 07:30 UTC

**Comment by Ritaplfigueiredo** [comment] 2018-03-29 11:41
Hello @AlexDBlack. I know this is a closed issue. However, I am getting the same error when trying to use CnnToRnnPreProcessor. I am producing my DataSetIterator with CnnSentenceDataSetIterator, which if minLength!=maxLength actually creates a 2D mask array instead of a vector. 

How do I solve my error?

**Comment by AlexDBlack** [comment] 2018-03-29 21:35
@Ritaplfigueiredo Open a new issue with more details, including code - I'm unable to help if I can't reproduce the problem. Thanks.
