### ISSUE TITLE
deeplearning4j InvalidKerasConfigurationException

### ISSUE THREAD

**Issue by AimenKaa** [deeplearning4j/deeplearning4j#9072] opened 2020-08-22 10:23 UTC
deeplearning4j returning "Expected model class name Model (found Functional)." when trying to load a keras model. same happens when try to load it as sequential.

python :

from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np
model = ResNet50(weights='imagenet')
model.save("resnet50.h5")

java(spring)

public INDArray useModel(String name, Long id) throws Exception{
    File file= new File("src/main/uploads/image.jpg");
    String resnet = "src/main/uploads/model/resnet50.h5";
    ComputationGraph model = KerasModelImport.importKerasModelAndWeights(resnet);
    NativeImageLoader loader = new NativeImageLoader(224, 224, 3);
    INDArray image = loader.asMatrix(file);
    INDArray[] output = model.output(image);
    return output[0];

}

mavn deps :
"
<dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-modelimport</artifactId>
        <version>1.0.0-beta7</version>
    </dependency>
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-core</artifactId>
        <version>1.0.0-beta7</version>
    </dependency>
    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-native-platform</artifactId>
        <version>1.0.0-beta7</version>
    </dependency>
    <dependency>
        <groupId>org.datavec</groupId>
        <artifactId>datavec-data-image</artifactId>
        <version>1.0.0-beta7</version>
    </dependency>
"

**Comment by agibsonccc** [comment] 2020-08-30 23:22
@AimenKaa I just worked on a resnet50 related issue and found something different. I was able to import the model fine. I fixed a semi related issue here: https://github.com/eclipse/deeplearning4j/issues/9061 I was also able to import the model fine. I'm closing this because I can't reproduce your issue here. Maybe try again with snapshots.

**Closed as completed by agibsonccc** 2020-08-30 23:22 UTC
Labels: DL4J Keras

**Comment by OysterQAQ** [comment] 2020-09-22 03:33
I have the same problem.
any updates about the issue?
