### ISSUE TITLE
ParallelWrapper has JsonMappingException with .weightInit(WeightInit.DISTRIBUTION)

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#3243] opened 2017-04-13 09:37 UTC
JsonMappingException occurs when I use .weightInit(WeightInit.DISTRIBUTION) as an weight initialization for the models.
please see the below info.

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class org.deeplearning4j.nn.conf.distribution.Distribution)
```
[model configuration](https://gist.github.com/kepricon/7531eb1f9bd5954406e3d6b017657d8b)
[full stack trace](https://gist.github.com/kepricon/576d582783aaa150f9a89bc767b677c9)

**Comment by kepricon** [comment] 2017-04-13 09:42
also relevant : https://github.com/deeplearning4j/deeplearning4j/issues/3122

**Comment by AlexDBlack** [comment] 2017-04-13 10:11
This very likely isn't specific to ParallelWrapper - it'll probably happen with anything doing to/from JSON (so ModelSerializer, Spark, etc also). Looks like a JSON encoding issue.

**Comment by AlexDBlack** [comment] 2017-04-13 12:25
I'm also unable to reproduce this on DL4J master - I can do to/from JSON ok - and the JSON looks fine (all type field are there)

However I am getting a crash when running the following on PW (and not alone), native and cuda: https://gist.github.com/AlexDBlack/03b4bb359a7aa5de05bdff788a761055
https://gist.github.com/AlexDBlack/9a90f8e981ef1e91aefc50206b846726
(it's possible I'm doing something wrong here, or there's some misconfiguration that isn't being picked up correctly).

**Comment by crockpotveggies** [comment] 2017-04-13 15:42
@AlexDBlack perhaps that's related to selecting Workspace.NONE?

**Comment by kepricon** [comment] 2017-04-14 07:36
@crockpotveggies I've tried this for a couple of hours.  it happens with WorkspaceMode.SINGLE

one thing I am sure is it happens when I use **PW**. I guess it can be the shade issue when PW creates trainer threads using model configurations.

has no concrete idea yet.

**Comment by AlexDBlack** [comment] 2017-04-14 12:41
So the crash issue I reported here earlier is now fixed (thanks to @raver119 ) - I can now run that code successfully (as a test in parallel wrapper module in DL4J). I'm still not able to reproduce the JSON mapping problem in the original issue.

@kepricon is there any repository that I can clone and run to reproduce this?

**Comment by kepricon** [comment] 2017-04-20 04:47
@AlexDBlack 
sorry I missed your comments. I'll share the code which can reproduce this.

**Comment by AlexDBlack** [comment] 2017-04-20 07:40
I'm able to reproduce this using the provided repo.
After some digging: it looks like to/from JSON are not thread safe for some reason (even though the underlying object mapper using Jackson *is* supposed to be thread safe).

**Closed** 2017-04-20 08:23 UTC
