### ISSUE TITLE
Training shared parameters networks

### ISSUE THREAD

**Issue by cgravier** [deeplearning4j/deeplearning4j#1634] opened 2016-06-02 07:54 UTC
I was considering the [Computation Graph API](http://deeplearning4j.org/compgraph) in order to train a shared parameter CNN.
One main example of such networks are siamese networks.
I don't think the API propose this yet (?)

Having discussed this with Adam on gitter, I am asking here so that maybe Alex could provided an insight on the current implementation w.r.t. such architectures.

Thanks.

**Comment by AlexDBlack** [comment] 2016-06-02 08:31
As noted in gitter: this is not yet supported

In theory, you could hack your way to equivalent functionality by stacking examples/activations and redistributing them after the layer, but I probably wouldn't recommend it. :)

**Comment by cgravier** [comment] 2016-06-02 12:58
thanks :)

**Comment by AlexDBlack** [comment] 2018-05-09 06:52
Duplicate of: https://github.com/deeplearning4j/deeplearning4j/issues/1785

**Closed by AlexDBlack** 2018-05-09 06:52 UTC
Labels: enhancement
