### ISSUE TITLE
mvn commamd built nd4j-native but not nd4j-cuda, what is the cause?

### ISSUE THREAD

**Issue by terU3760** [deeplearning4j/deeplearning4j#9191] opened 2021-02-26 08:45 UTC
#### Issue Description

Please describe our issue, along with:
- Successfully build nd4j-cuda
- nd4j-native was successfully built but nothing has been done with nd4j-cuda

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - current newest version
* Platform information (OS, etc) - Windows 10
* CUDA version, - CUDA Driver Version / Runtime Version - 11.1 / 10.2

#### Additional Information

Factually we have successfully built nd4j-native by run the command

mvn clean install -DskipTests=true

followinmg the instructions on this page: https://github.com/eclipse/deeplearning4j/tree/master/nd4j .

But we found the build is successful but it only generated files in these folders:
......\deeplearning4j\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native\target
......\deeplearning4j\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native-platform\target

no files even no target directory was generated in these folders:
......\deeplearning4j\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-cuda
......\deeplearning4j\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-cuda-platform

What is the cause? Should there be some modification to the configuration files or additional parameters should be appended to the build command maven?

**Comment by agibsonccc** [comment] 2021-02-26 09:54
@terU3760  again not a bug, closing this. If you have issues, please use the forums.

**Closed as completed by agibsonccc** 2021-02-26 09:54 UTC

**Comment by terU3760** [comment] 2021-02-26 10:44
Moved the question here: https://community.konduit.ai/t/mvn-commamd-built-nd4j-native-but-not-nd4j-cuda-what-is-the-cause/1206 . Anyone could please help us out?
