### ISSUE TITLE
Support dgetrs

### ISSUE THREAD

**Issue by haifengl** [deeplearning4j/deeplearning4j#6763] opened 2018-11-25 22:52 UTC
DGETRS solves a system of linear equations `A * X = B`  or  `A' * X = B` with a general N-by-N matrix A using the LU factorization computed by `DGETRF`. ND4J already supports DGETRF. But without DGETRS, we cannot leverage the LU decomposition effectively.

**Comment by saudet** [comment] 2018-11-27 00:41
Duplicate of #6764

**Closed by saudet** 2018-11-27 00:41 UTC
Labels: Duplicate, Enhancement, ND4J
