### ISSUE TITLE
openblas java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by borkox** [deeplearning4j/deeplearning4j#6241] opened 2018-08-21 20:32 UTC
Hi,
I have been using the deeplearning for a long time. I just experienced a problem, which I experience only when I start from terminal. Strange thing is that if I use the project run from Intellij I have no problem. Maybe from Intellij it uses MKL and from terminal it tries to use OPENBLAS. Intellij and terminal uses exactly the same java. Yesterday I had a skype call with my friend and he experienced the same problem with Windows 10. So I will give all the details:
1. java log
2. screenshots of where te DLL is
3. screenshot of ldd command to find dependencies
4. screenshot the it runs in IntelliJ with the same Java
5. output of command `java -XshowSettings:properties -version`  (seems not good formatted in github)
6. versions

=========================================================

> 
> borkox@BOBIPC D:\work\rltrader-copy\rltrader
>  "c:\Program Files\Java\jdk1.8.0_60\bin\java.exe" -Djava.library.path= -jar target/rltrader-1.0-SNAPSHOT.jar -trade
> 22:37:38,958 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
> 22:37:38,960 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
> 22:37:38,961 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/D:/work/rltrader-copy/rltrader/target/rltrader-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/logback.xml]
> 22:37:39,063 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@69663380 - URL [jar:file:/D:/work/rltrader-copy/rltrader/target/rltrader-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/logback.xml] is not of type file
> 22:37:39,262 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
> 22:37:39,297 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
> 22:37:39,318 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
> 22:37:39,397 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@5b37e0d2 - Will use zip compression
> 22:37:39,488 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
> 22:37:39,563 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: log/debug.log
> 22:37:39,563 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [log/debug.log]
> 22:37:39,567 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
> 22:37:39,572 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
> 22:37:39,600 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
> 22:37:39,600 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
> 22:37:39,600 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
> 22:37:39,602 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
> 22:37:39,602 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
> 22:37:39,604 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
> 22:37:39,610 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.rltrader] to DEBUG
> 22:37:39,610 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.rltrader] to false
> 22:37:39,610 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[com.rltrader]
> 22:37:39,610 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[com.rltrader]
> 22:37:39,610 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
> 22:37:39,620 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4459eb14 - Registering current configuration as safe fallback point
> 
> 2018-08-21 22:37:39 INFO  o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
> 2018-08-21 22:37:41 INFO  o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 2
> Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
>         at java.lang.Runtime.loadLibrary0(Runtime.java:870)
>         at java.lang.System.loadLibrary(System.java:1122)
>         at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1225)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:983)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:882)
>         at org.bytedeco.javacpp.openblas_nolapack.<clinit>(openblas_nolapack.java:10)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:348)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:941)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:898)
>         at org.bytedeco.javacpp.presets.openblas_nolapack.blas_set_num_threads(openblas_nolapack.java:189)
>         at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:136)
>         at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:52)
>         at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:31)
>         at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:91)
>         at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:72)
>         at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1236)
>         at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:653)
>         at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5575)
>         at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5447)
>         at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:213)
>         at com.rltrader.App.<clinit>(App.java:22)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
>         at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
> Caused by: java.lang.UnsatisfiedLinkError: C:\Users\borkox\.javacpp\cache\openblas-0.3.0-1.4.2-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniopenblas_nolapack.dll: Can't find dependent libraries
>         at java.lang.ClassLoader$NativeLibrary.load(Native Method)
>         at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
>         at java.lang.Runtime.load0(Runtime.java:809)
>         at java.lang.System.load(System.java:1086)
>         at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1205)
>         ... 27 more
> 
===========================================================
![image](https://user-images.githubusercontent.com/21053237/44426802-51282e80-a598-11e8-9b14-edae89b5f515.png)
===========================================================
![image](https://user-images.githubusercontent.com/21053237/44426823-600ee100-a598-11e8-9285-d784be762dcf.png)
============================================================
![image](https://user-images.githubusercontent.com/21053237/44426856-7cab1900-a598-11e8-9628-c1d33540c593.png)

===========================================================

> > "c:\Program Files\Java\jdk1.8.0_60\bin\java.exe" -XshowSettings:properties -version
> Property settings:
>     awt.toolkit = sun.awt.windows.WToolkit
>     file.encoding = Cp1251
>     file.encoding.pkg = sun.io
>     file.separator = \
>     java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
>     java.awt.printerjob = sun.awt.windows.WPrinterJob
>     java.class.path = .
>     java.class.version = 52.0
>     java.endorsed.dirs = c:\Program Files\Java\jdk1.8.0_60\jre\lib\endorsed
>     java.ext.dirs = c:\Program Files\Java\jdk1.8.0_60\jre\lib\ext
>         C:\WINDOWS\Sun\Java\lib\ext
>     java.home = c:\Program Files\Java\jdk1.8.0_60\jre
>     java.io.tmpdir = C:\Users\borkox\AppData\Local\Temp\
>     java.library.path = c:\Program Files\Java\jdk1.8.0_60\bin
>         C:\WINDOWS\Sun\Java\bin
>         C:\WINDOWS\system32
>         C:\WINDOWS
>         D:\installs\ConEmuPack.180528\ConEmu\Scripts
>         D:\installs\ConEmuPack.180528
>         D:\installs\ConEmuPack.180528\ConEmu
>         D:\Python36\Scripts\
>         D:\Python36\
>         D:\Python365\Scripts\
>         D:\Python365\
>         C:\ProgramData\Oracle\Java\javapath
>         C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
>         C:\Program Files (x86)\Intel\iCLS Client\
>         C:\Program Files\Intel\iCLS Client\
>         C:\WINDOWS\system32
>         C:\WINDOWS
>         C:\WINDOWS\System32\Wbem
>         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
>         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
>         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
>         C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
>         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
>         C:\Program Files\Intel\WiFi\bin\
>         C:\Program Files\Common Files\Intel\WirelessCommon\
>         C:\Program Files\nodejs\
>         C:\Program Files\Git\cmd
>         C:\Program Files (x86)\GtkSharp\2.12\bin
>         C:\WINDOWS\System32\OpenSSH\
>         D:\tools\apache-maven-3.3.3\bin
>         C:\Program Files\Java\jdk1.8.0_60\bin
>         C:\Users\borkox\AppData\Local\Microsoft\WindowsApps
>         D:\mingw\bin
>         C:\Python27\Scripts
> 
>         .
>     java.runtime.name = Java(TM) SE Runtime Environment
>     java.runtime.version = 1.8.0_60-b27
>     java.specification.name = Java Platform API Specification
>     java.specification.vendor = Oracle Corporation
>     java.specification.version = 1.8
>     java.vendor = Oracle Corporation
>     java.vendor.url = http://java.oracle.com/
>     java.vendor.url.bug = http://bugreport.sun.com/bugreport/
>     java.version = 1.8.0_60
>     java.vm.info = mixed mode
>     java.vm.name = Java HotSpot(TM) 64-Bit Server VM
>     java.vm.specification.name = Java Virtual Machine Specification
>     java.vm.specification.vendor = Oracle Corporation
>     java.vm.specification.version = 1.8
>     java.vm.vendor = Oracle Corporation
>     java.vm.version = 25.60-b23
>     line.separator = \r \n
>     os.arch = amd64
>     os.name = Windows 10
>     os.version = 10.0
>     path.separator = ;
>     sun.arch.data.model = 64
>     sun.boot.class.path = c:\Program Files\Java\jdk1.8.0_60\jre\lib\resources.jar
>         c:\Program Files\Java\jdk1.8.0_60\jre\lib\rt.jar
>         c:\Program Files\Java\jdk1.8.0_60\jre\lib\sunrsasign.jar
>         c:\Program Files\Java\jdk1.8.0_60\jre\lib\jsse.jar
>         c:\Program Files\Java\jdk1.8.0_60\jre\lib\jce.jar
>         c:\Program Files\Java\jdk1.8.0_60\jre\lib\charsets.jar
>         c:\Program Files\Java\jdk1.8.0_60\jre\lib\jfr.jar
>         c:\Program Files\Java\jdk1.8.0_60\jre\classes
>     sun.boot.library.path = c:\Program Files\Java\jdk1.8.0_60\jre\bin
>     sun.cpu.endian = little
>     sun.cpu.isalist = amd64
>     sun.desktop = windows
>     sun.io.unicode.encoding = UnicodeLittle
>     sun.java.launcher = SUN_STANDARD
>     sun.jnu.encoding = Cp1251
>     sun.management.compiler = HotSpot 64-Bit Tiered Compilers
>     sun.os.patch.level =
>     sun.stderr.encoding = cp866
>     sun.stdout.encoding = cp866
>     user.country = US
>     user.dir = D:\work\rltrader-copy\rltrader
>     user.home = C:\Users\borkox
>     user.language = en
>     user.name = borkox
>     user.script =
>     user.timezone =
>     user.variant =
> 
>  java version "1.8.0_60"
>  Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
>  Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
> 
> 

=====================================================
>         <nd4j.version>1.0.0-beta2</nd4j.version>
>         <nd4j.backend>nd4j-native-platform</nd4j.backend>
>         <rl4j.version>1.0.0-beta2</rl4j.version>
>         <dl4j.version>1.0.0-beta2</dl4j.version>
>         <scala.binary.version>2.11</scala.binary.version>

**Comment by saudet** [comment] 2018-08-22 01:56
Could you set "org.bytedeco.javacpp.logger" system property to "slf4j" and post the debug log?

**Comment by borkox** [comment] 2018-08-22 06:08
Hi, I attached wat I have from file and from console.
I also attached te pom.xml file (renamed to log because it didn't uploaded first time). I made some exclusions in POM file, maybe that can cause me having trouble.

[debug.log](https://github.com/deeplearning4j/deeplearning4j/files/2309069/debug.log)
[console.log](https://github.com/deeplearning4j/deeplearning4j/files/2309070/console.log)

[pom.xml.log](https://github.com/deeplearning4j/deeplearning4j/files/2309072/pom.xml.log)

Regards

**Comment by borkox** [comment] 2018-08-22 06:18
I removed all exclusions from the pom, builded as spring-boot jar and still doesn't run. Maybe something is not included in the final jar.

![image](https://user-images.githubusercontent.com/21053237/44446121-629b2600-a5ec-11e8-84ef-8350baca3f0f.png)

**Comment by saudet** [comment] 2018-08-22 07:41
This happens only in Spring? I'm guessing that's what you mean by "terminal", so I'll mark this as a duplicate of #6132. If you have a way to reproduce this issue outside of Spring, please let me know! Thanks

**Closed by saudet** 2018-08-22 07:41 UTC

**Comment by borkox** [comment] 2018-08-22 07:54
I confirm this works on Linux with the same build process. I tried on couple of linuxes and it works. So maybe it is something with the path constructing. It doesn't necessary means it is 100% connected to spring-boot.

**Comment by saudet** [comment] 2018-08-22 22:15
Do you have a way to reproduce it on Linux or on Windows outside of Spring?

**Comment by borkox** [comment] 2018-08-23 07:26
No, I cannot reproduce outside of spring. But I just used a google cloud machine with Debian 9 and it works with spring-boot, I see it is using MKL as provider.
So I guess the not working combination is : spring-boot+openblas+Windows

**Comment by saudet** [comment] 2018-08-23 12:13
It's happening on Linux too, see issue #6132.
