### ISSUE TITLE
Create documentation for custom loss functions

### ISSUE THREAD

**Issue by rachmaninovquartet** [deeplearning4j/deeplearning4j#1194] opened 2016-02-26 20:04 UTC
The documentation for custom loss functions is currently lacking.

**Comment by chrisvnicholson** [comment] 2016-02-26 20:55
we'll fill this out at some point: http://deeplearning4j.org/customizelossfunction

**Comment by tmsimont** [comment] 2016-05-09 18:00
I looked at the link above and I'm lost about how to integrate a custom model into a MultiLayerConfiguration object with something like this code:
https://gist.github.com/tmsimont/8c08e821b5cbb813b71d532d782de1d9

I'm trying to have the output layer score come from the cosine distance between output and label

The relationship between `org.deeplearning4j.nn.conf.layers` and `org.deeplearning4j.nn.layers` and `org.deeplearning4j.nn.multilayer` is a little bit confusing. 

I see a factory pattern hiding in here somewhere, but I'm not seeing how it comes together in a way relevant to the code linked here: http://deeplearning4j.org/customizelossfunction

It's looking like you can't create new Configuration objects without adding to the hard-coded configuration/layer associations here:
https://github.com/deeplearning4j/deeplearning4j/blob/b1ffaddb67b6cf89ee97d40db931dd95f6cab742/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/factory/DefaultLayerFactory.java#L69

This seems like it really limits the ability to extend multi-layer networks in particular.

Is there something I'm missing about how to create a new layer model?

**Comment by tomthetrainer** [comment] 2017-01-18 06:17
This is a duplicate of #2647, or rather when #2647 is done this one will be solved as well.  Will note on other ticket that page stub https://deeplearning4j.org/customizelossfunction has been created and will fill that page out, move to #2647 for further comment

**Closed by tomthetrainer** 2017-01-18 06:17 UTC
Labels: documentation
