### ISSUE TITLE
Glove code giving NaN as output

### ISSUE THREAD

**Issue by sreethasreekumar** [deeplearning4j/deeplearning4j#1622] opened 2016-05-31 11:10 UTC
When running the code for Glove inside dl4j, its giving Nan as output. 
16:37:02.443 [main] INFO  deeplearning.GloVeExample - Day/night similarity: NaN
16:37:02.465 [main] INFO  deeplearning.GloVeExample - Nearest words to 'day': [i, do, to, nt, the, that, s, he, you, is, we]. 
Please help to solve the issue.

**Comment by raver119** [comment] 2016-05-31 11:11
Please provide more details: what you're using as input text, what you're using as pom.xml etc. 
As much details as possible please

**Comment by treo** [comment] 2016-05-31 11:15
Just tried it as well. I see it using both rc3.9 and master (tried only the CPU backend).

**Comment by agibsonccc** [comment] 2016-05-31 11:19
Maybe try using double for the data type? http://nd4j.org/userguide

**Comment by raver119** [comment] 2016-05-31 11:19
Using float/double shouldn't affect results there. So that definitely sounds like a problem.

**Comment by sreethasreekumar** [comment] 2016-05-31 12:07
<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-nlp</artifactId>
    <version>0.4-rc3.9</version>
</dependency>
This is the dependency, I am using. 
And input the same rawtext.txt in the dl4j(resource) folder

**Comment by raver119** [comment] 2016-05-31 12:09
Show full pom.xml please

**Comment by sreethasreekumar** [comment] 2016-05-31 12:24
<properties>
  <nd4j.version>0.4-rc3.9</nd4j.version> 
  <dl4j.version>0.4-rc3.9</dl4j.version>
</properties>
  
 <dependencies>
<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-nlp</artifactId>
    <version>0.4-rc3.9</version>

</dependency>
<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-examples</artifactId>
    <version>0.0.3.1</version>
</dependency>

 <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>deeplearning4j-ui</artifactId>
     <version>0.4-rc3.9</version>
   </dependency>
<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4-rc3.9</version>
</dependency>
 </dependencies>

**Comment by agibsonccc** [comment] 2016-05-31 14:03
Could you get rid of the deeplearning4j-examples? I'm not sure where you would have gotten that from.

**Comment by RobAltena** [comment] 2017-07-24 05:04
Closing this (and https://github.com/deeplearning4j/dl4j-examples/issues/227) after verifying the Glove example runs fine on 0.8.0. Gist of output [here](https://gist.github.com/RobAltena/ee07ed279d67070564498ec205d70444).

**Closed by RobAltena** 2017-07-24 05:04 UTC
Labels: bug

**Comment by daanvdn** [comment] 2018-06-22 20:29
@RobAltena, @raver119  

This issue still occurs in dl4j versions 1.0.0-alpha and 1.0.0-beta, as mentioned in the comment here: https://github.com/deeplearning4j/deeplearning4j/issues/3462

Sometimes the NaN issue doesn't occur, but even if the similarity is a number then the results  are way off.  Is there any workaround or a fix on the roadmap?

**Comment by RobAltena** [comment] 2018-06-23 00:53
I closed this issue because it was inactive, old and many versions behind. And the example ran fine.
If you want to increase the odds of people looking into this issue then please submit a gist with an example to reproduce the bug. For even better odds: A failing unit test.

**Comment by daanvdn** [comment] 2018-06-23 10:07
@RobAltena do I submit the unit test via a pull request? Or do I just create a separate mini-project and add the unit test there?

**Comment by RobAltena** [comment] 2018-06-23 12:57
Create a separate mini project in a gist. Refer to it in a new issue. (Because this one really refers to an ancient version).
