### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path while loading DL4J MultiLayerNetworkAndNormalizer

### ISSUE THREAD

**Issue by kuntalgithub** [deeplearning4j/deeplearning4j#6666] opened 2018-11-06 02:15 UTC
Hi,
I am getting following exception on Linux while loading  DL4J **MultiLayer network**.

I have verified that following jars are part of my runtime setup  /<MY_ACCOUNT>/.javacpp/cache
mkl-dnn-0.15-1.4.2-linux-x86_64.jar 
nd4j-native-1.0.0-beta2-linux-x86_64.jar  
openblas-0.3.0-1.4.2-linux-x86_64.jar  

I have followed the getting started docs: http://deeplearning4j.org/quickstart.
We are using **<nd4j.backend>nd4j-native-platform</nd4j.backend>** 
for the for the artifact id.

Any help will be highly appreciated.

=================================
Caused by: java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1225)
	at org.bytedeco.javacpp.Loader.load(Loader.java:983)
	at org.bytedeco.javacpp.Loader.load(Loader.java:882)
	at org.bytedeco.javacpp.openblas_nolapack.<clinit>(openblas_nolapack.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:941)
	at org.bytedeco.javacpp.Loader.load(Loader.java:898)
	at org.bytedeco.javacpp.presets.openblas_nolapack.blas_set_num_threads(openblas_nolapack.java:189)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.setMaxThreads(CpuBlas.java:136)
	at org.nd4j.nativeblas.Nd4jBlas.<init>(Nd4jBlas.java:52)
	at org.nd4j.linalg.cpu.nativecpu.blas.CpuBlas.<init>(CpuBlas.java:31)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:91)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:72)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.getEnvironmentInformation(NativeOpExecutioner.java:1236)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.printEnvironmentInformation(DefaultOpExecutioner.java:649)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5575)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5447)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:213)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:254)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetworkAndNormalizer(ModelSerializer.java:422)
	at com.gbar.eventhub.processor.functions.anomaly.AnomalyDetector.initializeModel(AnomalyDetector.java:103)
	at com.gbar.eventhub.processor.functions.anomaly.AnomalyDetector.<init>(AnomalyDetector.java:93)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 26 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /ngs/app/cscdmt/.javacpp/cache/openblas-0.3.0-1.4.2-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjniopenblas_nolapack.so: libopenblas_nolapack.so.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1205)
	... 53 common frames omitted

**Comment by saudet** [comment] 2018-11-07 05:02
Duplicate of #6132

This has already been fixed, please use the newly released version 1.0.0-beta3. Thanks!

**Closed by saudet** 2018-11-07 05:02 UTC
Labels: Duplicate, ND4J, Question
