### ISSUE TITLE
ND4J: INDArray pile not matching expected shape

### ISSUE THREAD

**Issue by icantsayrural** [deeplearning4j/deeplearning4j#6838] opened 2018-12-11 13:43 UTC
```
INDArray a = Nd4j.create(new double[]{1, 2, 3}, new int[]{1, 3});
INDArray b = Nd4j.create(new double[]{4, 5, 6}, new int[]{1, 3});
Nd4j.pile(a, b)
```
This currently returns an `INDArray` with shape `(2, 3)` which is different from the expected shape `(2, 1, 3)` (to match [`numpy.stack`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html) with `axis=0`).

This is the behaviour from `org.nd4j:nd4j-native-platform:1.0.0-beta2`.

**Comment by raver119** [comment] 2018-12-11 13:51
Pile works properly, Use Nd4j.vstack or concat instead.

**Comment by raver119** [comment] 2018-12-11 13:58
I mean - it's not a bug. By definition pile stacks array vertically, AND adds additional dimension.

**Comment by raver119** [comment] 2018-12-11 14:00
However, it's a good question if we should keep this mechanic now, since we have 0D/1D in master.

cc @AlexDBlack

**Comment by raver119** [comment] 2018-12-11 14:04
I mean: when pile was added there were no 1D arrays, and vectors had shape [1, X].  So pile of vectors was 2D matrix. Now we have 1D vectors everywhere, and the same code should be stacked into 3D tensor.

**Comment by AlexDBlack** [comment] 2018-12-11 23:36
Yeah, I think we should always add extra dimension now, so pile([1,3],[1,2],0) returns [2,1,3].

**Comment by raver119** [comment] 2018-12-12 03:56
Kk, applied this change in my branch, will be merged together with other tweaks.

**Closed by raver119** 2018-12-12 03:56 UTC
