### ISSUE TITLE
Unable to compile DL4J due to an (ssExtractDependencies) java.net.URISyntaxException error

### ISSUE THREAD

**Issue by brunoneri** [deeplearning4j/deeplearning4j#8256] opened 2019-09-30 14:07 UTC
#### Issue Description
I am unable to compile DL4J and ND4J with native platform backend and also with CUDA platform backend.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta5
* Platform information (OS, etc): Ubuntu 16.04.06
* sbt version : 1.3.2

#### Additional Information

- Exception stack trace

[error] (update) java.net.URISyntaxException: Illegal character in path at index 116: https://repo1.maven.org/maven2/org/nd4j/nd4j-backend-impls/1.0.0-beta5/nd4j-backend-impls-1.0.0-beta5-linux-x86_64.${project.packaging}
[error] (ssExtractDependencies) java.net.URISyntaxException: Illegal character in path at index 116: https://repo1.maven.org/maven2/org/nd4j/nd4j-backend-impls/1.0.0-beta5/nd4j-backend-impls-1.0.0-beta5-linux-x86_64.${project.packaging}

- build.sbt(extract)
import yolo.builds.Libs
name := "yolo"
version := "0.1"
scalaVersion := "2.12.8"
libraryDependencies+= Libs.nd4s
libraryDependencies+= Libs.nd4jNativePlatform
libraryDependencies+= Libs.dl4jCore
libraryDependencies+= Libs.dl4jUi
libraryDependencies+= Libs.dl4jZoo

- Libs.scala (extract)
val dl4jVer = "1.0.0-beta5"
val dl4jCore            = "org.deeplearning4j" %  "deeplearning4j-core"             % dl4jVer
val dl4jUi              = "org.deeplearning4j" %% "deeplearning4j-ui"               % dl4jVer
val dl4jZoo             = "org.deeplearning4j" %  "deeplearning4j-zoo"              % dl4jVer
val nd4jCuda92Platform  = "org.nd4j"           % "nd4j-cuda-9.2"                    % dl4jVer
val nd4jNative          = "org.nd4j"           %  "nd4j-native"                     % dl4jVer
val nd4jNativePlatform  = "org.nd4j"           %  "nd4j-native-platform"            % dl4jVer
val nd4s                = "org.nd4j"           %% "nd4s"                            % dl4jVer

**Comment by saudet** [comment] 2019-10-01 00:36
Duplicate of https://github.com/sbt/sbt/issues/5046

**Closed as completed by saudet** 2019-10-01 00:36 UTC
Labels: Bug, Duplicate
