### ISSUE TITLE
Appropriate image channel order for predictions on imported keras models seems to differ when run on CPU/CUDA vs CuDNN 

### ISSUE THREAD

**Issue by ClnSchlssr** [deeplearning4j/deeplearning4j#5983] opened 2018-07-27 01:45 UTC
When comparing the outputs from models imported from Keras on different platforms (CPU/CUDA/CuDNN) I noticed that CuDNN gives a different output for the same image channel ordering, but the same output if the channels are flipped. 

For the image attached run through the models attached I get:

CPU:
Resnet:
RGB: 0.3022676706314087
BGR: 0.9479966163635254
Xception:
RGB: 0.012912283651530743
BGR: 0.002920493483543396

CUDA: 
Resnet:
RGB: 0.3022680878639221
BGR: 0.9479965567588806
Xception:
RGB: 0.01291227899491787
BGR: 0.00292049627751112

CUDNN:
Resnet:
RGB: 0.9479965567588806
BGR: 0.3022678792476654
Xception:
RGB: 0.0029204979073256254
BGR: 0.012912283651530743

Meanwhile, the models loaded by Keras in R give me (with no image channel altering):

Keras Resnet Output: 0.3022
Keras Xception Output: 0.00292

Code is attached but I'm flipping the image channel using:

```
            Java2DNativeImageLoader loader = new Java2DNativeImageLoader(tileSize, tileSize, 3);
            BufferedImage imgRGB = ImageIO.read(new File(imagePath));
            //Load as RGB and BGR to check if there is any channel order difference
            INDArray imageArrayRGBresnet = loader.asMatrix(imgRGB, false);
            INDArray imageArrayRGBxception = loader.asMatrix(imgRGB, false);
            INDArray imageArrayRGBresnetFlip = loader.asMatrix(imgRGB, true);
            INDArray imageArrayRGBxceptionFlip = loader.asMatrix(imgRGB, true);
```

Part of the reason I've been checking this is that in the [tf imagenet image preprocessing script](https://github.com/tensorflow/tensorflow/blob/883e8b6863511b46d7985e9ff8d1809ffe2a1bc0/tensorflow/python/keras/applications/imagenet_utils.py), the preprocessing type determines whether the channels are flipped, and different preprocessing is usually applied to resnet vs xception models. 

Could there be a difference in the preprocessing between the CPU, CUDA and CuDNN libraries which modifies the image channel order before a forward pass?

I'm using the POM to control which platform is used.

System Information:
DL4J: 1.0.0 - SNAPSHOT
Operating System: Win10
CUDA Version: 9.2 
cuDNN Version: 7.1
GPU: Nvidia GTX 1080ti
GPU Driver: 398.36

[models](https://drive.google.com/file/d/1AhdMJc4L-o6wBccgyGeHPLdaL23fkjQ7/view?usp=sharing)
[image](https://drive.google.com/file/d/12V7iN-mBYPtUSv-2_XGhksS8_Uak55GH/view?usp=sharing)
(Image is of some cells so be warned if you have trypophobia)

**Comment by saudet** [comment] 2018-07-27 02:45
cuDNN apparently only supports common strides, so we check for that and manually duplicate when necessary, such as here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-cuda/src/main/java/org/deeplearning4j/nn/layers/convolution/CudnnConvolutionHelper.java#L152
There could be a few missing checks for that...

**Comment by AlexDBlack** [comment] 2018-07-27 07:04
I'm unable to reproduce this. Find below the code I'm using (which uses the image + models from the initial issue post above).

Note this compares cuda and cudnn only.

```
        @Test
    public void test() throws Exception {

        int tileSize = 224;
        Java2DNativeImageLoader loader = new Java2DNativeImageLoader(tileSize, tileSize, 3);

        BufferedImage imgRGB = ImageIO.read(new File("C:/Temp/test_img.tif"));
        //Load as RGB and BGR to check if there is any channel order difference
        INDArray imageRGB = loader.asMatrix(imgRGB, false);
        INDArray imageBGR = loader.asMatrix(imgRGB, true);

        DataNormalization scaler = new ImagePreProcessingScaler(-1.0, 1.0);
        scaler.transform(imageRGB);
        scaler.transform(imageBGR);

        File modelFile = new File("C:/Temp/resnet-120618-sgdm.h5");
        ComputationGraph restoredCNN = KerasModelImport.importKerasModelAndWeights( modelFile.getAbsolutePath(), new int[]{tileSize, tileSize, 3}, false);

        INDArray outRGBCuDNN = restoredCNN.outputSingle(imageRGB);
        INDArray outBGRCuDNN = restoredCNN.outputSingle(imageBGR);

        CuDNNTestUtils.removeHelpers(restoredCNN.getLayers());
        CuDNNTestUtils.assertHelpersAbsent(restoredCNN.getLayers());

        INDArray outRGB = restoredCNN.outputSingle(imageRGB);
        INDArray outBGR = restoredCNN.outputSingle(imageBGR);


        assertEquals(outRGB, outRGBCuDNN);
        assertEquals(outBGR, outBGRCuDNN);




        modelFile = new File("C:/Temp/xception-210618-sgdm.h5");
        restoredCNN = KerasModelImport.importKerasModelAndWeights( modelFile.getAbsolutePath(), new int[]{tileSize, tileSize, 3}, false);

        outRGBCuDNN = restoredCNN.outputSingle(imageRGB);
        outBGRCuDNN = restoredCNN.outputSingle(imageBGR);

        CuDNNTestUtils.removeHelpers(restoredCNN.getLayers());
        CuDNNTestUtils.assertHelpersAbsent(restoredCNN.getLayers());

        outRGB = restoredCNN.outputSingle(imageRGB);
        outBGR = restoredCNN.outputSingle(imageBGR);

        assertEquals(outRGB, outRGBCuDNN);
        assertEquals(outBGR, outBGRCuDNN);
    }
```

ResNet:
![image](https://user-images.githubusercontent.com/2360237/43306512-cca3a60e-91be-11e8-9c40-b398ea402d09.png)

xception:
![image](https://user-images.githubusercontent.com/2360237/43306627-1a92824a-91bf-11e8-9ad4-ff773d615122.png)

**Comment by ClnSchlssr** [comment] 2018-07-27 21:09
I've determined that the platform is not affecting this. Instead the image is being randomly loaded with the channels flipped (with both CUDA and CuDNN) depending on whether which imageio library is being used to load it. Sorry for pulling that in the wrong direction... I had run it a couple times and gotten the same results so it did appear that the platform was causing the difference.

**Comment by saudet** [comment] 2018-07-30 01:17
@ClnSchlssr Probably don't need both, but that's deprecated at this point. We should use `NativeImageLoader`.

**Comment by saudet** [comment] 2018-07-30 03:15
Java2DNativeImageLoader isn't deprecated, @ClnSchlssr is loading TIFF *files* via ImageIO, which we're not recommending to do. Maybe we should just remove these dependencies and users would at least get an error instead of some strange behavior?

**Comment by AlexDBlack** [comment] 2018-07-30 03:22
Oh, not loading via our image loaders? Yeah, I'd say that's not our responsibility then.
We might be able to pull these dependencies out, but I'm not sure it's enough of an issue in practice to warrant the effort of doing so right now...

Anyway, sounds like this isn't an issue in our code - so I'm closing this.

**Closed by AlexDBlack** 2018-07-30 03:22 UTC

**Comment by AlexDBlack** [comment] 2018-07-30 04:06
@saudet hm, true...
https://github.com/deeplearning4j/deeplearning4j/issues/5997

**Comment by ClnSchlssr** [comment] 2018-07-30 17:24
@Saudet, thanks for drawing my attention to that. I actually hadn't realized I was doing it in a non-standard way. 
I think the reason I was using this approach is because using `flipChannels` was a convenient way to change the channel order for networks that expect it one way or another, but `Java2DImageLoader` doesn't have a `as.Matrix(File file, Boolean flipChannels)` . Some questions that arise from this for me: what is the correct way to load BufferedImages for the as.Matrix methods that take them? Is there a good reason to offer methods that take BuffuredImages if there's a risk of something like this happening (even if this is a pretty strange bug)?
 In any case, I really appreciate the help on this - you've saved me significant frustration and confusion.

**Comment by saudet** [comment] 2018-07-31 02:16
@ClnSchlssr The "risk" is with ImageIO, and only because DataVec is including dependencies it's not really using. So, should we remove them?
