### ISSUE TITLE
1.0.0-M1 bug DL4JClassLoading of CuDNN

### ISSUE THREAD

**Issue by jljljl** [deeplearning4j/deeplearning4j#9331] opened 2021-05-28 15:17 UTC
(reposted issue)
Hi! I found an issue and a way how to fix it.

#### Issue Description

Class org.deeplearning4j.common.config.DL4JClassLoading contains multiple createNewInstance() methods. Looks like they're overloaded in a wrong way.

1.    public static <T> T createNewInstance(String className, Object... args);
2.   public static <T> T createNewInstance(String className, Class<? super T> superclass);
3.    public static <T> T createNewInstance(String className, Class<? super T> superclass, Object [] args);
4.    public static <T> T createNewInstance(String className,  Class<? super T> superclass, Class<?>[] parameterTypes, Object [] args);

`at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:57)`
```helperRet =  DL4JClassLoading.createNewInstance(cudnnHelperClassName, layerHelperSuperClass, arguments);``` is meant to invoke 3rd method, but in fuct thread jumps to first method because it matches arguments. After that is mess arguments array and arguments Object[] { DataType } becomes Object[] { Class, Object[] }. So it throws that here is no method `org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,[Ljava.lang.Object;)`.

<details>

<summary>Screenshots</summary>

![bug0](https://user-images.githubusercontent.com/6739086/119870587-fb4bf680-bf3a-11eb-9332-02eedf0ddc21.jpg)
![bug1](https://user-images.githubusercontent.com/6739086/119870593-fc7d2380-bf3a-11eb-8ec4-e1dd12ef7ccc.jpg)

</details>

#### Suggestion

Best way here is to rename first method. Methods with dynamic array arguments "x()" can be renamed to "xArgs()".

<details>

<summary>Output</summary>

```
o.d.e.q.m.c.LeNetMNISTReLu - Data load...
o.d.e.q.m.c.LeNetMNISTReLu - Data vectorization...
o.d.i.r.BaseImageRecordReader - ImageRecordReader: 10 label classes inferred using label generator ParentPathLabelGenerator
o.d.i.r.BaseImageRecordReader - ImageRecordReader: 10 label classes inferred using label generator ParentPathLabelGenerator
o.d.e.q.m.c.LeNetMNISTReLu - Network configuration and training...
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.c.c.ND4JClassLoading - Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader.
o.n.c.c.ND4JClassLoading - Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader.
o.n.c.c.ND4JClassLoading - Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader.
o.n.c.c.ND4JClassLoading - Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader.
o.n.n.NativeOpsHolder - Number of threads used for linear algebra: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [8,0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.JCublasBackend - ND4J CUDA build version: 11.2.142
o.n.l.j.JCublasBackend - CUDA device 0: [NVIDIA GeForce RTX 3060]; cc: [8.6]; Total memory: [12884901888]
o.n.l.j.JCublasBackend - Backend build information:
 MSVC: 192829915
STD version: 201402L
CUDA: 11.2.142
DEFAULT_ENGINE: samediff::ENGINE_CUDA
HAVE_FLATBUFFERS
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
o.d.c.c.DL4JClassLoading - Cannot create instance of class 'org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper'.
java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,[Ljava.lang.Object;)
	at java.base/java.lang.Class.getConstructor0(Class.java:3508)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2711)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:103)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:89)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:74)
Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,[Ljava.lang.Object;)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:108)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:89)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:74)
	at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:57)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.initializeHelper(ConvolutionLayer.java:72)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.<init>(ConvolutionLayer.java:67)
	at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.instantiate(ConvolutionLayer.java:173)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:714)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:604)
	at org.deeplearning4j.examples.quickstart.modeling.convolution.LeNetMNISTReLu.main(LeNetMNISTReLu.java:148)
Caused by: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>(java.lang.Class,[Ljava.lang.Object;)
	at java.base/java.lang.Class.getConstructor0(Class.java:3508)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2711)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:103)
	... 9 more
```
  
</details>

#### Version Information

* org.deeplearning4j:deeplearning4j-cuda-11.2:1.0.0-M1
* cudnn-11.2-windows-x64-v8.1.1.33
* Windows 10
* Nvidia driver version 466
* Java SE 1.8
* User\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955\jre\bin\javaw.exe

I tried to commit it, but I cannot commit because here is no repository for deeplearning4j-cuda-11.2:1.0.0-M1 has been found. Here is only cuda-11.0 for SNAPSHOT version in repository which is not compiled correctly due to IDE settings difference.

It might not only be a bug of this version. It may also be in previous versions.

Also it may be cause by difference in JVMs behavior so they don't run overloaded methods in a same way.

================
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda-platform-redist</artifactId>
            <version>11.2-8.1-1.5.5</version>
        </dependency>
```
is working

**Comment by agibsonccc** [comment] 2021-05-31 03:13
@jljljl could you clarify the wrong behavior a bit? Some code + a stack trace to demonstrate the issue would help a lot. Thanks!

**Comment by jljljl** [comment] 2021-05-31 15:57
@agibsonccc The misstake was wrong methods overloading. Here is pretty full explanation. Second image shows stack trace. Stack trace went 74 line instead of 92.

But anyway it is fixed just accept merge request. Check https://github.com/eclipse/deeplearning4j/pull/9333 commits require to be checked

**Comment by cyberbeat** [comment] 2021-06-03 08:49
I stumbled upon the same problem, using CUDA is impossible with current dl4j SNAPSHOT. The constructor

`public static <T> T createNewInstance(String className, Object... args) {`

seems too generic - the HelperUtils.createHelper has this call:

```
 helperRet =  DL4JClassLoading.createNewInstance(
                        cudnnHelperClassName,
                        layerHelperSuperClass,
                        arguments);
```

but the above method is called, although this should be called:

`public static <T> T createNewInstance(String className, Class<? super T> superclass, Object [] args) {`

This is my stacktrace:

```
[pool-1-thread-15] ERROR org.deeplearning4j.common.config.DL4JClassLoading - Cannot create instance of class 'org.deeplearning4j.cuda.recurrent.CudnnLSTMHelper'.
java.lang.NoSuchMethodException: org.deeplearning4j.cuda.recurrent.CudnnLSTMHelper.<init>(java.lang.Class, [Ljava.lang.Object;)
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:103)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:89)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:74)
	at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:57)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.initializeHelper(LSTM.java:53)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.<init>(LSTM.java:49)
	at org.deeplearning4j.nn.conf.layers.LSTM.instantiate(LSTM.java:78)
	at org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional.instantiate(Bidirectional.java:139)
	at org.deeplearning4j.nn.conf.graph.LayerVertex.instantiate(LayerVertex.java:106)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:572)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:437)
	at org.deeplearning4j.nn.graph.ComputationGraph.setListeners(ComputationGraph.java:2921)
	at org.deeplearning4j.nn.graph.ComputationGraph.addListeners(ComputationGraph.java:2966)
	at com.linkedin.dagli.dl4j.NeuralNetwork$Preparer.initializeGraph(NeuralNetwork.java:197)
	at com.linkedin.dagli.dl4j.NeuralNetwork$Preparer.finish(NeuralNetwork.java:222)
	at com.linkedin.dagli.dl4j.NeuralNetwork$Preparer.finish(NeuralNetwork.java:50)
	at com.linkedin.dagli.nn.AbstractNeuralNetwork$Preparer.finishUnsafe(AbstractNeuralNetwork.java:1232)
	at com.linkedin.dagli.dag.MultithreadedDAGExecutor$PreparationFinishTask.onRun(MultithreadedDAGExecutor.java:792)
	at com.linkedin.dagli.dag.MultithreadedDAGExecutor$Task.run(MultithreadedDAGExecutor.java:368)
	at com.linkedin.dagli.dag.MultithreadedDAGExecutor$Scheduler.lambda$schedule$4(MultithreadedDAGExecutor.java:329)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "main" java.lang.RuntimeException: MultithreadedDAGExecutor terminated execution because it encountered an unexpected exception in a worker thread: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.recurrent.CudnnLSTMHelper.<init>(java.lang.Class, [Ljava.lang.Object;)
	at com.linkedin.dagli.dag.MultithreadedDAGExecutor.executeUnsafe(MultithreadedDAGExecutor.java:1546)
	at com.linkedin.dagli.dag.MultithreadedDAGExecutor.prepareUnsafeImpl(MultithreadedDAGExecutor.java:1497)
	at com.linkedin.dagli.dag.LocalDAGExecutor.prepareUnsafeImpl(LocalDAGExecutor.java:71)
	at com.linkedin.dagli.dag.AbstractDAGExecutor.prepareUnsafe(AbstractDAGExecutor.java:99)
	at com.linkedin.dagli.dag.DAG1x1.prepare(DAG1x1.java:253)
	at de.cyberbeat.wasgeht.ExtractorLoader.startLearnDL4J(ExtractorLoader.java:969)
	at de.cyberbeat.wasgeht.ExtractorLoader.main(ExtractorLoader.java:2060)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.recurrent.CudnnLSTMHelper.<init>(java.lang.Class, [Ljava.lang.Object;)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:108)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:89)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:74)
	at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:57)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.initializeHelper(LSTM.java:53)
	at org.deeplearning4j.nn.layers.recurrent.LSTM.<init>(LSTM.java:49)
	at org.deeplearning4j.nn.conf.layers.LSTM.instantiate(LSTM.java:78)
	at org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional.instantiate(Bidirectional.java:139)
	at org.deeplearning4j.nn.conf.graph.LayerVertex.instantiate(LayerVertex.java:106)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:572)
	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:437)
	at org.deeplearning4j.nn.graph.ComputationGraph.setListeners(ComputationGraph.java:2921)
	at org.deeplearning4j.nn.graph.ComputationGraph.addListeners(ComputationGraph.java:2966)
	at com.linkedin.dagli.dl4j.NeuralNetwork$Preparer.initializeGraph(NeuralNetwork.java:197)
	at com.linkedin.dagli.dl4j.NeuralNetwork$Preparer.finish(NeuralNetwork.java:222)
	at com.linkedin.dagli.dl4j.NeuralNetwork$Preparer.finish(NeuralNetwork.java:50)
	at com.linkedin.dagli.nn.AbstractNeuralNetwork$Preparer.finishUnsafe(AbstractNeuralNetwork.java:1232)
	at com.linkedin.dagli.dag.MultithreadedDAGExecutor$PreparationFinishTask.onRun(MultithreadedDAGExecutor.java:792)
	at com.linkedin.dagli.dag.MultithreadedDAGExecutor$Task.run(MultithreadedDAGExecutor.java:368)
	at com.linkedin.dagli.dag.MultithreadedDAGExecutor$Scheduler.lambda$schedule$4(MultithreadedDAGExecutor.java:329)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodException: org.deeplearning4j.cuda.recurrent.CudnnLSTMHelper.<init>(java.lang.Class, [Ljava.lang.Object;)
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:103)
	... 22 more


```

I can confirm the above patch working.

**Comment by agibsonccc** [comment] 2021-06-03 09:42
Perfect thanks. Let me figure out the issue with the tests and I'll get this merged tomorrow. and publish a build.

**Comment by agibsonccc** [comment] 2021-06-03 09:52
@cyberbeat Also, I wouldn't say it's impossible..deeplearning4j-cudnn is actually going to be deprecated. Please take a look at the new approach and see if that works for you: https://github.com/KonduitAI/deeplearning4j-gitbook-sync/blob/en-1.0.0-M1/multi-project/explanation/config/backends/config-cudnn.md

**Comment by jljljl** [comment] 2021-06-03 13:52
@cyberbeat this is fixed now https://github.com/eclipse/deeplearning4j/pull/9333 you also can find my forked repository with changes

**Comment by cyberbeat** [comment] 2021-06-03 16:03
@agibsonccc thanks, the new method works, too

**Closed as completed** 2021-06-05 12:16 UTC

**Comment by agibsonccc** [comment] 2021-06-05 12:17
@cyberbeat I merged @jljljl 's PR after a bit of testing on my side. We'll push out a quick M1.1 to address some of the issues that were found by the community. I've also disabled the old helpers by default since they're mostly being kept around in case of needing to preserve old behavior, you can see that here: https://github.com/eclipse/deeplearning4j/pull/9343

**Comment by jljljl** [comment] 2021-06-05 16:19
@agibsonccc have you fixed tests?

**Comment by agibsonccc** [comment] 2021-06-05 23:12
Yes I did. I think it was a stale dependency on my side. I do a lot of branch switching and sometimes have to double check that. That's why I kept asking if it worked for you. I managed to run the tests after a while.
