### ISSUE TITLE
rnnTimeStep causes fatal error on trained model?

### ISSUE THREAD

**Issue by lacic** [deeplearning4j/deeplearning4j#2548] opened 2016-12-20 16:01 UTC
Not sure if this belongs here or under nd4j issues, but I'll try to describe stepwise what's happening:

**Step 1**: A model and configuration was found and stored using the Arbiter example (resulting in  arbiter.model & arbiter-conf.json files being created) 

**Step 2:** The model is loaded and evaluated (custom code where **rnnTimeStep** is called with **no issues**)

**Step 3**: The stored configuration file is loaded and a new model is being trained using the same data as in Step 1

**Step 4**: The trained model is being evaluated in the same manner as Step 2, but when it reaches the first call of **rnnTimeStep** the following [error](https://gist.github.com/lacic/950fae61bdeb58ba82d6206212a99608) happens.

I've traced it a little in the MultiLayerNetwork, GravesLSTM and LSTMHelpers classes.

In MultiLayerNetwork it happens on the **2nd iteration** of  method
`public INDArray rnnTimeStep(INDArray input)` 
at line
`input = ((RecurrentLayer)this.layers[i]).rnnTimeStep(input);`

In the GravesLSTM it happens at
`private FwdPassReturn activateHelper(boolean training, INDArray prevOutputActivations, INDArray prevMemCellState, boolean forBackprop)`
when calling
`return LSTMHelpers.activateHelper(...);`

In LSTMHelpers it happens in the method
`public static FwdPassReturn activateHelper(...)`
when calling
`INDArray recurrentWeightsIFOG = recurrentWeights.get(new INDArrayIndex[] { NDArrayIndex.all(), NDArrayIndex.interval(0, 4 * hiddenLayerSize) }).dup('f');`

What's strange is that it happens only when loading the previously trained and stored model using the configuration file. Loading the stored model from Arbiter does not cause this issue.

What I also noticed is that when the training in Ste3 is finished and the model is stored, the Java process is still running (note that each of the Steps is a separate process/java file run individually one after the other). The process of Step 3 is needed to be manually killed (_another issue maybe?_)

Unfortunately, I don't have a runnable example code which I can share through gist at the moment. :/

**Comment by raver119** [comment] 2016-12-20 16:04
Are you on 0.7.1 or current master?

**Comment by lacic** [comment] 2016-12-20 16:04
0.7.1

**Comment by raver119** [comment] 2016-12-20 16:07
can you also provide that file as gist? hs_err_pid15404.log

**Comment by lacic** [comment] 2016-12-20 16:16
Here is the [log](https://gist.github.com/lacic/4af93b24ca7335c78d1100eca403dba3) file.

**Comment by lacic** [comment] 2016-12-20 16:31
Here is also the [conf](https://gist.github.com/lacic/24cb8f3c6411f71b77d86d2a005b4796) used to train the network.

**Comment by raver119** [comment] 2016-12-20 16:37
Interesting. Null pointer leaked into nativeOps?

**Comment by lacic** [comment] 2016-12-20 16:50
I've now tried to manually configure the network (in Java code) using the values from the configuration file.

It seems that this behaviour is happening when GravesLSTM layers are being stacked.

For example, this is the [hard-coded configuration](https://gist.github.com/lacic/26ec5e5c2acaa9b41887fd367655984b) which also produces the above mentioned error when trained, stored, loaded and evaluated. 

When we remove the 2 of the 3 GravesLSTM layers like in [here](https://gist.github.com/lacic/d5187c7e6d891a0945d36864c5bebda3), the trained models does not cause the error anymore.

**Comment by lacic** [comment] 2016-12-20 17:12
Hi again,

is it possible that the width of the hidden layer needs to be an even number ?

I've adapted the previous hard-coded configuration to have a hidden layer width of 20 ([gist](https://gist.github.com/lacic/dce122066d2d46c83b43d14d149bedc6)). In this case the error does not happen anymore.

After that I've tried the following experiments with the same network setup:
Exp1: Hidden Layer Width = 20
Exp2: Hidden Layer Width = 21
Exp3: Hidden Layer Width = 30
Exp4: Hidden Layer Width = 31
Exp5: Hidden Layer Width = 126
Exp6: Hidden Layer Width = 127 (this is the configuration which was found through Arbiter)

All the experiments with an **odd number** for the hidden layer width (Exp2, Exp4 and Exp6) would cause the error and all **even values** would produce results without any issues!!

**Comment by raver119** [comment] 2016-12-20 17:51
Despite even/odd numbers, it shouldn't cause segfault anyway. That what makes me really surprised in this issue...

**Comment by raver119** [comment] 2016-12-20 18:06
What's your value for numInput?

**Comment by lacic** [comment] 2016-12-20 18:16
NumInput is 1 (monthly values)

**Comment by raver119** [comment] 2016-12-20 19:05
I'm unable to reproduce it locally with your config so far.

Could you please provide me with shapes of your datasets/masks/features?

**Comment by lacic** [comment] 2016-12-20 20:37
Will do asap.

**Comment by raver119** [comment] 2016-12-20 20:51
One more nuance:

So you train model, save it using ModelSerializer, then load it using ModelSerializer, then second call to rnnTimeStep causes that crash. Am i right?

**Comment by lacic** [comment] 2016-12-20 21:30
Process 1:
Train mode by loading configl, save it using ModelSerializer

Process 2:
Load model using ModelSerializer, load data train features, test features and test labels using SequenceRecordReaderDataSetIterator.
Start to initialize the network by looping over the extracted rows (values per time step) of the train data. Fails at the first occurance of rnnTimeStep.

When I said "second call to rnnTimeStep", I was refereing to the MultiLayerNetwork class and what happens internally.

I'm currently preparing an example for that.

**Comment by raver119** [comment] 2016-12-20 21:40
Yes, reproducible example would be very handful here. Right now i'm doing +- the same you're doing (i'm using existing dataset iterators available in examples), and no matter what i do - it trains/evaluates fine

**Comment by lacic** [comment] 2016-12-20 22:41
Ok, here is the example. Hope that it can compile normally, I am currently on a totaly different PC than I normally use and nothing is setup at all (Java, Maven, IDE - just snippets from the git repo I use). :)

First there is a [SerializationUtils ](47c7cd47d590e07e5e6cba830b8dd167) class which takes care of the serialization stuff.  It is used in the provided train and evaluate examples.

The [TrainExample](https://gist.github.com/lacic/2e0271ebfd73f9189d6d46f65319024b) shows how I train the model using the above mentioned [configuration file](https://gist.github.com/lacic/24cb8f3c6411f71b77d86d2a005b4796). You will probably need to adapt the defined paths or create the needed folder structure. 

The [EvaluationExample](https://gist.github.com/lacic/283f0ab7746540633d6dcd5b64c4f5d0) loads from the same path the previously stored model and normalier files. Not sure if I am correctly converting the Integer value to the INDArray ?

In my case, I have 31 files, or rather time series examples to train and test on. The train and test split is 80/20 for each time series. For example, one time series produces then such [train/features/0.csv](https://gist.github.com/lacic/5cbe6bb05cc8865ed0dd24a926c04cab) , [train/labels/0.csv](https://gist.github.com/lacic/2787dcfeea47cba858b6fbe7b693929e) , [test/features/0.csv](https://gist.github.com/lacic/f78c8c768e30c6592d72e5dfb74ef4f5) and [test/labels/0.csv](https://gist.github.com/lacic/bfe292d9d56229e05da810b706869479) files (actually in my case 1 full TS has 60 rows which are split into a train and test set, but you get the point).

Hope that these examples can help you reproduce the error. The erro should happen in the EvaluatonExample on the first **rnnTimeStep** call. The only difference should be in the files used for training and testing.

**Comment by lacic** [comment] 2016-12-21 00:28
Just noticed that the link to the SerializationUtils was wrong. Is edited and should work now correctly.

**Comment by AlexDBlack** [comment] 2016-12-21 01:26
I'm not able to reproduce this yet, based on your code. I've tried on nd4j-native, both with 0.7.1 (openblas and MKL), as well as current master. Windows for all tests so far.

I have also tried to reproduce it separately (my own test) based on your description.

Can you provide the following details:
- Operating system
- ND4J backend
- Hardware (CPU and if relevant GPU)
- Java version


Also, to avoid any differences between what we are running: can you provide a github repo, that I can clone and essentially click run on?
With data etc that can reproduce it.

Unless there's something specific to your setup (OS, hardware, backend, etc) I'm not sure what else to try to reproduce this, based on the information provided so far.

**Comment by raver119** [comment] 2016-12-21 10:22
Please specify, if GPU was used with arbiter or first training.

**Comment by AlexDBlack** [comment] 2016-12-21 12:38
Info posted by @lacic earlier in gitter:

"GPU was not used"

Ubuntu 16.04.1
CPU i7-3770 @ 3.40 Ghz x 4
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
<java.version>1.8</java.version>
<nd4j.version>0.7.1</nd4j.version>
<dl4j.version>0.7.1</dl4j.version>
<datavec.version>0.7.1</datavec.version>
<arbiter.version>0.7.1</arbiter.version>


I've also tested (my reconstruction of) the provided code on Ubuntu 16.04 (native + cuda 7.5) and still can't reproduce the problem.

**Comment by raver119** [comment] 2016-12-21 12:39
The same, ubuntu 16.04, no luck.

**Comment by lacic** [comment] 2016-12-21 13:47
Hi,

while I was preparing the git repo for you to test it out more easily (with the above defined classes) I also successfully run everything. I looked then what I forgot to add in the examples and found the following line:

`DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE);` 

in the EvaluationExample class.

Basically I trained with Type.FLOAT (that is the default, or?) and then loaded the model and tried to evaluate with the Type.DOUBLE

Setting this property did cause the problem, and by removing it it from the EvaluationExample makes it run ok.

Is there a way to find out what was set at DataTypeUtil.setDTypeForContext (FLOAT or DOUBLE) while loading a model? Or to provide some warning?

**Comment by raver119** [comment] 2016-12-21 13:50
Ahhh... That explains a lot.

DataType switch is **dangerous**, when happens within single JVM. Just avoid doing that.

**Comment by raver119** [comment] 2016-12-21 13:53
Just to be clear: Sure, there's 0 problem if you're doing it in separate JVM, or you realize details of how that'll affect what you're doing. If doing that wrong you're might be easily able to get op call with one operand being float, and other operand being double, and there segfault will come, due to obvious arrays length difference.

But if you're starting new JVM, and setting dataType to anything, and then restoring model - you'll be just all fine, data will be transparently converted to target dataType.

**Comment by raver119** [comment] 2016-12-21 13:56
Btw, what is EvaluationExample? Can i have a link?

**Comment by lacic** [comment] 2016-12-21 16:20
That is basically the same gist as mentioned before. Here is a new [gist](https://gist.github.com/lacic/bd140dcf4853cc36e3f750832b03fc96) with the flag set in the beginning.

Interestingly, this does not happen if I train with `DataBuffer.Type.DOUBLE`, and then load and evaluate the serialized model in a different process where the same DataType was not set.

Thx for the help. DataType validation would be awesome.

**Comment by raver119** [comment] 2016-12-21 16:21
Hm, this gist -> https://gist.github.com/lacic/bd140dcf4853cc36e3f750832b03fc96

Does it reproduce crash for you 100%? That shouldn't happen. i'll double check ser/de.

**Comment by lacic** [comment] 2016-12-21 16:38
I've finally managed to create the [git repo](https://github.com/lacic/dl4j-2548) for the issue.

After **TrainExample** is run, **EvaluationExampleCorrect** will work fine, but **EvaluationExampleWithError** should cause the error (is at least for me the case). 

Can you check if it also happens at your side?

**Comment by raver119** [comment] 2016-12-21 16:42
Yes, it's 100% reproducible.

Thank you very much.

**Comment by raver119** [comment] 2016-12-21 17:58
Bug fixed, will be merged in few minutes.

Awesome job localizing this one. Highly appreciated.

**Closed** 2016-12-21 18:00 UTC
Labels: other fix
