### ISSUE TITLE
RL4J: Can't get pendulum task working

### ISSUE THREAD

**Issue by tobq** [deeplearning4j/deeplearning4j#8680] opened 2020-02-06 23:24 UTC
#### Issue Description

I'm creating a pendulum env like so: `new GymEnv<Box, Integer, ActionSpace<Integer>>("Pendulum-v0", false, false)` but an error is thrown on initialisation: `Python error occured`.

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform: Windows

#### Additional Information

Full Error: 
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Python error occurred
	at org.deeplearning4j.rl4j.mdp.gym.GymEnv.checkPythonError(GymEnv.java:57)
	at org.deeplearning4j.rl4j.mdp.gym.GymEnv.<init>(GymEnv.java:128)
	at org.deeplearning4j.rl4j.mdp.gym.GymEnv.<init>(GymEnv.java:96)
	at reinforcement.problems.Gym.<init>(Gym.java:29)
	at reinforcement.main.<clinit>(main.java:15)
```

pom.xml: https://gist.github.com/tobq/6e5bff34cab3c2d226cea0bc26e86990

**Comment by saudet** [comment] 2020-02-07 13:10
`Pendulum-v0` has a continuous action space. That's not supported by RL4J, yet.

/cc @aboulang2002 @Bam4d @RobAltena

**Comment by saudet** [comment] 2020-02-07 13:11
Duplicate of #5264

**Closed as completed by saudet** 2020-02-07 13:11 UTC
Labels: Enhancement, Duplicate, RL4J
