### ISSUE TITLE
KerasModelImport: NullPointerException for top_level_model_weights layer

### ISSUE THREAD

**Issue by Foorcee** [deeplearning4j/deeplearning4j#9524] opened 2021-11-14 12:11 UTC
#### Issue Description

When I try to import my pre-trained keras tensorflow model, I encounter a NullPointerException.

```
String simpleMlp = new ClassPathResource("model.h5").getFile().getPath();
this.model = KerasModelImport.importKerasSequentialModelAndWeights(simpleMlp);
```

I am not sure if it is related to #8827

#### Version Information

* Deeplearning4j version 1.0.0-SNAPSHOT
* Platform information (OS, etc) Win-10

[pom.xml](https://gist.github.com/Foorcee/53ce4d7c200efb7e4944ee8e05e88e87)

#### Additional Information

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.deeplearning4j.nn.modelimport.keras.KerasLayer.getNumParams()" because the return value of "java.util.Map.get(Object)" is null
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:274)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:151)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:326)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:218)
```

https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasModelUtils.java#L274

![](https://i.imgur.com/tE9f4pj.png)
![](https://i.imgur.com/RDqzZvZ.png)
![](https://i.imgur.com/tuGqJss.png)

**Comment by agibsonccc** [comment] 2021-11-15 11:36
@Foorcee could you send me the model somehow? I can take a look, we do support TF keras now. There might be something for your model we're missing though. Sorry but from your output (which is very good btw) it's kind of hard to tell at a glance what the problem might be without some digging.

**Comment by Foorcee** [comment] 2021-11-15 13:54
@agibsonccc https://foorcee.de/model/model.h5

**Comment by agibsonccc** [comment] 2021-11-30 00:41
@Foorcee could you tell be a bit about how you're building the model? It looks fairly simple but what I see in there is an extra attribute called model_weights/ I think this might be new. Do you know what version of keras this was built with?

**Comment by Foorcee** [comment] 2021-11-30 10:51
@agibsonccc I do not know exactly how to find out?
`print("Keras: ", keras.__version__, "Tensorflow: ", tf.__version__)` says `Keras:  2.7.0 Tensorflow:  2.7.0`

**Comment by agibsonccc** [comment] 2021-11-30 11:01
@Foorcee ok this confirms it.  A duplicate was raised here: https://github.com/eclipse/deeplearning4j/issues/9543 I'll close that one in favor of this one since there is a reproducer model here. It does appear to be a recent change in keras that added this parameter. I should have this fixed in a day or 2. Thanks for reporting!

**Closed as completed** 2021-12-01 08:27 UTC
Labels: DL4J Keras
