### ISSUE TITLE
How to build nd4j from source on Windows 10 with CUDA driver version 11.1 and a newest Nvidia GPU card device?

### ISSUE THREAD

**Issue by terU3760** [deeplearning4j/deeplearning4j#9181] opened 2021-02-10 04:00 UTC
#### Issue Description

Please describe our issue, along with:
- Sucessfully build nd4j.jar
- ./buildmultiplescalaversions.sh nor working on our situation

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - current newest version
* Platform information (OS, etc) - Windows 10
* CUDA version, -  CUDA Driver Version / Runtime Version - 11.1 / 10.2

#### Additional Information

Factually we have built libnd4j from souce on Windows 10 with CUDA driver version 11.1 and a newest Nvidia GPU card device and we've got the expected file: nd4jcuda.dll. Next we need to build nd4j from source. We searched the whole network and only found two guides on how to do the job. They are:

https://deeplearning4j.konduit.ai/getting-started/build-from-source

and

https://github.com/deeplearning4j/nd4j

but no matter the version of nd4j from here: https://github.com/deeplearning4j/nd4j or here: https://github.com/KonduitAI/deeplearning4j/tree/master/nd4j or here: https://github.com/eclipse/deeplearning4j/tree/master/nd4j
running the command:
./buildmultiplescalaversions.sh 

seems not working in our situation because our newest CUDA driver version 11.1 is still not supported in these files. But if run
mvn .....

command to build. What is the exactly command in our situation?

**Comment by agibsonccc** [comment] 2021-02-10 05:56
Closing this. Again, this is not a bug and double posting will not help you get answers faster. If you want guaranteed response times, please consider a commercial engagement with proper expectations and an SLA, otherwise you can also wait for our release. (I know neither option is ideal for you, but demanding something of an OSS project which you're using for free and repeatedly banging the door same day isn't reasonable either.) Thanks for understanding.

**Closed as completed** 2021-02-10 05:58 UTC
