### ISSUE TITLE
DataSetIterator with NormalizerMinMaxScaler causes NullPointerException: toPreProcess 

### ISSUE THREAD

**Issue by iskanderuse** [deeplearning4j/deeplearning4j#4214] opened 2017-10-27 13:45 UTC
#### Issue Description

The following code throws the Exception:

```
NormalizerMinMaxScaler  preProcessor = new NormalizerMinMaxScaler(-1,1);

public void train(DataSetIterator iterator){
        preProcessor.fit(iterator);
        iterator.setPreProcessor(preProcessor);
        for( int i=0; i<nEpochs; i++ ){
            iterator.reset();
            network.fit(iterator);
        }
         iterator.reset();
        //--- Exception is here:
        RegressionEvaluation evaluation = network.evaluateRegression(iterator);
        System.out.println(evaluation.stats());
    }
```

#### Version Information
        <nd4j.version>0.9.1</nd4j.version>
        <dl4j.version>0.9.1</dl4j.version>
        OS Windows 10

```
Exception in thread "ADSI prefetch thread" java.lang.RuntimeException: java.lang.NullPointerException: toPreProcess
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:442)
Caused by: java.lang.NullPointerException: toPreProcess
	at org.nd4j.linalg.dataset.api.preprocessor.AbstractDataSetNormalizer.preProcess(AbstractDataSetNormalizer.java:113)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:295)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:417)

```

**Comment by Tschigger** [comment] 2017-10-27 14:58
Possible duplicate of https://github.com/deeplearning4j/deeplearning4j/issues/3846.

**Comment by AlexDBlack** [comment] 2017-11-29 03:26
https://github.com/deeplearning4j/deeplearning4j/pull/4326

**Closed by AlexDBlack** 2017-11-29 03:26 UTC
