### ISSUE TITLE
Support dpotrs

### ISSUE THREAD

**Issue by haifengl** [deeplearning4j/deeplearning4j#6762] opened 2018-11-25 22:49 UTC
DPOTRS solves a system of linear equations `A*X = B` with a symmetric
positive definite matrix A using the Cholesky factorization `A = U**T*U or A = L*L**T` computed by DPOTRF. Although ND4J already supports DPOTRF, we cannot really use the decomposition without DPOTRS.

**Comment by saudet** [comment] 2018-11-27 00:40
Duplicate of #6764

**Closed by saudet** 2018-11-27 00:40 UTC
Labels: Duplicate, Enhancement, ND4J
