### ISSUE TITLE
WordVectorSerializer.writeParagraphVectors can't work when run large data

### ISSUE THREAD

**Issue by xueyuan1990** [deeplearning4j/deeplearning4j#4620] opened 2018-02-06 09:51 UTC
I run it with idea in window. version 0.9.1
```
val doc_in = "docpath"
val model = "modelpathl"
val file = new File(doc_in);
val iter = new BasicLineIterator(file)
val t = new DefaultTokenizerFactory();
t.setTokenPreProcessor(new CommonPreprocessor());
val source = new LabelsSource("DOC_");
val builder = new ParagraphVectors.Builder()
val vecsize = 200
val iterations = 10
var vec = builder.minWordFrequency(5).iterations(iterations).seed(119).epochs(1).windowSize(5)
  .sequenceLearningAlgorithm(new DM[VocabWord]()).iterate(iter).trainWordVectors(true).layerSize(vecsize) //.learningRate(0.025)
  .tokenizerFactory(t).workers(12).sampling(0) /*.labelsSource(source)*/ .build()
vec.fit();
WordVectorSerializer.writeParagraphVectors(vec, new File(model));
```

when I test on small data, it works well
But when the dataset is large, I get the message below:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Stream Closed
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeParagraphVectors(WordVectorSerializer.java:477)
	at com.meizu.algo.train.DocVector$.main(DocVector.scala:51)
	at com.meizu.algo.train.DocVector.main(DocVector.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: java.io.IOException: Stream Closed
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeWordVectors(WordVectorSerializer.java:393)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeParagraphVectors(WordVectorSerializer.java:687)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeParagraphVectors(WordVectorSerializer.java:475)
	... 7 more
Caused by: java.io.IOException: Stream Closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeWordVectors(WordVectorSerializer.java:392)
	... 9 more
```
Thank you for your help

**Comment by raver119** [comment] 2018-02-06 10:08
How large is large?

**Comment by xueyuan1990** [comment] 2018-02-06 10:42
@raver119 input file is 359277kb , has 10,000 docs in it.  when I set iterations=1 ,it works well, but when iterations>=2 , I get Stream Closed IOException.

**Comment by raver119** [comment] 2018-02-06 10:44
But that's saver exception. So i wonder: what's the number of words in vocabulary, and what's the vector length.

p.s. are you sure it's not just lack of free space on hard drive? It looks like that for me atm.

**Comment by xueyuan1990** [comment] 2018-02-06 10:47
@raver119 I think is no matter with the space.Because the output file of iterations=1 and iterations>=2 should be the same. The words size is about 300,000

**Comment by raver119** [comment] 2018-02-06 10:49
That's exactly the reason i'm thinking you're over hdd space :)

Look at your exception: that's `Stream Closed` exception. It has nothing to do with linear algebra or iterations.

**Comment by xueyuan1990** [comment] 2018-02-06 10:52
@raver119 You mean I have not enough space? But there is 356 GB in my hdd space

**Comment by raver119** [comment] 2018-02-06 10:53
Ok, i'll try to reproduce your issue. However, i've used paravec on WAY larger models, so i'm a bit skeptic here.

**Comment by xueyuan1990** [comment] 2018-02-06 11:00
@raver119 By the way, my doc is word segment of Chinese Article like "宋轶 礼服 太美 了 ，   一个 气质 如 兰 ，   颜值 绝 美的 妹纸  ". :-) Thank you for your answer.

**Comment by raver119** [comment] 2018-02-06 11:01
Post gist with your source code please, which **reproduces** this behavior.

**Comment by xueyuan1990** [comment] 2018-02-06 11:03
`
 val doc_in = "docpath"
    val model = "modelpathl"
    val file = new File(doc_in);
    val iter = new BasicLineIterator(file)
    val t = new DefaultTokenizerFactory();
    t.setTokenPreProcessor(new CommonPreprocessor());

    val source = new LabelsSource("DOC_");
    val builder = new ParagraphVectors.Builder()
    val vecsize = 200
    val iterations = 10
    var vec = builder.minWordFrequency(5).iterations(iterations).seed(119).epochs(1).windowSize(5)
      .sequenceLearningAlgorithm(new DM[VocabWord]()).iterate(iter).trainWordVectors(true).layerSize(vecsize) //.learningRate(0.025)
      .tokenizerFactory(t).workers(12).sampling(0) /*.labelsSource(source)*/ .build()
    vec.fit();
    WordVectorSerializer.writeParagraphVectors(vec, new File(model));
`

**Comment by xueyuan1990** [comment] 2018-02-06 11:05
@raver119 I  have post it in my question

**Comment by raver119** [comment] 2018-02-06 11:06
Thanks

**Comment by xueyuan1990** [comment] 2018-02-06 11:07
@raver119 Hope your further answer

**Comment by raver119** [comment] 2018-02-08 06:29
I'm worry, what's Special Processing?

**Comment by raver119** [comment] 2018-02-08 07:49
Ok, closing this issue.

**Closed by raver119** 2018-02-08 07:49 UTC
