### ISSUE TITLE
BlackOut to speed up RNN for large datasets (esp vocab)

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1524] opened 2016-05-09 18:13 UTC
Review paper http://arxiv.org/pdf/1511.06909v7.pdf for opportunities to integrate techniques.

**Comment by dapifer** [comment] 2017-05-01 16:43
This appears to be a duplicate of #1491.  Will be addressing it there; can we close this as a duplicate?

**Comment by AlexDBlack** [comment] 2017-05-10 10:16
Closed as duplicate: https://github.com/deeplearning4j/deeplearning4j/issues/1491

**Closed by AlexDBlack** 2017-05-10 10:16 UTC
Labels: enhancement, perf
