### ISSUE TITLE
Dropconnect - incorrect configuration validation warning

### ISSUE THREAD

**Issue by redfish41** [deeplearning4j/deeplearning4j#3248] opened 2017-04-14 03:21 UTC
#### Issue Description
In my MultiLayerConfiguration, I set useDropConnect to true and I also set a dropout rate for every layer. But the validation code says 'dropConnect is set to true but dropout rate is set to 0.0'.  
Below is my code link.
 https://gist.github.com/redfish41/809047ff1674962b0351c4f0ef969384

#### Version Information
dependencies
 <properties>
        <nd4j.backend>nd4j-native-platform</nd4j.backend>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <shadedClassifier>bin</shadedClassifier>
        <java.version>1.8</java.version>
        <nd4j.version>0.8.0</nd4j.version>
        <dl4j.version>0.8.0</dl4j.version>
        <datavec.version>0.8.0</datavec.version>
        <arbiter.version>0.8.0</arbiter.version>
        <guava.version>19.0</guava.version>
        <jfreechart.version>1.0.13</jfreechart.version>
        <maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
        <exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
    </properties>
 platform information windows 10

**Comment by AlexDBlack** [comment] 2017-04-14 03:52
As mentioned in gitter: The produced configuration is fine (values are set correctly), the issue seems to be just the warning/validation.

**Comment by AlexDBlack** [comment] 2017-04-18 06:15
Confirmed as simply an incorrect warning. Fixed here, will be merged soon: https://github.com/deeplearning4j/deeplearning4j/pull/3263

**Closed by AlexDBlack** 2017-04-18 06:15 UTC
