### ISSUE TITLE
Add system property for DL4J download net/data locations

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5102] opened 2018-05-09 08:20 UTC
For example, the location of pretrained nets from the model zoo...
my ```C:\Users\Alex\.deeplearning4j``` is currently at 7.4GB and is still growing as I run more of the model zoo tests :)

I would be nice if I could specify for it to use another location (i.e., another drive).
This applies to both the model zoo and things like SVHN and TinyImageNet etc

**Comment by saudet** [comment] 2018-05-10 05:17
That would be a duplicate of #4962

**Comment by AlexDBlack** [comment] 2018-05-21 00:44
A related idea, for unit tests:
Let's configure surefire so it uses a different (non-default) directory for these resources.
It's annoying to be using DL4J in one JVM only to have my resources (pretrained nets, data) deleted at random times by unit tests running in a separate JVM.

**Closed** 2018-05-29 01:27 UTC
Labels: Enhancement, Java
