### ISSUE TITLE
Arbiter UI NPE

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#8779] opened 2020-03-12 00:38 UTC
#### Issue Description

NPE in the arbiter basic example 
```
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.ui.VertxUIServer.stop(VertxUIServer.java:306)
	at org.deeplearning4j.arbiterexamples.quickstart.BasicHyperparameterOptimizationExample.main(BasicHyperparameterOptimizationExample.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

#### Version Information
beta6, macos

**Comment by AlexDBlack** [comment] 2020-03-13 08:20
So far I've been unable to reproduce this (5 runs through on master, CPU backend).
Was this on current master also?

**Comment by eraly** [comment] 2020-03-26 00:40
This was on beta6. I can try with snapshots and see if it is still an issue.

**Comment by eraly** [comment] 2020-04-01 17:40
Still seeing this on snapshots:

```
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.ui.VertxUIServer.stop(VertxUIServer.java:306)
	at org.deeplearning4j.arbiterexamples.quickstart.BasicHyperparameterOptimizationExample.main(BasicHyperparameterOptimizationExample.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by AlexDBlack** [comment] 2020-04-02 10:09
thanks. Though based on the line numbers, that doesn't make a whole lot of sense, as it would require the server field to be null, which it can't be

Line 306: https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-vertx/src/main/java/org/deeplearning4j/ui/VertxUIServer.java#L306

Unless there's a missing "caused by" here you haven't posted?
Can you post the complete output of the run? Maybe there's some other hint there

**Comment by eraly** [comment] 2020-04-04 22:20
I can't load the UI. I get "ERR_CONNECTION_REFUSED" when I try.

The run gives no other errors. Here is a snapshot of the screen

<img width="1260" alt="Screen Shot 2020-04-04 at 3 15 35 PM" src="https://user-images.githubusercontent.com/8340500/78462516-c4a48400-7687-11ea-9aa3-6523faf8ca84.png">

**Comment by printomi** [comment] 2020-04-21 11:34
I think that PR #8856 will fix this. In that PR, I replace `server.close()` with `vertx.close()`. In beta6, `server.close()` did not actually stop the UI.
I have run `BasicHyperparameterOptimizationExample` with my build of 1.0.0-SNAPSHOT on Windows, and the UI properly stopped.

**Comment by AlexDBlack** [comment] 2020-04-23 00:28
Closing this due to likely being fixed by this PR: https://github.com/eclipse/deeplearning4j/pull/8856

@eraly Can you retest to confirm it's fixed at some point? We'll re-open if not. Thanks

**Closed as completed by AlexDBlack** 2020-04-23 00:28 UTC

**Comment by eraly** [comment] 2020-04-25 18:18
Retested and I can confirm it is fixed. Thanks!
