### ISSUE TITLE
the JVM crashes

### ISSUE THREAD

**Issue by dayong0325** [deeplearning4j/deeplearning4j#8974] opened 2020-05-23 08:34 UTC
#### Issue Description
jvm crashes
#### Version Information

use: nd4j-native-platform
version: 1.0.0-beta6
The operating system：Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017

[hs_err_pid51585.log](https://github.com/eclipse/deeplearning4j/files/4671411/hs_err_pid51585.log)

**Comment by raver119** [comment] 2020-05-23 08:37
Can you do 2 things please?
1) Can you try your code with latest nd4j version, which is 1.0.0-beta7
2) Can you share the code that reproduces this crash?

**Comment by dayong0325** [comment] 2020-05-30 09:33
Thank you for your advice，I tried the beta7 version and it didn't work，

This is my code：
        ExecutorService executorService = Executors.newFixedThreadPool(5);
        for (int i = 0 ; i < 5 ; i++) {
            executorService.submit(() -> {
                INDArray src = Nd4j.zeros(new int[]{1, 2});
                INDArray tmp = Nd4j.create(new float[]{3, 4}, 2);
                src.put(NDArrayIndex.indexesFor(0), tmp);
                System.out.println(src);
            });
        }
        executorService.shutdown();

I'm using a docker environment, which in a docker container causes the JVM to crash, but runs well on the host(no in docker container)， So I don't know what's missing from the docker container, Importantly, only multithreaded calls can cause the JVM to crash。

**Comment by raver119** [comment] 2020-06-02 07:50
Hmm.. Docker container you're talking about. What OS it's based on? What's the base image? Maybe you could share it so I could reproduce your issue locally?

**Comment by treo** [comment] 2020-06-02 11:36
Can you also please add the crash log for the reproducing example?

**Comment by espentj** [comment] 2020-09-15 08:34
Same problem. Native part crashes immediately upon initialization

Note my call that causes the crash is the initialization of a dataarray with floats (nothing special about it).
DataBuffer buffy = new FloatBuffer(arr);

**Running it on docker base image:**
FROM azul/zulu-openjdk-alpine:13-jre

VOLUME /tmp

RUN adduser -D -s /sbin/nologin ingressuser

WORKDIR /opt
USER ingressuser
ENTRYPOINT ["java", "-XshowSettings:vm", "-XX:+PrintFlagsFinal", "-XX:MaxRAMPercentage=70", "-Djava.security.egd=file:/dev/./urandom", "-Djava.awt.headless=true", "-jar", "/opt/app.jar"]

**Maven dependencies:** 
nd4j-native:1.0.0-beta7
nd4j-native-platform:1.0.0-beta7

**Logger:**
"org.nd4j.linalg.factory.Nd4jBackend",
"message":"Loaded [CpuBackend] backend"}

A fatal error has been detected by the Java Runtime Environment:

> SIGSEGV (0xb) at pc=0x00000000000021c6, pid=1, tid=9
> 
> JRE version: OpenJDK Runtime Environment Zulu13.33+25-CA (13.0.4+8) (build 13.0.4+8-MTS)
> Java VM: OpenJDK 64-Bit Server VM Zulu13.33+25-CA (13.0.4+8-MTS, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
> Problematic frame:
> C  0x00000000000021c6
>

**Comment by espentj** [comment] 2020-09-15 08:34
Note my call that causes the crash is the initialization of a dataarray with floats (nothing special about it).
DataBuffer buffy = new FloatBuffer(arr);

**Comment by espentj** [comment] 2020-09-15 08:50
Tested azul/zulu-openjdk-centos:13 and it works there,

**Comment by agibsonccc** [comment] 2021-04-15 05:54
Closing due to lack of reproducibility.

**Closed as completed by agibsonccc** 2021-04-15 05:54 UTC
Labels: Bug, LIBND4J
