### ISSUE TITLE
"A fatal error has been detected by the Java Runtime Environment" when running ParagraphVectors.inferVector(), 1.0.0-alpha

### ISSUE THREAD

**Issue by xinxu75** [deeplearning4j/deeplearning4j#5072] opened 2018-05-07 06:48 UTC
#### Issue Description

I submitted this issue before for dl4j v0.80, and thought it was resolved after upgrading to 1.00-alpha. However when I built a new ParagraphVectors model and called the method inferVector() to infer a batch of new texts, the error came back again. The information about the issue is as follows:

I'm running DL4J on my personal laptop, within Eclipse IDE. If I saved the ParagraphVectors model to a file and then loaded the model from the same file to call ParagraphVectors.inferVector, I received the error message of "A fatal error has been detected by the Java Runtime Environment". One error report is in attachment. 

I noticed that this issue appears to be more likely to happen when the new text is a (slightly) longer sentence. The data for training the model and new texts are in Simplified Chinese, all being properly processed before using Dl4J.

The code snippet causing this issue is as follows, within a next() function of a DataSetIterator:

            for(int j=0; j<report.size(); j++){
                String stc = report.get(j);
                // this is where the problem is
                // m_SWV is loaded from a saved model, and proper TokenizerFactory has been set
                INDArray vector = ((ParagraphVectors)m_SWV).inferVector(stc);  

                features.put(new INDArrayIndex[]{NDArrayIndex.point(i), NDArrayIndex.all(), NDArrayIndex.point(j)}, vector);
                temp[1] = j;
                featuresMask.putScalar(temp, 1.0); 
            }

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0-alpha
* platform information (OS, etc): DELL Inspiron 15 laptop with Windows 8 as OS
* Java version: jdk1.8.0_60

[hs_err_pid4712_jdk1.8_60.log](https://github.com/deeplearning4j/deeplearning4j/files/1978729/hs_err_pid4712_jdk1.8_60.log)

**Comment by xinxu75** [comment] 2018-05-07 07:55
Hi there,

Just to share additional information. When I upgraded Java to version JDK 1.8.0_171, the error remained but the error message appeared to be different - it showed the error is from "org/bytedeco/javacpp/Pointer$NativeDeallocator" rather than "ParagraphVectors.inferVector(Ljava/lang/String;)"

I attached the error log under JDK 1.8.0_171 below, hopefully providing some insights?

Thanks a lot for your help

[hs_err_pid5128_jdk1.8_171.log](https://github.com/deeplearning4j/deeplearning4j/files/1978981/hs_err_pid5128_jdk1.8_171.log)

**Comment by treo** [comment] 2018-05-07 08:26
What you are seeing is probably something distinct from what you've reported earlier, but pointer dereference like that always looks pretty much the same.

Can you try the snapshots to see if the error still occurs? And if it still does, can you provide us with a self contained example that triggers the bug? 

An error like that usually only happens when you use something that isn't thread-safe in a threaded context, but I couldn't find any indication of that your log, so without something that we can use to reproduce the problem, it will take a lot longer to actually do something about it.

**Comment by xinxu75** [comment] 2018-05-07 10:26
I'm not sure how to replicate the error from your side? Do I need to upload the model file which is about 500MB?

**Comment by xinxu75** [comment] 2018-05-07 10:30
Also, on the thread-safety, just wondering if this is the cause for a simple situation such as above?

If this is indeed the multi-threading issue, how to resolve it? Much appreciated for your help

**Comment by treo** [comment] 2018-05-07 10:47
/cc @raver119 any idea?

@xinxu75 does the error still appear if you use 1.0.0-SNAPSHOT?

**Comment by xinxu75** [comment] 2018-05-07 11:39
How to get 1.0.0-SNAPSHOT? 

My project's Build Path depends on "dl4j-examples" Project (by "mvn clean install"), which in turn used 1.0.0-alpha. Now, within the .m2/org/.../1.0.0-SNAPSHOT/ directory, there is no .jar file?

**Comment by treo** [comment] 2018-05-07 11:46
https://deeplearning4j.org/snapshots

**Comment by xinxu75** [comment] 2018-05-07 11:46
Also, I suspected this error would persist, as it persisted from 0.8.0 to 1.0.0-alpha. From past experiences, when changing dl4j versions, the error may disappear for specific files, but may re-appear when different model files and/or different documents are used ...

**Comment by xinxu75** [comment] 2018-05-07 12:08
Hi there,

The existing POM.xml already has the following - does that mean it uses SNAPSHOT already? The error is the same.
-------------------------------------
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

**Comment by xinxu75** [comment] 2018-05-07 12:16
For the above example, when I change argument from -Xmx1g to -Xmx2g, the error will disappear. Hope this provides some clues?

**Comment by saudet** [comment] 2018-05-08 03:52
It sounds like something gets garbage collected earlier than it should, but when we give it enough memory, it just doesn't get deallocated as fast and a crash doesn't happen.

**Comment by xinxu75** [comment] 2018-05-08 04:32
So, what should be the solution or walk-around? Many thanks

**Comment by raver119** [comment] 2018-05-08 04:33
Workaround will be - just set higher xmx. Fix to be found yet.

**Comment by xinxu75** [comment] 2018-05-08 04:34
I've tried but it didn't work, as I've got hundreds of thousands of documents to inferVector ...

**Comment by xinxu75** [comment] 2018-05-08 04:36
only 5 sentences with -Xmx1g, you already see this error, you can imagine what memory required for, say 100,000 sentences ...

**Comment by raver119** [comment] 2018-05-08 04:37
I highly doubt there's linear correlation.

**Comment by raver119** [comment] 2018-05-08 04:38
And in any way - bug is accepted, and will be investigated and fixed as soon as we have free time slot.

**Comment by xinxu75** [comment] 2018-05-08 04:43
I tried 500GB, the error persists ...

BTW, typically how long it takes for you to investigate and potentially fix it? Thanks

**Comment by raver119** [comment] 2018-05-08 04:44
Show your source code please. as gist or pastebin.com link.

**Comment by xinxu75** [comment] 2018-05-08 04:45
My source code is already shown above, super-simple, only 10+ lines

**Comment by raver119** [comment] 2018-05-08 04:46
no, i mean paravec model. configuration you've used to build it.

**Comment by raver119** [comment] 2018-05-08 04:48
also, i need bigger chunk of inference code. 
Is inferVector() called in separate threads?

**Comment by xinxu75** [comment] 2018-05-08 04:48
Nope, single thread only from my code

**Comment by xinxu75** [comment] 2018-05-08 04:49
I'll copy paravec model building code soon here, also simple, mostly copied from dl4j examples ...

**Comment by raver119** [comment] 2018-05-08 04:50
Sounds very suspicious. Show model source code.

**Comment by xinxu75** [comment] 2018-05-08 04:58
Here the build model code:
-----------------------------------------------------------------------------
	public void build_wv(String sentencePath, String prefix, boolean suffix, boolean wrtFile, String delim, String seqAlg, int headSkip,
			int textPos, int labelPos, int vecSize, int minFreq, int numEpochs, int batchSz, int wdSz, int[] appTxt) throws Exception{
		
	    LabelAwareSentenceIterator iter=new LabelAwareAppendSentenceIterator(sentencePath, prefix, suffix, delim,
	    		headSkip, textPos, labelPos, appTxt);
	    String wvModelPath=((LabelAwareAppendSentenceIterator)iter).getWVModelPath();
	    	
	    TokenizerFactory tokenizerFactory = new DefaultTokenizerFactory();
	    tokenizerFactory.setTokenPreProcessor(new CommonPreprocessor());

	    // ParagraphVectors training configuration
	    if (seqAlg == null) seqAlg="org.deeplearning4j.models.embeddings.learning.impl.sequence.DM";
	    m_WV = new ParagraphVectors.Builder()
	    		.minWordFrequency(minFreq)
	    		.layerSize(vecSize)
                .windowSize(wdSz)
	    		.batchSize(batchSz)
	    		.epochs(numEpochs)
	    		.iterate(iter)
	    		.trainWordVectors(true)
	    		.tokenizerFactory(tokenizerFactory)
	    		.sequenceLearningAlgorithm(seqAlg) // need class name, not code name
//	    		.learningRate(0.025)
//	    		.minLearningRate(0.001)
	    		.build();
	    
	    // Start model training	    
	    ((ParagraphVectors)m_WV).fit();
	    if(wrtFile && wvModelPath!=null){
	    	System.out.println("Saving Models ...");
			Files.deleteIfExists(Paths.get(wvModelPath));
	    	WordVectorSerializer.writeParagraphVectors((ParagraphVectors)m_WV, wvModelPath);
	    }
	    System.out.println("Doc2Vec build Done");
	}
-------------------------------------------------------------

**Comment by raver119** [comment] 2018-05-08 05:00
What are actual values of these variables?
```
minWordFrequency(minFreq)
    		.layerSize(vecSize)
            .windowSize(wdSz)
    		.batchSize(batchSz)
    		.epochs(numEpochs)
    		.iterate(iter)
    		.trainWordVectors(true)
    		.tokenizerFactory(tokenizerFactory)
```

**Comment by xinxu75** [comment] 2018-05-08 05:01
The only new class is LabelAwareAppendSentenceIterator, which is almost the same as LabelAwareListSentenceIterator in 0.8.0. Because you removed this class in 1.0.0-alpha, I re-implemented it

**Comment by xinxu75** [comment] 2018-05-08 05:01
key parameters are:

	    int vecSize=450,
	    		minFreq=3,
	    		numEpochs=1,
	    		batchSz=200000,
	    		wdSz=45;

**Comment by raver119** [comment] 2018-05-08 05:06
Sorry, you re-implemented what? How you load your hundreds of thousands of sentences?

**Comment by xinxu75** [comment] 2018-05-08 05:10
it's the iterator. There is no problem reading hundreds of thousands of sentences when building the model

**Comment by xinxu75** [comment] 2018-05-08 05:10
the problem is to inferVector() hundreds of thousands of new sentences

**Comment by raver119** [comment] 2018-05-08 05:11
show source code of iterator please

**Comment by xinxu75** [comment] 2018-05-08 05:14
public class LabelAwareAppendSentenceIterator implements LabelAwareSentenceIterator{

    private int currPosition;
    private List<String> labels;
    private List<String> text;
    private String currentLabel;
    private SentencePreProcessor sentencePreProcessor;
    private String wvModelPath;

    public LabelAwareAppendSentenceIterator(String sentencePath, String prefix, boolean suffix, String delim, 
    		int headSkip, int textPos, int labelPos, int[] appTxt) throws IOException {
		System.out.println("Building sentence iterators ... ");

    	labels=new ArrayList<String>();
    	text=new ArrayList<String>();
	    try(BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(sentencePath), SINA_WV.utfCharset))){
	    	String buffer;
	    	int lineCount=0;
	    	br.mark(1); if(br.read()!=0xFEFF) br.reset();

	    	while((buffer=br.readLine()) != null){
	    		String[] tks=buffer.split(delim);

	    		if (lineCount<headSkip){
	    			if(suffix)
	    				wvModelPath = prefix+tks[labelPos]+".tar.gz";
	    			else
	    				wvModelPath = prefix+".tar.gz";
	    		}
	    		else {
	    			labels.add(tks[labelPos]);
	    		    if(appTxt!=null){
	    		    	String apppre = StringUtils.EMPTY,
	    		    			apppost = StringUtils.EMPTY;
	    		    	for(int a:appTxt){
	    		    		apppre += tks[a]+StringUtils.SPACE;
	    		    		apppost += StringUtils.SPACE+tks[a];
	    		    	}
		    			text.add(apppre+tks[textPos]+apppost);
	    		    } else {
	    		    	text.add(tks[textPos]);
	    		    }    						
	    		    // System.out.println(wvModelPath+": "+fullTxt.toString());
	    		}
	    		lineCount++;
	    	}
	    }
    }

    public String getWVModelPath(){
    	return wvModelPath;
    }
    
    public int totalLines(){
    	return text.size();
    }
    
    /**
     * Returns the current label for nextSentence()
     *
     * @return the label for nextSentence()
     */
    @Override
    public synchronized String currentLabel() {
        return currentLabel;
    }

    @Override
    public List<String> currentLabels() {
        return Arrays.asList(currentLabel);
    }

    /**
     * Gets the next sentence or null
     * if there's nothing left (Do yourself a favor and
     * check hasNext() )
     *
     * @return the next sentence in the iterator
     */
    @Override
    public String nextSentence() {
        String ret = text.get(currPosition);
        currentLabel = labels.get(currPosition);
        if (sentencePreProcessor != null)
            ret = sentencePreProcessor.preProcess(ret);
        currPosition++;
        return ret;
    }

    /**
     * Same idea as {@link java.util.Iterator}
     *
     * @return whether there's anymore sentences left
     */
    @Override
    public synchronized boolean hasNext() {
        return currPosition < text.size();
    }

    /**
     * Resets the iterator to the beginning
     */
    @Override
    public void reset() {
        currPosition = 0;

    }

    /**
     * Allows for any finishing (closing of input streams or the like)
     */
    @Override
    public void finish() {
        //no op
    }

    @Override
    public SentencePreProcessor getPreProcessor() {
        return sentencePreProcessor;
    }

    @Override
    public void setPreProcessor(SentencePreProcessor preProcessor) {
        this.sentencePreProcessor = preProcessor;
    }
}

**Comment by raver119** [comment] 2018-05-08 05:17
Just to be clear - you're loading hundreds of thousands of sentences into RAM?

**Comment by raver119** [comment] 2018-05-08 05:35
Some tests-related iterator (probably deleted long ago) wasn't suited for loading gigabytes of data.

In any way, i'll try to reproduce your issue on my box once i have free time.

**Comment by xinxu75** [comment] 2018-05-08 05:36
I think this implementation does not have problems when building the model. It reads 600K sentences and output to the model file

**Comment by xinxu75** [comment] 2018-05-08 05:37
So far I haven't seen issues on that part. So is my understanding correct?

**Comment by raver119** [comment] 2018-05-08 05:37
We will see soon.

**Comment by xinxu75** [comment] 2018-05-08 05:42
BTW, file with few 00K sentences is < 1GB, so that does not cause issue

**Comment by xinxu75** [comment] 2018-05-08 05:44
just wondering what may be typical timeline for your investigation and potentially finding solution? Thanks a lot

**Comment by xinxu75** [comment] 2018-05-08 14:36
BTW, I noted that the dl4j-examples project was automatically re-built, possibly due to SNAPSHOT update. Now this crash persistently happens regardless of any argument/option

**Comment by xinxu75** [comment] 2018-05-08 14:38
Let me know if I need to disable SNAPSHOT.

Also any quick workaround is much appreciated in case proper solutions may be difficult to find. Thanks

**Comment by raver119** [comment] 2018-05-12 15:56
We'll get to this problem before release, so in next few days i hope.

**Comment by xinxu75** [comment] 2018-05-13 01:35
Thanks raver119. So you also replicated this problem from your end? 
Look forward to your fixing the bug asap, and please let me know. Much appreciated

**Comment by xinxu75** [comment] 2018-05-18 04:02
@raver119, Hi raver119,
Just wondering any update on fixing this bug? Much appreciated

**Comment by xinxu75** [comment] 2018-05-27 09:46
@raver119, Hi raver119,
I tested today, and it looks this bug still persists. Just wondering if any progress? Much appreciated

**Comment by xinxu75** [comment] 2018-05-29 07:10
@treo, Hi there, I believe raver119 already well understood this issue/bug. Anyway, as requested I've created the following github project and uploaded the code (DL4JTest.java) you need to reproduce the bug (running with -Xmx1g).
https://github.com/xinxu75/DL4J-Bug-5072

However, it requires a model file "V3_PVec_ver1.tar.gz", which is ~500MB. Github does Not allow me to upload this file. Please let me know where I can upload this file? Thanks a lot

**Comment by treo** [comment] 2018-05-29 07:17
@xinxu75 I've asked for the full Project there, i.e. with your pom.xml and the directory structure and so on.

You can upload that file to a file hoster of your choice. Dropbox should work.

**Comment by xinxu75** [comment] 2018-05-29 10:12
@treo, Could you please provide your email account, for me to share file in Dropbox? Thanks

**Comment by xinxu75** [comment] 2018-05-30 06:57
@treo, I've shared the model file, which you may download from Google Drive. 

Just put the model file in the same directory of DL4JTest.java/.class, you should be able to run the code (DL4JTest.java) to reproduce this bug (running with -Xmx1g).

Let me know your questions or observations. Thanks

**Comment by treo** [comment] 2018-05-31 10:04
@xinxu75 Thanks. I could reproduce your crash.

@raver119 The following are my notes on the problem, while I was reproducing it and trying to find a workaround:

While adding a Workspace has reduced the probability of a crash, I could still get one every so often.

I've reproduced the problem now on Linux and Windows. Both of them using 1.0.0-beta. 

It looks very much like a race condition somewhere, as it doesn't crash as often when I run it on my dual core laptop (compared to the quad core desktop). 

Also interesting no note is that on Linux (OpenJDK 8, in contrast to Oracle JDK on Windows), it seems to crash the JVM during something seemingly unrelated. (see attachments)

Interestingly, on Windows setting OPENMP_NUM_THREADS=1 seems to work fine as a workaround. Running the demo code for 1k iterations resulted in no crashes. Yet on linux I still had some of those weird crashes. Maybe they actually are unrelated.

[hs_err_pid31260.log](https://github.com/deeplearning4j/deeplearning4j/files/2057732/hs_err_pid31260.log)
[replay_pid31260.log](https://github.com/deeplearning4j/deeplearning4j/files/2057733/replay_pid31260.log)

**Comment by xinxu75** [comment] 2018-06-01 14:31
@treo, Hi Paul,
Just to confirm in your workaround, should the Windows environment variable be OMP_NUM_THREADS=1 or OPENMP_NUM_THREADS=1? Thanks

**Comment by treo** [comment] 2018-06-01 14:33
@xinxu75 oh, right, looks like the heat-wave got the better of me. It should be OMP_NUM_THREADS=1

**Comment by xinxu75** [comment] 2018-06-03 05:52
@treo, @raver119 ,
Hi guys, I did some tests using a larger test data, over 100K sentences instead of 5 sentences in DL4JTest.java (provided to Paul earlier). This may be more realistic to test the workaround "OMP_NUM_THREADS=1" in Windows O/S. 

Unfortunately the same bug persists. Below are my observations:
1. I created two Doc2Vec models (algorithms: CBOW/DM), one with "OMP_NUM_THREADS=1" and another without setting this environment variable during model creation stage. 
When inferring vectors for the sentences with "OMP_NUM_THREADS=1", regardless which model was used, the crash happened when about 1/3 of the sentences were inferred

2. I created a Doc2Vec model using algorithms: SkipGram/DBOW (see hypotheses in #5406) with "OMP_NUM_THREADS=1". 
When inferring vectors for the sentences, whether with or without "OMP_NUM_THREADS=1", the crash happened when about 1/3 of the sentences were inferred (similar places as above)

3. I also tested the effect of -Xmx64g vs -Xmx16g, and it appeared they only affected when the crash happened, not fixing the crash issue.

4. I finally tried other permutations of "OMP_NUM_THREADS=1"(with vs without) during vector inference stage, Algorithms (CBOW/DM vs SkipGram/DBOW) and -Xmx (64g vs 16g), the same crash happened. The only difference is when it happened.
For example, Without "OMP_NUM_THREADS=1" during vector inference stage, the crash happened:
i) SkipGram/DBOW with -Xmx64g: about 1/3 of the sentences were inferred;
ii) SkipGram/DBOW with -Xmx16g: about 2/3 of the sentences were inferred - interestingly later than 64g
iii) CBOW/DM with -Xmx64g: about 100+ sentences were inferred
iv) CBOW/DM with -Xmx16g: only 8 sentences were inferred

5. All the tests above used Chinese characters with UTF-8, under Windows 8.1

Therefore, the general conclusion is that Paul's suggested workaround may affect the timing of the crash (depending on other factors), given big enough test sample. I don't know whether such timing may be random or not, but the underlying problem is not fixed by this workaround, or others like algorithms.

**Comment by raver119** [comment] 2018-06-03 05:55
Thanks for investigating this issue.

I think i know what’s wrong, so i hope it will be fixed once high priority
problems resolved (TF import issues should be solved first)

**Comment by xinxu75** [comment] 2018-06-03 06:21
@treo, @raver119,
Hi guys, 

May I suggest you conduct some tests using a reasonably big test corpus (maybe in English, e.g. Wikipedia), say, 100K-1M sentences to test inferVector(.) of Doc2Vec? This may give you a better picture how this crash occurs.

Also, not sure if the following observation is helpful:
During model creation stage, if I used "OMP_NUM_THREADS=1", I saw the following log:
[main] INFO org.deeplearning4j.models.embeddings.loader.WordVectorSerializer - Projected memory use for model: [198.78 MB]
However, regardless what happened in model creation, during vector inference stage (when loading the same model), also using "OMP_NUM_THREADS=1", I saw the following log (with half of the memory projected as above)
[main] INFO org.deeplearning4j.models.embeddings.loader.WordVectorSerializer - Projected memory use for model: [99.39 MB]

In general, it appears to me whatever done in model creation stage has little impact on the crashes (timing) in vector inference stage. 

Hope all the above observations help. Thanks

**Comment by xinxu75** [comment] 2018-06-03 06:29
@raver119,
Just saw you last comment. Look forward to your solutions. 

Could you kindly keep me posted when this can be resolved? If you think this resolution may take very long, I may consider using other approaches rather than waiting for Doc2Vec to be fixed ... Much appreciated

**Comment by xinxu75** [comment] 2018-06-26 02:04
@raver119, 
Hi raver119, I tried to run one of DL4J-Examples, CnnSentenceClassificationExample (org.deeplearning4j.examples.convolution.sentenceclassification.CnnSentenceClassificationExample), but with different data and Wordvectors models. I found the following "Bad number of bytes requested for allocation" error, after the first iteration of training.

Just wondering if this is the same memory allocation issue of TF as in this bug, or shall I submit a new issue/bug ticket?

The log message from CnnSentenceClassificationExample:
----------------------------------------------------------------
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/mmxxlh/.m2/repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/mmxxlh/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 2
o.n.n.Nd4jBlas - Number of threads used for BLAS: 2
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 8.1]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [14.2GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
o.d.n.g.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: SINGLE; inference: SINGLE]
Number of parameters by layer:
	cnn3	135100
	cnn4	180100
	cnn5	225100
	globalPool	0
	out	602
Loading word vectors and creating DataSetIterators
Starting training
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 0.8525929776123994
Bad number of bytes requested for allocation: -2051807296
Exception in thread "main" java.lang.RuntimeException: Number of bytes for allocation should be positive
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.execCustomOpFloat(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1695)
	at org.nd4j.linalg.convolution.Convolution.im2col(Convolution.java:213)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:387)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:278)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:442)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:105)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1680)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1566)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1349)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:173)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:59)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:970)
	at org.deeplearning4j.examples.convolution.sentenceclassification.CnnSentenceClassificationExample.main(CnnSentenceClassificationExample.java:132)

**Comment by raver119** [comment] 2018-06-26 03:33
Please update your examples clone by doing git pull. Issue you're asking about was fixed in 1.0.0-SNAPSHOTs, and basically it was really possible to get this exception before fix, especially with convolutional networks.

**Comment by xinxu75** [comment] 2018-06-26 06:30
@raver119, thanks. So this is a different issue. 

Just wondering if there's progress of the ParagraphVectors.inferVector issue and related (TF import) issues? Much appreciated

Also, the following is from POM.xml of dl4j-examples used in my project, therefore am I using 1.0.0-SNAPSHOT already?
----------------------------------------------- 
    <parent>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-examples-parent</artifactId>
        <version>1.0.0-alpha</version>
    </parent>

    <name>DeepLearning4j Examples</name>

    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

**Comment by xinxu75** [comment] 2018-07-05 03:43
@raver119, I've seen release note of 1.0.0-beta, but didn't find the bug fix for this ParagraphVector issue? Just wondering if this is fixed in the new release of 1.0.0-beta? Thanks

**Comment by treo** [comment] 2018-07-26 13:42
@raver119 

Using today's snapshots (nd4j-native-1.0.0-20180726.120726-4171) I'm still running into this bug. 
[hs_err_pid4428.log](https://github.com/deeplearning4j/deeplearning4j/files/2232218/hs_err_pid4428.log)

**Comment by raver119** [comment] 2018-07-26 13:44
Hm. Mind sending me your code in pm? My code doesn't reproduce this issue anymore.

**Comment by xinxu75** [comment] 2018-07-30 05:10
@raver119,@treo,
Hi guys, It's been almost 2 months since raver119 commented "I think i know what’s wrong, so i hope it will be fixed once high priority problems resolved (TF import issues should be solved first)". Just wondering if there is any update on fixing this bug? Many thanks

**Comment by raver119** [comment] 2018-07-30 05:18
Yep. This bug was considered fixed for a while, until @treo managed to reproduce it once again. So i'll be looking into it in nearest days once again.

**Comment by xinxu75** [comment] 2018-07-30 05:35
@raver119, thanks for the update. Could you please let me know as soon as you fix it, so that I can also test it from my side? Hopefully this helps shorten the lifecycle on this bug. Thanks

**Comment by raver119** [comment] 2018-07-30 05:36
Sure

**Comment by xinxu75** [comment] 2018-09-22 18:03
@raver119, Just wondering if there is any update on fixing this bug? It looks another 2 months since last update ... Thanks

**Comment by xinxu75** [comment] 2018-10-15 06:18
@raver119, I tested 1.0.0-beta2 today on this ParagraphVector issue, but looks the same bug persists...
Just wondering any update from your end? Thanks

**Closed** 2022-10-31 23:42 UTC
Labels: Bug, Release Burndown
