### ISSUE TITLE
NaN on arm server

### ISSUE THREAD

**Issue by liweigu** [deeplearning4j/deeplearning4j#8813] opened 2020-03-30 07:52 UTC
#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior
NaN occors in https://gist.github.com/liweigu/bfcbd2a6e612e02ad7b24fee3cfac235 for epoch=500.
It's ok for epoch=50.
The detail is at https://community.konduit.ai/t/nan-on-arm-server/320 .

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0.0-SNAPSHOT
* Platform information (OS, etc)
arm on Huawei
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment] 2020-04-02 07:20
We've checked libnd4j and nd4j tests on ARM. All tests pass, now we're going to check dl4j tests there.

But so far i suspect there's some kind of underflow/overflow due to hardware specifics.

**Comment by raver119** [comment] 2020-04-06 06:20
As expected, we see NaNs in couple of DL4J tests on ARM. However, it's just a few tests, and by the looks of it - it's really numeric stability issue. We'll keep looking into it.

**Comment by quickwritereader** [comment] 2020-12-23 06:27
so far it did not occur on arm32 builds. will test arm64 when I switch to it.

**Comment by quickwritereader** [comment] 2020-12-23 06:30
@liweigu 
could you test it again on your arm server with [the latest source codes](https://github.com/KonduitAI/deeplearning4j/)? 
I want to know if the issue is still relevant.
thanks

**Comment by liweigu** [comment] 2020-12-23 11:50
I shall try it out and reply recently.

**Comment by liweigu** [comment] 2020-12-24 03:30
Do i have to compile dl4j from source? Or, can i just use the SNAPSHOT by maven?

**Comment by quickwritereader** [comment] 2020-12-24 04:19
it would be better to use from the source. you can cross-compile to build it fast

**Comment by liweigu** [comment] 2020-12-25 07:26
After libnd4j and nd4j compiled, i got error on compiling datavec:
[ERROR] Failed to execute goal on project datavec-parent: Could not resolve dependencies for project org.datavec:datavec-parent:pom:1.0.0-SNAPSHOT: The following artifacts could not be resolved: **com.jakewharton.byteunits:byteunits:jar:${byteunits.version}, net.ericaro:neoitertools:jar:${neoitertools.version}**: Failure to find com.jakewharton.byteunits:byteunits:jar:${byteunits.version} in https://repo.maven.apache.org/maven2 was cached in the local repository

I'm compiling without openblas which might not be necessary i think.
The compiling command is:
```
export LIBND4J_HOME=/root/deeplearning4j/libnd4j
cd /root/deeplearning4j/datavec
mvn -Djavacpp.platform=linux-arm64 clean install -Dmaven.test.skip=true
```

How to solve it?

**Comment by saudet** [comment] 2020-12-25 07:31
It sounds like you may be using an old version of Maven.
Make sure you're running the latest version:
https://maven.apache.org/download.cgi

**Comment by liweigu** [comment] 2020-12-25 07:44
I get the same error with apache-maven-3.6.3.

It says:
[WARNING] The POM for com.jakewharton.byteunits:byteunits:jar:${byteunits.version} is missing, no dependency information available
But i cannot find the byteunits.version variable in the pom.

**Comment by saudet** [comment] 2020-12-25 07:51
It's there though: https://github.com/KonduitAI/deeplearning4j/blob/master/pom.xml#L263

**Comment by liweigu** [comment] 2020-12-25 07:58
Well, it's in the deeplearning4j/pom.xml.
And i can find ${byteunits.version} and ${neoitertools.version} in deeplearning4j/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/pom.xml, but even i hard code them to 0.9.1 and 1.0.0, and recompile nd4j-backends by `mvn -Djavacpp.platform=linux-arm64 clean install -Dmaven.test.skip=true -pl nd4j-backends`, the error is same for compiling datavec.

The full log:
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 19 modules...
[INFO] Not installing Nexus Staging features:
[INFO]  * Preexisting staging related goal bindings found in 19 modules.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] DataVec                                                            [pom]
[INFO] datavec-api                                                        [jar]
[INFO] datavec-data                                                       [pom]
[INFO] datavec-data-audio                                                 [jar]
[INFO] datavec-data-image                                                 [jar]
[INFO] datavec-data-codec                                                 [jar]
[INFO] datavec-arrow                                                      [jar]
[INFO] datavec-geo                                                        [jar]
[INFO] datavec-python                                                     [jar]
[INFO] datavec-local                                                      [jar]
[INFO] datavec-data-nlp                                                   [jar]
[INFO] datavec-hadoop                                                     [jar]
[INFO] datavec-spark_2.11                                                 [jar]
[INFO] datavec-spark-inference-parent                                     [pom]
[INFO] datavec-spark-inference-model                                      [jar]
[INFO] datavec-spark-inference-server                                     [jar]
[INFO] datavec-spark-inference-client                                     [jar]
[INFO] datavec-jdbc                                                       [jar]
[INFO] datavec-excel                                                      [jar]
[INFO] 
[INFO] ---------------------< org.datavec:datavec-parent >---------------------
[INFO] Building DataVec 1.0.0-SNAPSHOT                                   [1/19]
[INFO] --------------------------------[ pom ]---------------------------------
[WARNING] The POM for com.jakewharton.byteunits:byteunits:jar:${byteunits.version} is missing, no dependency information available
[WARNING] The POM for net.ericaro:neoitertools:jar:${neoitertools.version} is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for DataVec 1.0.0-SNAPSHOT:
[INFO] 
[INFO] DataVec ............................................ FAILURE [  0.334 s]
[INFO] datavec-api ........................................ SKIPPED
[INFO] datavec-data ....................................... SKIPPED
[INFO] datavec-data-audio ................................. SKIPPED
[INFO] datavec-data-image ................................. SKIPPED
[INFO] datavec-data-codec ................................. SKIPPED
[INFO] datavec-arrow ...................................... SKIPPED
[INFO] datavec-geo ........................................ SKIPPED
[INFO] datavec-python ..................................... SKIPPED
[INFO] datavec-local ...................................... SKIPPED
[INFO] datavec-data-nlp ................................... SKIPPED
[INFO] datavec-hadoop ..................................... SKIPPED
[INFO] datavec-spark_2.11 ................................. SKIPPED
[INFO] datavec-spark-inference-parent ..................... SKIPPED
[INFO] datavec-spark-inference-model ...................... SKIPPED
[INFO] datavec-spark-inference-server ..................... SKIPPED
[INFO] datavec-spark-inference-client ..................... SKIPPED
[INFO] datavec-jdbc ....................................... SKIPPED
[INFO] datavec-excel ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.133 s
[INFO] Finished at: 2020-12-25T15:46:22+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project datavec-parent: Could not resolve dependencies for project org.datavec:datavec-parent:pom:1.0.0-SNAPSHOT: The following artifacts could not be resolved: com.jakewharton.byteunits:byteunits:jar:${byteunits.version}, net.ericaro:neoitertools:jar:${neoitertools.version}: Failure to find com.jakewharton.byteunits:byteunits:jar:${byteunits.version} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by saudet** [comment] 2020-12-25 08:19
You need to build from the root of the repository, not in datavec.

**Comment by liweigu** [comment] 2020-12-25 09:04
Let me try it.

**Comment by quickwritereader** [comment] 2020-12-25 17:08
I tried the latest arm64 build on raspberry pi4 (raspios(debian buster) lite arm64).
it worked as well.

**Comment by liweigu** [comment] 2020-12-28 08:42
It worked well for me too.

By the way, a suggestion about compiling is to avoid accessing to **googleapis** durning maven building, because it was blocked on my side at < org.deeplearning4j:dl4j-spark_2.11 > with error:
```
Dec 25, 2020 8:46:19 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://maven-central.storage-download.googleapis.com:443: Connection reset
Dec 25, 2020 8:46:19 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://maven-central.storage-download.googleapis.com:443
```
(which should be ok on your side.)

I think this issue has been fixed. :-)

**Comment by quickwritereader** [comment] 2020-12-28 09:02
great.
I was told we will have a release. so I'm closing this issue

**Closed as completed by quickwritereader** 2020-12-28 09:02 UTC
Labels: Bug, ARM
