### ISSUE TITLE
ModelSerializer: output of a deserialized ComputationGraph  PreprocessorVertex: nullPointerException

### ISSUE THREAD

**Issue by atollFP** [deeplearning4j/deeplearning4j#1269] opened 2016-03-12 02:08 UTC
I used the latest snapshot with the newest merge fix for Deserialization of Computation Graph.
I used ModelSerializer to serialize and deserialzied a computation graph.

When trying to output from the model.

```
java.lang.NullPointerException
	at org.deeplearning4j.nn.graph.vertex.impl.PreprocessorVertex.doForward(PreprocessorVertex.java:65)
	at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:750)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:789)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:778)

```

**Comment by AlexDBlack** [comment] 2016-03-12 02:28
I can't reproduce this. Here's a unit test that I wrote to try, that runs fine:

```java
@Test
    public void testPreProcessorVertex() throws Exception {
        ComputationGraphConfiguration conf = new NeuralNetConfiguration.Builder()
                .graphBuilder()
                .addInputs("in")
                .addVertex("preproc", new PreprocessorVertex(new RnnToFeedForwardPreProcessor()), "in")
                .addLayer("out", new OutputLayer.Builder().nIn(1).nOut(1).build(), "preproc")
                .setOutputs("out")
                .build();

        ComputationGraph graph = new ComputationGraph(conf);
        graph.init();

        INDArray in = Nd4j.zeros(2,1,3);

        INDArray out = graph.output(in)[0];
        assertArrayEquals(new int[]{6,1},out.shape());

        String json = conf.toJson();
        ComputationGraphConfiguration conf2 = ComputationGraphConfiguration.fromJson(json);
        ComputationGraph graph2 = new ComputationGraph(conf2);
        graph2.init();
        INDArray out2 = graph2.output(in)[0];
        assertArrayEquals(new int[]{6,1},out2.shape());

        ModelSerializer.writeModel(graph,new File("C:/Temp/Debug/cg.zip"),true);
        ComputationGraph g = ModelSerializer.restoreComputationGraph(new File("C:/Temp/Debug/cg.zip"));
        INDArray out3 = g.output(in)[0];
        assertArrayEquals(new int[]{6,1},out3.shape());
    }
```

**Comment by atollFP** [comment] 2016-03-12 02:34
[comp.zip](https://github.com/deeplearning4j/deeplearning4j/files/170225/comp.zip)

Here is my serialized model. Takes as input an indarray of shape [4, 4, 3]. Do you have the same error as me ?

**Comment by AlexDBlack** [comment] 2016-03-12 02:36
I'm assuming that model was serialized before the fix? If you open up the file (it's just a zip) and look at the configuration.json, you'll see the PreprocessorVertex doesn't have any contents. In my test case after the fix, I do have the preprocessor listed there.

**Comment by atollFP** [comment] 2016-03-12 11:15
You're right. I used the old file (I changed the name of the file for save but not for load).

**Comment by AlexDBlack** [comment] 2016-03-12 11:21
Ok, cool. I'll close this then.

**Closed by AlexDBlack** 2016-03-12 11:21 UTC
