### ISSUE TITLE
Broken link in the doc

### ISSUE THREAD

**Issue by rishikksh20** [deeplearning4j/deeplearning4j#2744] opened 2017-01-25 10:00 UTC
In Quickstart home page the link of `Architecture` under `Open Source Community`  side menu throws `404 page not found` message  after clicking on it.

**Comment by tomthetrainer** [comment] 2017-01-25 18:04
Thanks

**Comment by rkfg** [comment] 2017-03-19 22:15
Duplicate of #2323

**Comment by tomthetrainer** [comment] 2017-03-22 00:31
Commented out so no more 404, real issue, we need an architecture page

**Closed by tomthetrainer** 2017-03-22 00:31 UTC
