### ISSUE TITLE
Wrong DeepAutoEncoder example in documentation

### ISSUE THREAD

**Issue by alexde989** [deeplearning4j/deeplearning4j#1082] opened 2016-01-29 05:22 UTC
http://deeplearning4j.org/deepautoencoder.html

https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/deepbelief/DeepAutoEncoderExample.java

The example in the documentation is wrong. Since the decoding layer does not use the transposed weights of the encoding layer.

Also there is no performance metric for how well an AutoEncoder is performing. How do you calculate the F1 Score, Precision and Recall.

Is there a correct example of an AutoEncoder anywhere ? I am looking for a simple working Autoencoder. Not a StackedAutoEncoder.

**Comment by nyghtowl** [comment] 2016-05-09 22:56
AutoEncoder code needs to be reviewed

**Comment by tomthetrainer** [comment] 2017-04-07 21:19
We currently had Variational AutoEncoder and a DeepAutoEncoder in examples. 

This is an old ticket, I assume the issue is addressed, that doc page may need another review, but that is another issue, closing this

**Closed by tomthetrainer** 2017-04-07 21:19 UTC
Labels: bug, documentation
