### ISSUE TITLE
Nd4j.arange()　in GPU Bug

### ISSUE THREAD

**Issue by titainic** [deeplearning4j/deeplearning4j#8356] opened 2019-11-05 03:12 UTC
#### Issue Description

INDArray data = Nd4j.arange(-1, 1, 0.01);
INDArray data = Nd4j.arange(-1, 1, 0.02);
INDArray data = Nd4j.arange(-1, 1, 0.08);
GPU info:
Expected vs provided shape mismatch [200] vs [201] at index 0

CPU　no problem
#### Version Information

1.0.0-beta5

* Deeplearning4j version
* Platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

Deeplearning4j version : 1.0.0-beta5
OS : Ubuntu16.04
CUDA versoon: 10.1
NVIDIA driver version:　nvidia 418.67 GTX1080

#### Additional Information
* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

Expected vs provided shape mismatch [200] vs [201] at index 0
Exception in thread "main" java.lang.RuntimeException: Op [range] execution failed
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2307)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6606)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.arange(BaseNDArrayFactory.java:346)
	at org.nd4j.linalg.factory.Nd4j.arange(Nd4j.java:2628)
	at com.dl4j.diff.demo.RegularizationAutoDiff.funationFx(RegularizationAutoDiff.java:65)
	at com.dl4j.diff.demo.RegularizationAutoDiff.main(RegularizationAutoDiff.java:35)
Caused by: java.lang.RuntimeException: Expected vs provided shape mismatch
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2491)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2297)

pom.xml

    

            
         <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-10.1-platform</artifactId>
            <version>1.0.0-beta5</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
             <version>1.0.0-beta5</version>
        </dependency>

**Comment by AlexDBlack** [comment] 2019-11-15 07:32
Confirmed to be an issue for CUDA only.
Seems to be C++ level issue. 

```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for OpenMP: 32
o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 0
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.JCublasBackend - ND4J CUDA build version: 10.1.168
o.n.l.j.JCublasBackend - CUDA device 0: [TITAN X (Pascal)]; cc: [6.1]; Total memory: [12884901888]
Expected vs provided shape mismatch [200] vs [201] at index 0



java.lang.RuntimeException: Op [range] execution failed

	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2304)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6560)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.arange(BaseNDArrayFactory.java:348)
	at org.nd4j.linalg.factory.Nd4j.arange(Nd4j.java:2606)
	at org.deeplearning4j.Temp.test(Temp.java:10)
...
Caused by: java.lang.RuntimeException: Expected vs provided shape mismatch
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2488)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2294)
```

Reproducible with:
```
Nd4j.arange(-1, 1, 0.01);
```

**Comment by AlexDBlack** [comment] 2019-11-15 07:42
Also reproducible with (what Nd4j.arange uses internally):
```
    @Test
    public void test(){
        DynamicCustomOp op = DynamicCustomOp.builder("range")
                .addFloatingPointArguments(-1.0, 1.0, 0.01)
                .build();

        List<LongShapeDescriptor> lsd = op.calculateOutputShape();
        System.out.println("Calculated output shape: " + Arrays.toString(lsd.get(0).getShape()));
        op.setOutputArgument(0, Nd4j.create(lsd.get(0)));

        Nd4j.exec(op);
    }
```
```
Calculated output shape: [201]
Expected vs provided shape mismatch [200] vs [201] at index 0

java.lang.RuntimeException: Op [range] execution failed
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2304)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6560)
	at org.deeplearning4j.Temp.test(Temp.java:23)
Caused by: java.lang.RuntimeException: Expected vs provided shape mismatch
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2488)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:2294)
	... 24 more
```

**Comment by raver119** [comment] 2019-11-15 08:13
Not reproducible on Linux. Might be Windows/MSVC specific issue.

**Comment by raver119** [comment] 2019-11-15 08:35
```
TEST_F(DeclarableOpsTests16, test_range_1) {
    nd4j::ops::range op;
    auto z = NDArrayFactory::create<float>('c', {200});

    Context ctx(1);
    ctx.setTArguments({-1.0, 1.0, 0.01});
    ctx.setOutputArray(0, &z);

    auto status = op.execute(&ctx);
    ASSERT_EQ(Status::OK(), status);
}
```

This test passes for me on both Windows and Linux...

**Comment by raver119** [comment] 2019-11-15 08:46
```
TEST_F(DeclarableOpsTests16, test_range_2) {
    nd4j::ops::range op;
    auto z = NDArrayFactory::create<float>('c', {200});

    double tArgs[] = {-1.0, 1.0, 0.01};

    auto shapes = ::calculateOutputShapes2(nullptr, op.getOpHash(), nullptr, nullptr, 0, tArgs, 3, nullptr, 0, nullptr, 0);
    shape::printShapeInfoLinear("Result", shapes->at(0));
    ASSERT_TRUE(shape::shapeEquals(z.shapeInfo(), shapes->at(0)));

    delete shapes;
}
```

Passes on Windows and Linux. Problem is somewhere else.

**Comment by raver119** [comment] 2019-11-15 09:44
Fixed in my branch. Just a precision issue on Java side. Will be merged later today with other fixes.

**Closed as completed by raver119** 2019-11-15 09:44 UTC
