### ISSUE TITLE
Can not only use second GPU

### ISSUE THREAD

**Issue by yylonly** [deeplearning4j/deeplearning4j#2374] opened 2016-11-25 15:34 UTC
I have two GPUs on the server 

> +------------------------------------------------------+                       
> | NVIDIA-SMI 352.93     Driver Version: 352.93         |                       
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Tesla K40m          On   | 0000:02:00.0     Off |                    0 |
> | N/A   50C    P0    78W / 235W |   4979MiB / 11519MiB |     75%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  Tesla K40m          On   | 0000:84:00.0     Off |                    0 |
> | N/A   41C    P0    77W / 235W |   2574MiB / 11519MiB |     94%      Default |
> +-------------------------------+----------------------+----------------------+

But when i try only use second GPU by 
`.useDevice(1)` 

I alway get the out of boundary error:

> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> 	at java.util.ArrayList.get(ArrayList.java:429)
> 	at org.nd4j.jita.constant.ConstantProtector.containsDataBuffer(ConstantProtector.java:56)
> 	at org.nd4j.jita.constant.ProtectedCudaShapeInfoProvider.createShapeInformation(ProtectedCudaShapeInfoProvider.java:60)
> 	at org.nd4j.linalg.jcublas.CachedShapeInfoProvider.createShapeInformation(CachedShapeInfoProvider.java:41)
> 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:172)
> 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:253)
> 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:290)
> 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:567)
> 	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:258)
> 	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:224)
> 	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4477)
> 	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4439)
> 	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3692)
> 	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:396)
> 	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:350)
> 	at net.mydreamy.encrpyed.ministdes.TranningEncrypedDESMinistMultiGPUFFSingle.main(TranningEncrypedDESMinistMultiGPUFFSingle.java:258)
> 	... 6 more
>

**Comment by raver119** [comment] 2016-11-25 15:35
Please show me what exactly you're doing.

**Comment by yylonly** [comment] 2016-11-25 15:40
code is here:
```
	   Configuration cudaconfig = CudaEnvironment.getInstance().getConfiguration();

           cudaconfig..allowMultiGPU(false).allowCrossDeviceAccess(false).useDevice(1);
```
I test get device api though
`log.info("Device list " + conf.getAvailableDevices().toString());`
I got

> [net.mydreamy.encrpyed.ministdes.TestGPUEnvironment.main()] INFO net.mydreamy.encrpyed.ministdes.TestGPUEnvironment - Device list [0, 1]

**Comment by raver119** [comment] 2016-11-25 15:43
As temporary workaround - please get rid of both calls, and just use CUDA environment variables to route computations to specific device.

And meanwhile i'll check what's wrong there.

**Comment by yylonly** [comment] 2016-11-25 15:47
> just use CUDA environment variables to route computations to specific device.
How to do that? Does you mean only use `cudaconfig.useDevice(1)` ?

**Comment by raver119** [comment] 2016-11-25 15:50
No, there's nVidia environment variables that limit number of devices available for given process.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars

You need the first one: CUDA_​VISIBLE_​DEVICES

**Comment by yylonly** [comment] 2016-11-25 15:54
Okay, let me try.

**Comment by yylonly** [comment] 2016-11-25 16:12
> export CUDA_VISIBLE_DEVICES=1

that is work for my case: only use second GPU 

however, I invoke `.getAvailableDevices()`, it shows that

> INFO net.mydreamy.encrpyed.ministdes.TestGPUEnvironment - Device list [0]

When i change export CUDA_VISIBLE_DEVICES=0, the API still shows that

> INFO net.mydreamy.encrpyed.ministdes.TestGPUEnvironment - Device list [0]

Maybe, this will help to figure out the bugs.

**Comment by raver119** [comment] 2016-11-25 16:24
No, that's not a bug. That's valid behavior. When you define CUDA_VISIBLE_DEVICE=1, for all subsequent calls it's assumed the only device, and is listed as 0.

I.e. if you have 8 devices on system and set CUDA_VISIBLE_DEVICES=1,3,5,6
on any cuda app you'll see them as 0,1,2,3. Routing will be provided by CUDA driver.

**Comment by yylonly** [comment] 2016-11-25 16:25
Okay, I see

**Comment by raver119** [comment] 2016-11-25 17:54
That doesn't matter, same codebase is used, just different CUDA binaries.

**Comment by raver119** [comment] 2016-11-25 18:24
As speaking of original issue - yep, i confirm it's a bug. useDevice(int) causes undesired behaviour.

I'll take care of this one, thanks for highlighting.

**Comment by raver119** [comment] 2016-11-28 10:30
Issue is fixed/improved. Now it's definitely possible to force specific device/devices being used right from jvm. Will be merged a bit later today.


Thanks for highlighting this issue.

**Comment by yylonly** [comment] 2016-11-28 10:36
Thanks. I will pull and test after the merging..

**Comment by raver119** [comment] 2016-11-28 10:39
Also, i've added method .useDevices(int... devices) that accepts multiple devices, if you want to use, say 2  devices out of 4.

**Comment by raver119** [comment] 2016-11-28 10:53
You could pull from my branches if you want: branch name is r119_fixes everywhere.

Here's the tests i've used: https://github.com/deeplearning4j/nd4j/blob/78c96a8a3f7aab948af84902c144e1b2123c4436/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/test/java/jcuda/jcublas/ops/DevicesTests.java#L18-L18

I've tested it on dual gpu system, works fine.

**Comment by raver119** [comment] 2016-11-28 20:08
Fix is merged.

**Closed by raver119** 2016-11-28 20:08 UTC
Labels: bug
