### ISSUE TITLE
Glove example errors out

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#8904] opened 2020-05-01 23:25 UTC
Originally filed under examples which are not tracked. Seeing on snapshots.

```
o.d.m.s.SequenceVectors - Starting learning process...
Exception in thread "VectorCalculationsThread 0" java.lang.RuntimeException: java.lang.UnsupportedOperationException
        at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1343)
Caused by: java.lang.UnsupportedOperationException
        at org.deeplearning4j.models.embeddings.learning.impl.elements.GloVe.learnSequence(GloVe.java:135)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors.trainSequence(SequenceVectors.java:399)
        at org.deeplearning4j.models.sequencevectors.SequenceVectors$VectorCalculationsThread.run(SequenceVectors.java:1274)
```

**Comment by treo** [comment] 2020-05-06 10:07
Duplicate of https://github.com/eclipse/deeplearning4j/issues/7855

**Closed as completed by treo** 2020-05-06 10:07 UTC
