### ISSUE TITLE
Cannot load existing computation graph.

### ISSUE THREAD

**Issue by ChadiOm** [deeplearning4j/deeplearning4j#6552] opened 2018-10-09 12:40 UTC
Hello everyone.

My code is very simple : 

<
ComputationGraph computationGraph = ModelSerializer.restoreComputationGraph (new File(path2Net));
>

path2Net refers to the path where my .zip is located. The .zip contains a JSON file edited in version 1.0.0-alpha.

In version 1.0.0-alpha, everything worked well. I upgraded my version to 1.0.0-beta2 and I have the following error message : 

"Error deserializing ComputationGraphConfiguration - configuration may have a custom layer, vertex or preprocessor, in pre version 1.0.0-alpha JSON format. These layers can be deserialized by first registering them with NeuralNetConfiguration.registerLegacyCustomClassesForJSON(Class...)"

Please someone can help me ?

Thanx

**Comment by AlexDBlack** [comment] 2018-10-09 23:09
Well, does this network have a custom layer or vertex?
If so, then follow the instructions in the error message.
So, as per the error, call
```
NeuralNetConfiguration.registerLegacyCustomClassesForJSON(MyCustomLayer.class)
```
where ```MyCustomLayer``` is the custom layer.

If there are no custom layers/vertices/preprocessors, then we'll need to debug this. Either you can share your network file, or open it in a zip program and just share the configuration.json file, and I'll take a look.

**Comment by AlexDBlack** [comment] 2018-10-11 09:20
Thanks for the model. I was able to reproduce this, and fix it here: https://github.com/deeplearning4j/deeplearning4j/pull/6560
The cause was a bug in the loading of frozen layers that were serialized in the old/legacy JSON format from a few versions back.

Once the pull request linked above is merged, you can access the fix using snapshots: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

**Closed** 2018-10-11 12:20 UTC
Labels: DL4J
