### ISSUE TITLE
how to use "KerasModelImport" to import model which contains some GRU layers

### ISSUE THREAD

**Issue by fullstackyang** [deeplearning4j/deeplearning4j#7248] opened 2019-03-05 06:04 UTC
#### Issue Description

I use the class "KerasModelImport" to import  a json model file saved by python keras lib, like this:
```
ComputationGraph computationGraph = KerasModelImport.importKerasModelAndWeights(model, weight);
```

but it fails with a Exception as follow:
```
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type GRU. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:318)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:234)
```

#### Version Information

* Deeplearning4j version: 1.0.0-beta3
* platform information: MacOS X 10.13.6
* keras version：1.1.0
* TensorFlow version: 0.12.1

**Comment by maxpumperla** [comment] 2019-03-05 08:03
@fullstackyang thanks, this is on our radar, but needs to be implemented still, see here: https://github.com/deeplearning4j/deeplearning4j/issues/5590

In fact, we have an older PR that adds this, but it needs more love. https://github.com/deeplearning4j/deeplearning4j/pull/5921

Anyway, thanks for reporting. I'm going to close this ticket as duplicate of the one above.

**Closed by maxpumperla** 2019-03-05 08:03 UTC
Labels: DL4J Keras
