### ISSUE TITLE
Core dump written in Ubuntu 14.04 LTS. 

### ISSUE THREAD

**Issue by FatimaAswadi** [deeplearning4j/deeplearning4j#1619] opened 2016-05-30 10:46 UTC
when i run the DBNfullexample of Deeplearning4j library by use IntelliJ IDEA, i have the following problem 
```
 A fatal error has been detected by the Java Runtime Environment:
#
 SIGSEGV (0xb) at pc=0x00007f027c022324, pid=8295, tid=139649893463808

JRE version: OpenJDK Runtime Environment (7.0_101) (build 1.7.0_101-b00)
 Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
 Derivative: IcedTea 2.6.6
Distribution: Ubuntu 14.04 LTS, package 7u101-2.6.6-0ubuntu0.14.04.1
Problematic frame:
C  [libnd4j.so+0x94324]  functions::reduce::ReduceFunction<float>::exec(float*, int*, float*, float*, int*, int*, int)+0xc24

Core dump written. Default location: /home/grid-lab/dl4j-0.4-examples/core or core.8295

An error report file with more information is saved as:
/home/grid-lab/dl4j-0.4-examples/hs_err_pid8295.log

If you would like to submit a bug report, please include
 instructions on how to reproduce the bug and visit:
 http://icedtea.classpath.org/bugzilla
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

Process finished with exit code 134
```
`
the complete log file  for this error in this link https://gist.github.com/FatimaAswadi/89edb444d8ec6a1033473d7baf80946c#file-hs_err_pid8295-log

what should I do to solve it?  
the details for run the program as the following ::
OS : Ubuntu 14.04 LTS 
java version : 
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

how I run the program:
at first i update the libc6 because the glibc version was 2.15 but we need version 2.17 onward so i upgrade my Os from 12.04 LTS to 14.04 LTS
glibc version:
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.9) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

then I run the following commands before I run the program
```
`ulimit -c unlimited

ulimit -u 30654

ulimit -n 4096`
```

then run the idea 

can anyone help me
thanks

**Comment by FatimaAswadi** [comment] 2016-06-01 07:46
for this problem, when I reduce the number of iteration from 10 to 2 only its work without any problem. However 10 iterations are not big I may need to increase it.!
so the problem still need a solution  !!
my pc memory is 8 GB and has 4 processors 
thanks

**Comment by agibsonccc** [comment] 2016-06-01 07:51
Could you give us the crash log or something we can use to actually diagnose this?

**Comment by FatimaAswadi** [comment] 2016-06-01 07:54
I give you the link of complete log file in the above 
and its here again  https://gist.github.com/FatimaAswadi/89edb444d8ec6a1033473d7baf80946c#file-hs_err_pid8295-log
thanks

**Comment by agibsonccc** [comment] 2016-06-01 07:58
Let this run over night with valigrind: https://github.com/deeplearning4j/libnd4j/wiki/Debugging-libnd4j Give us the output from that.

**Comment by FatimaAswadi** [comment] 2016-06-01 08:03
Okay

**Comment by FatimaAswadi** [comment] 2016-06-01 13:31
excuse me Mr. @agibsonccc , how can i run the valigrind from the "IntelliJ IDEA " . I dont understand from the previous link 
I try it for single java program "DBNFullExample.java" but it dosnt work because there is a problem for compile this program alone 
could you please explain it 
thank you

**Comment by agibsonccc** [comment] 2016-06-01 14:38
Follow the guide and run it from command line.

**Comment by eraly** [comment] 2016-06-03 20:16
@FatimaAswadi Hi Fatima, Were you able to resolve your issue? We have a new release coming up in the next few days. Please give it a try and report back if you see issues.

**Comment by fac2003** [comment] 2016-06-04 14:37
I see the same crash in functions::reduce::ReduceFunction<float>::exec with another application code, running with the latest DL4J built from master, on CentOS. I expect that if you release rc3.10 from master it will have the same issue. Here's the stack trace I got, with matching code pointer 0x94324:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007facf76ad324, pid=24368, tid=140382809954048
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.so+0x94324]  functions::reduce::ReduceFunction<float>::exec(float*, int*, float*, float*, int*, int*, int)+0xc24
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/manuele_simi/variationanalysis2/variationanalysis/hs_err_pid24368.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by raver119** [comment] 2016-06-04 14:39
Please attach that file hs_err_pid24368.log

**Comment by fac2003** [comment] 2016-06-04 15:11
See here: https://gist.github.com/fac2003/62f7b99fab89ce8f6a432f849a1cd448#file-hs_err_pid24368-log

**Comment by raver119** [comment] 2016-06-04 15:18
Are you sure that's 100% current libnd4j/nd4j master being built?

**Comment by raver119** [comment] 2016-06-04 15:22
Please, pull again libnd4j,nd4j,dl4j build them all, and try to reproduce your crash once again.
Issue you're referring probably is fixed.

**Comment by fac2003** [comment] 2016-06-04 15:42
We built the whole stack a couple days ago from source (Thursday). Are you saying it has been fixed since? Can you show me the commits?

**Comment by raver119** [comment] 2016-06-04 15:49
https://github.com/deeplearning4j/libnd4j/commits/master

I don't know, if "it has been fixed" or not. I just say, that method signature i see in your crash log is outdated. And to confirm/decline that - i need information, if your issue is still reproducable or not.

**Comment by fac2003** [comment] 2016-06-04 15:49
Here's the relevant part of the install script used to build the image, again we built on Thursday, as far as I know:

```
# libnd4j
cd ~
export GIT_SSL_NO_VERIFY=true
git clone https://github.com/deeplearning4j/libnd4j.git
cd libnd4j
./buildnativeoperations.sh blas cpu
cd ~/libnd4j
export LIBND4J_HOME=`pwd`
echo "export LIBND4J_HOME=$LIBND4J_HOME" >> $HOME/.bashrc

# nd4j
cd ~
git clone https://github.com/deeplearning4j/nd4j.git
cd nd4j
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-cuda-7.5,!org.nd4j:nd4j-tests'

```

**Comment by raver119** [comment] 2016-06-04 15:50
./buildnativeoperations.sh  

That's enough for cpu now.

**Comment by fac2003** [comment] 2016-06-04 15:52
Are you saying including "blas" would cause the bug if the option is listed?

**Comment by raver119** [comment] 2016-06-04 15:54
No. I'm just saying that command line parameters were changed some time ago.

For cpu it's now ./buildnativeoperations.sh

for cuda it's: ./buildnativeoperations.sh -c cuda -b debug (or -b release)

**Comment by fac2003** [comment] 2016-06-04 15:59
To get back to this issue, I think unless you can point us to some change in the code since Thursday (we are in NYC/EST), or believe the options we used could trigger the issue in some way, there is no need for us to build another image with the exact same steps and hope for a different result.

**Comment by raver119** [comment] 2016-06-04 16:05
Unfortunately it seems my english isn't good enough to explain what's going on.
 
Your crash refers to method that was changed. Whole codebase was heavily changed/refactored. 

Will you follow my advices/requests or not - that's totally up to you. But i ***can't*** do anything with your issue without crash log from current master. Too much things were changed since you've built your local copy.

**Comment by fac2003** [comment] 2016-06-04 16:32
I've pulled the latest libnd4j commit: d6d6ad15a3df063e3b9b1393b02a29ecbb0e365b (https://github.com/deeplearning4j/libnd4j/commit/d6d6ad15a3df063e3b9b1393b02a29ecbb0e365b) and set the code to run again. May take some time before it crashes and hours for it to finish successfully. I'll let you know.

**Comment by raver119** [comment] 2016-06-04 16:35
Thanks, waiting for your confirm/decline then.

**Comment by fac2003** [comment] 2016-06-04 23:57
Got the failure after a while, the trace is [here](https://gist.github.com/fac2003/5562cf13dc66f8a87cc92443cacd13cb):
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f836c387324, pid=28729, tid=140203395344128
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.so+0x94324]  functions::reduce::ReduceFunction<float>::exec(float*, int*, float*, float*, int*, int*, int)+0xc24
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/manuele_simi/variationanalysis2/variationanalysis/hs_err_pid28729.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by saudet** [comment] 2016-06-05 12:38
@fac2003 I'm assuming you also have this https://github.com/deeplearning4j/nd4j/commit/a236952aee857ed54e294d585522f791c9c582e6 in your build?

**Comment by fac2003** [comment] 2016-06-05 14:46
No, it did not. I am rerunning with this one.

**Comment by FatimaAswadi** [comment] 2016-06-05 16:33
Hi @eraly , unfortunately til now its not solve, sorry for late reply , when is the new release will be available? maybe in this release the problem will solve 
thank you

**Comment by treo** [comment] 2016-06-05 17:26
@fac2003 your crash also still looks like it isn't using the actual master state, as the function it refers to doesn't exist anymore with that exact signature. either it would have an int in the beginning or it would look like `functions::reduce::ReduceFunction<float>::exec<simdOps::Max<float> >(float*, int*, float*, float*, int*, int*, int, int*, int*)` (depending on the actual operator it crashes with)

**Comment by fac2003** [comment] 2016-06-05 17:40
It is possible the manual build I did does not include "everything" that should be included. You need to realize that from the outside, the "actual master state" is rather poorly documented (and consists for several projects with dependencies), so it is not too surprising if others run into issues trying to build from source. 

I would much prefer you guys publishing snapshots of your development versions (like most other open-source projects do). This would make it easier for others to contribute useful feedback on these versions and for you to integrate the feedback to make the software more robust. 

At this point, I got another crash after 3 epochs of training.  The [trace](https://gist.github.com/fac2003/dd38be2f4b50d49a98acf72cc2f7daee) looks quite different:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  [thread 140320776759040 also had an error]
SIGSEGV (0xb) at pc=0x00007f9eface7353, pid=26247, tid=140320751580928
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.so+0x65353]  _ZN9functions6reduce14ReduceFunctionIfE4execEPfPiS3_S3_S4_S4_i._omp_fn.56+0x233
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" befor
e starting Java again
#
# An error report file with more information is saved as:
# /home/manuele_simi/variationanalysis2/variationanalysis/hs_err_pid26247.log


```

**Comment by treo** [comment] 2016-06-05 18:08
I realize that building from source isn't the easiest thing, and from what I can see around gitter, I guess that when the automation is finally set up correctly, Snapshot builds will probably be coming.

Going by your last trace, you are still not actually _using_ a libnd4j binary based on master, as the method name resolves to `functions::reduce::ReduceFunction<float>::exec(float*, int*, float*, float*, int*, int*, int)`

But now that I have taken a look at your and @FatimaAswadi traces, I can see that both of you are using a Parallel GC. That problem has been discussed in https://github.com/deeplearning4j/libnd4j/issues/223 and fixed by https://github.com/deeplearning4j/nd4j/pull/1004 and https://github.com/deeplearning4j/libnd4j/pull/228

So the fix should be included in the soon to be released next version.

**Closed** 2016-06-05 18:39 UTC
Labels: bug, stalled

**Comment by fac2003** [comment] 2016-06-05 21:04
I was trying to git pull manually and rebuild, but I guess some parts get cached or I just did not know the correct sequence of rebuilds and configurations. We'll trigger a complete rebuild tomorrow and hope this works. Otherwise we will disable the parallel GC and wait for your next release. Thanks for the detailed explanations.
