### ISSUE TITLE
Loading Keras LSTM fails with OutOfMemory, But Should Not (1.0.0-alpha)

### ISSUE THREAD

**Issue by mobiusinversion** [deeplearning4j/deeplearning4j#5062] opened 2018-05-05 17:45 UTC
Hello,

This seems like a pointer error:

[INFO] 2018-05-05 10:39:22,804 [MultiLayerNetwork:55] Starting MultiLayerNetwork with WorkspaceModes set to [training: SEPARATE; inference: SEPARATE]

    java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(68719476736): totalBytes = 226M, physicalBytes = 812M

	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:567)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:61)
	at ...

    Caused by: java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 226M + 256G > maxBytes = 3G
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:572)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	... 46 more

This model should not need 256G of memory, it is simply an LSTM i just trained on my local laptop:

    model = Sequential()
    model.add(Embedding(len(word_index) + 1, embedding_size,
                    weights=[embedding_matrix],
                    input_length=MAX_SEQUENCE_LENGTH,
                    trainable=True))

    model.add(Dropout(0.2))
    model.add(LSTM(256, dropout=0.2, recurrent_dropout=0.2))
    model.add(Dense(Y.shape[1], activation='softmax'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Could this be a result of the embedding?  The word_index length is defined as:

    max_features = 8192
    tokenizer = Tokenizer(num_words=max_features, split=' ')
    tokenizer.fit_on_texts(train_df['comment_text'].values)
    word_index = tokenizer.word_index

**Comment by maxpumperla** [comment] 2018-05-05 19:08
@mobiusinversion this is due to a problem with our orthogonal initializer, I'm closing this as duplicate of #5051. Should work if you (for now) use another recurrent init until this has been fixed.

**Closed by maxpumperla** 2018-05-05 19:08 UTC

**Comment by mobiusinversion** [comment] 2018-05-06 00:53
Thanks @maxpumperla!  Can't wait till I can rev up this new horsepower :)
