### ISSUE TITLE
Fatal error, core dumped, when running GenerateTxtModel example with commit 03e11c727222f21d74aa34cc9a069eca7ab54b1a in CPU mode

### ISSUE THREAD

**Issue by gregbarton** [deeplearning4j/deeplearning4j#9871] opened 2023-01-01 05:26 UTC
#### Issue Description

Please describe our issue, along with:
- Expected behavior: GenerateTxtModel should run without error
- Encountered behavior:
```
mvn -nsu compile exec:java -Dexec.mainClass="org.deeplearning4j.examples.advanced.modelling.charmodelling.generatetext.GenerateTxtModel"
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.deeplearning4j:dl4j-examples >------------------
[INFO] Building Introduction to DL4J 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0.1:enforce (enforce-default) @ dl4j-examples ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dl4j-examples ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ dl4j-examples ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ dl4j-examples ---
Using existing text file at /tmp/Shakespeare.txt
Loaded and converted file: 963172 valid characters of 969521 total characters (6349 removed)
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for linear algebra: 12
o.n.l.c.n.CpuNDArrayFactory - Binary level Generic x86 optimization level AVX/AVX2
o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 12
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [24]; Memory: [15.7GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
o.n.l.c.n.CpuBackend - Backend build information:
 GCC: "11.3.0"
STD version: 201103L
DEFAULT_ENGINE: samediff::ENGINE_CPU
HAVE_FLATBUFFERS
HAVE_OPENBLAS
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]

=====================================================================================
LayerName (LayerType)     nIn,nOut   TotalParams   ParamsShape                       
=====================================================================================
layer0 (LSTM)             77,200     222,400       W:{77,800}, RW:{200,800}, b:{800} 
layer1 (LSTM)             200,200    320,800       W:{200,800}, RW:{200,800}, b:{800}
layer2 (RnnOutputLayer)   200,77     15,477        W:{200,77}, b:{77}                
-------------------------------------------------------------------------------------
            Total Parameters:  558,677
        Trainable Parameters:  558,677
           Frozen Parameters:  0
=====================================================================================

o.d.o.l.ScoreIterationListener - Score at iteration 0 is 217.36468444651516
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd5d7e3e077, pid=3805136, tid=3805204
#
# JRE version: OpenJDK Runtime Environment Zulu18.30+11-CA (18.0.1+10) (build 18.0.1+10)
# Java VM: OpenJDK 64-Bit Server VM Zulu18.30+11-CA (18.0.1+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libnd4jcpu.so+0x130f077]  sd::ShapeDescriptor::ShapeDescriptor(long long const*, bool)+0x47
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/greg_barton/dl4j/deeplearning4j-examples/dl4j-examples/core.3805136)
#
# An error report file with more information is saved as:
# /home/greg_barton/dl4j/deeplearning4j-examples/dl4j-examples/hs_err_pid3805136.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: master branch, commit 03e11c727222f21d74aa34cc9a069eca7ab54b1a
* Platform information (OS, etc): Ubuntu 22.04 and OSX
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

[hs_err_pid3805136.log.gz](https://github.com/deeplearning4j/deeplearning4j/files/10328343/hs_err_pid3805136.log.gz)

**Comment by agibsonccc** [comment] 2023-01-11 00:01
@gregbarton  I just merged a set of changes that should address this. I'm still benchmarking this but this had to do with workspaces + cached shape buffers. I am running the snapshot build and it should be available within a few hours of me writing this. Please feel free to test this afterwards. I'm closing this since this is already reproduced in the test cases I just fixed.

**Closed as completed by agibsonccc** 2023-01-11 00:01 UTC
