### ISSUE TITLE
deeplearning4j 0.4.0 breaks on Windows 10 Insider Preview

### ISSUE THREAD

**Issue by tnolle** [deeplearning4j/deeplearning4j#1819] opened 2016-07-13 09:57 UTC
When I'm trying to run the examples I always get the `jnind4j.dll not in java.library.path` error. I have debugged this to the point where I can say that the ClassLoader is unable to load the dlls because it does not find the dependent libraries.

`java.lang.UnsatisfiedLinkError: C:\Users\tnolle\AppData\Local\Temp\javacpp2198661413766\jnind4j.dll: Can't find dependent libraries`

Funnily it all works fine when using the last RC version of the library. Also everything works fine when using the stable build of Windows 10.

The library cannot be loaded after `if(isAbsolute)` in the ClassLoader:

```Java
static void loadLibrary(Class<?> fromClass, String name, boolean isAbsolute) {
        ClassLoader loader =
            (fromClass == null) ? null : fromClass.getClassLoader();
        if (sys_paths == null) {
            usr_paths = initializePath("java.library.path");
            sys_paths = initializePath("sun.boot.library.path");
        }
        if (isAbsolute) {
            if (loadLibrary0(fromClass, new File(name))) {
                return;
            }
            throw new UnsatisfiedLinkError("Can't load library: " + name);
        }
```

The fact that it worked perfectly before the 0.4.0 let's me hope that this can perhaps be fixed very easily, but I can't seem to find how.

Cheers,
T

**Comment by saudet** [comment] 2016-07-13 11:26
The binaries were inadvertently linked with MKL. I've deployed a version linked with OpenBLAS, but we'll need to specify an extra dependency with a temporarily named classifier for now:
```xml
<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>${nd4j.version}</version>
    <classifier>windows-x86_64-openblas</classifier>
</dependency>
```

**Comment by raver119** [comment] 2016-07-13 11:59
I've sent my snapshot jars to other guy in gitter, and he's experiencing the same issue with CUDA backend. And MKL isn't supposed to be used for nd4j-cuda-7.5. 

Any ideas what might be causing this?

**Comment by tnolle** [comment] 2016-07-13 12:01
Yeah, I tested the suggested line in my pom file, but without success. The error is persisting.

**Comment by treo** [comment] 2016-07-13 12:43
You could try to use dependency walker (http://www.dependencywalker.com/) and start at `C:\Users\tnolle\AppData\Local\Temp\javacpp2198661413766\jnind4j.dll` to see what it is that it can't load.

**Comment by tnolle** [comment] 2016-07-13 12:48
I've done that. Here is the dependency walker image.

[https://www.dropbox.com/s/hxsxfv7rd47n1q7/jnind4j.dwi?dl=0](url)

**Comment by treo** [comment] 2016-07-13 13:21
What you are seeing is still a dependency on MKL_RT.DLL, i.e. intel mkl. So the dependency that @saudet mentioned wasn't used. Can you make sure that you added it correctly, and maybe even exclude the default (with probably something like this, you still will additionally need the openblas version as an extra dependency):
```
<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>${nd4j.version}</version>
    <exclusions>
        <exclusion>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
           <classifier>windows-x86_64</classifier>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by saudet** [comment] 2016-07-13 13:40
@raver119 There's issue #1813 for CUDA but I can't reproduce that one either. I've spend most of the day figuring out a way to get more info out of such errors from Windows, but there just doesn't appear to be one: https://blogs.msdn.microsoft.com/oldnewthing/20131127-00/?p=2553 So it looks like the best we can do is ask people to run Dependency Walker on the DLL and see what that gives.

**Comment by raver119** [comment] 2016-07-13 13:43
That's weird, but i can't reproduce this myself too.

**Comment by tnolle** [comment] 2016-07-13 13:53
Okay, I tried again but this time I get a different error. Apparently he does not find the openblas library now? I'm working with the pom files from the dl4j-examples here. There a property for the backend is being set in the parent pom file. But I don't think that this has something to do with this error, has it?

```Java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:487)
	at org.deeplearning4j.examples.feedforward.classification.MLPClassifierLinear.main(MLPClassifierLinear.java:60)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5023)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:169)
	... 2 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:178)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5020)
	... 3 more
```

I can reproduce this error on two other machines also running Win 10 IP. Only on the Win 10 Stable machine I can't, which is weird, especially because it was working on IP until RC 3.10.

**Comment by treo** [comment] 2016-07-13 13:54
This looks like you have modified your pom.xml to be not quite correct. Can you please share a gist of it, so I can modify it to be exactly as it should be?

**Comment by tnolle** [comment] 2016-07-13 13:58
Here is my setup. As I said, this is mainly the code from the dl4j-examples.

https://gist.github.com/tnolle/71213d6592f8001195193b6976dbb6e5

**Comment by treo** [comment] 2016-07-13 14:09
The problem you are seeing there is that you changed the dependency to be just the one with the classifier, instead of adding it.

But it looks like you can't use a classifier in exclusions, so I'm having some trouble with excluding the default one.

**Comment by tnolle** [comment] 2016-07-13 14:11
When I simply add it, then the classifier seems to be ingnored. Which means it's still loading MKL instead of openblas.

**Comment by treo** [comment] 2016-07-13 14:18
try it like this: https://gist.github.com/treo/a1b62e3a199f78fda1265654a01b4b22

it may be that Intellij will still try to load the mkl based dependency, but you should be able to run `mvn package` and then start one of the examples from command line.

**Comment by tnolle** [comment] 2016-07-13 14:23
Yep, that seems to be working fine (even in IntelliJ). Thank you very much.

**Comment by treo** [comment] 2016-07-13 14:26
Ok, so the solution for the moment is to have the dependency for nd4j-native to be like this:
``` xml
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>${nd4j.version}</version>
            <classifier>windows-x86_64-openblas</classifier>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>${nd4j.version}</version>
            <classifier>windows-x86_64</classifier>
            <scope>provided</scope>
        </dependency>
```

**Comment by JimLShelley** [comment] 2016-07-13 15:12
This works for me on Windows 7 with Netbeans also. And also many thanks.

**Comment by treo** [comment] 2016-07-28 10:05
For anyone who has problem with applying the fix themselves, I have a fork with the examples that contains it: https://github.com/treo/dl4j-0.4-examples

I'll delete the fork as soon as the next release is out and that workaround isn't needed anymore.

**Comment by treo** [comment] 2016-08-03 13:26
@JimLShelley Version 0.5.0 was just released, can you please remove the workaround and update to it, to confirm that this issue is now fixed?

**Comment by JimLShelley** [comment] 2016-08-03 15:05
Confirmed working now.

**Comment by raver119** [comment] 2016-08-03 15:10
@JimLShelley thanks!

**Closed by raver119** 2016-08-03 15:10 UTC
Labels: bug

**Comment by shenkev** [comment] 2016-11-29 20:19
I'm following the solution here, not sure why there's an error in one of the dependencies, what am I missing?

![image](https://cloud.githubusercontent.com/assets/5405172/20727276/b0acf180-b62d-11e6-85ff-c63df45ca4cf.png)

**Comment by raver119** [comment] 2016-11-29 20:22
As you can see - this issue was closed almost 4 months ago, it's not relevant. That's what you're missing.

Classifier you're using isn't available anymore. 

Just check pom.xml in examples, you'll see nd4j-native-platform artifact being used to address issue posted here.
