### ISSUE TITLE
Keras import

### ISSUE THREAD

**Issue by nt202** [deeplearning4j/deeplearning4j#4088] opened 2017-09-18 14:46 UTC
### Hello everyone. I'm trying to import keras model to dl4j, I changed dependency to 0.9.2-snapshot (to resolve Conv2D problem), but output is:

17:31:57.717 [main] WARN org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils - Unable to match layer parameter name bias:0 for stored weights.
17:31:57.887 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
17:31:57.973 [main] WARN org.reflections.Reflections - given scan urls are empty. set urls in the configuration
Exception in thread "main" java.lang.ExceptionInInitializerError
at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:219)
at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:77)
at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:226)
at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:129)
at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:120)
at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:237)
at ru.nt202.dl4j.Keras.main(Keras.java:28)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6365)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6229)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:205)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6286)
	... 10 more

my code is just
`        MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights
                (
                        "./src/main/resources/model.json",
                        "./src/main/resources/first_try.h5"
                );
`

I attached my h5 and json files
[resources.zip](https://github.com/deeplearning4j/deeplearning4j/files/1311044/resources.zip)

**Comment by maxpumperla** [comment] 2017-09-18 15:24
@nt202 you might want to give me your full stack trace as gist, but I'm pretty sure this just indicates that ND4J isn't initialised properly. It likely complains the first time it tries to init a weight from an imported layer. 

```
Caused by: java.lang.NullPointerException
at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6286)
```

I'm going to close this. Let me know if I'm wrong and feel free to reopen

**Closed by maxpumperla** 2017-09-18 15:24 UTC

**Comment by nt202** [comment] 2017-09-18 15:55
Sorry, you are right. Now I have another problem, here is my code

    public static void main(String[] args) throws IOException, InvalidKerasConfigurationException, UnsupportedKerasConfigurationException {
        MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights
                (
                        "./src/main/resources/model.json",
                        "./src/main/resources/first_try.h5"
                );

        File testData = new File("./src/main/resources/testing");

        String[] allowedExtensions = BaseImageLoader.ALLOWED_FORMATS;
        Random rng = new Random(123);
        FileSplit test = new FileSplit(testData, allowedExtensions, rng);

        ParentPathLabelGenerator labelMaker = new ParentPathLabelGenerator();

        ImageRecordReader readerTest = new ImageRecordReader(150, 150, 3, labelMaker);
        readerTest.initialize(test);
        DataSetIterator iteratorTest = new RecordReaderDataSetIterator(readerTest, 20, 1, 2);


        log.info("Evaluating model....");
        Evaluation eval = new Evaluation(2);

        while (iteratorTest.hasNext()) {
            DataSet ds = iteratorTest.next();
            INDArray features = ds.getFeatureMatrix();
            INDArray labels = ds.getLabels();
            INDArray predicted = model.output(features, false);
            eval.eval(labels, predicted);
        }
        log.info(eval.stats());
    }

output:

18:44:59.960 [main] INFO ru.nt202.dl4j.Keras - Evaluating model....
Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.convolution.Convolution.im2col(Lorg/nd4j/linalg/api/ndarray/INDArray;IIIIIIIIZLorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/nd4j/linalg/api/ndarray/INDArray;
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:359)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:257)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:414)
	at org.deeplearning4j.nn.layers.AbstractLayer.activate(AbstractLayer.java:309)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.activationFromPrevLayer(MultiLayerNetwork.java:789)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForwardToLayer(MultiLayerNetwork.java:929)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:870)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.feedForward(MultiLayerNetwork.java:861)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.silentOutput(MultiLayerNetwork.java:1906)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.output(MultiLayerNetwork.java:1898)
	at ru.nt202.dl4j.Keras.main(Keras.java:53)

Process finished with exit code 1

**Comment by agibsonccc** [comment] 2017-09-18 16:00
Now you look like you're using the wrong versions of nd4j. I'm not sure how
or why you setup your versions the way you did, but your versions of dl4j
and nd4j and datavec and any other dl4j dependency should all be 0.9.1

**Comment by nt202** [comment] 2017-09-18 16:38
But version 0.9.1 does'not contain Conv2D support
I used 
        <nd4j.version>0.9.1</nd4j.version>
        <dl4j.version>0.9.2-SNAPSHOT</dl4j.version>

I try to run simple HelloWorld for nd4j if I use version 0.9.2-SNAPSHOT for it. 

19:36:43.497 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
19:36:43.619 [main] WARN org.reflections.Reflections - given scan urls are empty. set urls in the configuration
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6336)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6229)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:205)
	at ru.nt202.nd4j.HelloWorld.main(HelloWorld.java:10)
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
	at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
	... 10 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:739)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:64)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:765)
	... 21 more

**Comment by agibsonccc** [comment] 2017-09-18 16:40
This means that nd4j isn't setup properly. I don't think this is the full trace. There's no root cause here.
Are you trying to build from source or just using snapshots?

**Comment by nt202** [comment] 2017-09-18 16:41
Just using snapshot

**Comment by nt202** [comment] 2017-09-18 16:42
It works properly for version 0.9.1

**Comment by agibsonccc** [comment] 2017-09-18 16:44
@saudet any ideas here?

**Comment by nt202** [comment] 2017-09-18 16:52
[ERROR] Failed to execute goal on project Diploma: Could not resolve dependencies for project ru.nt202:Diploma:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.nd4j:nd4j-native:jar:linux-x86_64:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:android-arm:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:android-x86:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:macosx-x86_64:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:linux-ppc64le:0.9.2-SNAPSHOT: Could not find artifact org.nd4j:nd4j-native:jar:linux-x86_64:0.9.2-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by raver119** [comment] 2017-09-18 19:18
If you're using snapshots, or building from sources, you shouldn't use `nd4j-native-platform` as backend. use `nd4j-native`

**Comment by saudet** [comment] 2017-09-19 04:03
The CI server isn't functioning too well these days, there might be missing artifacts on the snapshot repository.

**Comment by maxpumperla** [comment] 2017-09-19 08:01
@nt202 Conv2D is a keras 2 layer that only recently got integrated, def. not in 0.9.1., but 100% in latest snapshot. If, as @raver119 suggested, you build locally with `nd4j-native`, this should all work fine w/ `0.9.2-SNAPSHOT` (both nd4j and dl4j).

**Comment by rainjacket** [comment] 2017-09-23 01:46
maxpumperla any idea when 0.9.2 is coming out?

**Comment by maxpumperla** [comment] 2017-09-23 07:18
@rainjacket I can't make any promises here. We work towards a version 1.0 right now, might squeeze in another release before that.
