### ISSUE TITLE
hive and dl4j can not be work on spark 2 in the same time ?

### ISSUE THREAD

**Issue by hksong0209** [deeplearning4j/deeplearning4j#3363] opened 2017-05-05 11:46 UTC
#### Issue Description
i use dl4j (version 0.8) on spark 2.1. i find kryo should be registered as
```
SparkConf sparkConf = new SparkConf();
sparkConf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
		.set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator");
```
kryo registered as follows is invalid and 4j not work:
```
SparkSession spark = SparkSession.builder().enableHiveSupport().getOrCreate();
spark.conf().set("spark.serializer", "org.apache.spark.serializer.KryoSerializer");
spark.conf().set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator");
```
Therefore, with kryo of 4j, i can not use SparkSession, further, i can not use hive sql based on SparkSession in spark 2.

So, what can i do next to use hive and 4j on spark 2 in the same time ?
i will appreciate it if  anyone could offer help :)

**Comment by AlexDBlack** [comment] 2017-05-05 12:26
I don't understand what the problem is here.

>kryo registered as follows is invalid and 4j not work:

What does this mean? Are you getting an error/exception? If so - you'll need to post it before we can help you.

But first: https://deeplearning4j.org/spark#kryo

>To use Kryo, add the appropriate nd4j-kryo dependency and configure the Spark configuration to use the Nd4j Kryo Registrator, as follows:

Did you add the nd4j-kryo dependency?

**Comment by hksong0209** [comment] 2017-05-06 03:48
my origin main code on spark 2.1, nd4j-kryo dependency was added (i have run successfully the official SparkLSTMCharacterExample previously )：
```
		SparkSession spark = SparkSession
				  .builder()
				  .appName("Java Spark test APP")
				  .config("spark.some.config.option", "some-value")
				  .enableHiveSupport()
				  .getOrCreate();
		//
		SparkConf sparkConf = new SparkConf();
		sparkConf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
		.set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator");
		
		JavaSparkContext jsc = new JavaSparkContext(spark.sparkContext());
		spark.sql("SET spark.sql.hive.convertMetastoreParquet=false");
		//
		String sqlc ="select * from tempDB.test"; 
		Dataset<Row> userinfo = spark.sql(sqlc);
		//
		System.out.println("transform spark Dataset to JavaRDD<DataSet> for 4j");
		JavaRDD<DataSet> data4j = userinfo.
				.toJavaRDD().map(new DatasetRow2JavaRDDDataSet());
		System.out.println("training 4j LSTM net");
		int nIn = feaNum;
		int nOut = 1;
		SparkDl4jMultiLayer sparknet = getNetModel(nIn, nOut,jsc);
		int numEpochs = 2;
		MultiLayerNetwork net = null;
		for (int i = 0; i < numEpochs; i++) {
			net = sparknet.fit(data4j);  
			System.out.println("=================>"+i+": training finished");  
		}
```
after running the code above, i got the error:
```
ERROR yarn.ApplicationMaster: User class threw exception: java.lang.RuntimeException: Kryo serialization detected without an appropriate registrator for ND4J INDArrays.
When using Kryo, An appropriate Kryo registrator must be used to avoid serialization issues (NullPointerException) with off-heap data in INDArrays.

Caused by: java.lang.NullPointerException
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.interceptIntDataType(DefaultOpExecutioner.java:92)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.checkForCompression(DefaultOpExecutioner.java:64)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:84)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.equalsWithEps(BaseNDArray.java:4103)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.equals(BaseNDArray.java:4145)
	at org.deeplearning4j.spark.util.SparkUtils.checkKryoConfiguration(SparkUtils.java:93)
```
but i have set "sparkConf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer").set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator");" in my code. it is confusing.

just now, i find i can set kryo.registrator through SparkSession.config() intead of sparkConf.set():
```
SparkSession spark = SparkSession
				  .builder()
				  .appName("Java Spark test APP")
				  .config("spark.some.config.option", "some-value")
				  // kryo registrator in SparkSession.config()
				  .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
				  .config("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator")
				  .enableHiveSupport()
				  .getOrCreate();
//SparkConf sparkConf = new SparkConf();
//sparkConf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
//	.set("spark.kryo.registrator", "org.nd4j.Nd4jRegistrator");
```
then i can successfully run my code :).
i am a rookie in spark and dl4j, sorry to bother you, hahahaha...

**Comment by AlexDBlack** [comment] 2017-05-06 04:38
Ok, so it's working for you? Great, no problem.

I'll close this issue as resolved then. :)

**Closed by AlexDBlack** 2017-05-06 04:38 UTC
