### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by hanbaoan123** [deeplearning4j/deeplearning4j#7286] opened 2019-03-12 08:30 UTC
#### Issue Description
When I use RL4J to train a model, the following error occurs.

Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:178)
	at org.nd4j.linalg.api.buffer.LongBuffer.<init>(LongBuffer.java:105)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.create(DefaultDataBufferFactory.java:72)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1122)
	at org.nd4j.linalg.api.shape.Shape.shapeOf(Shape.java:2834)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.shapeOf(BaseNDArray.java:3070)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.subArray(BaseNDArray.java:2579)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:5035)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:2440)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putRow(BaseNDArray.java:4395)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteSchedule.setTarget(QLearningDiscreteSchedule.java:258)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteSchedule.trainStep(QLearningDiscreteSchedule.java:216)
	at org.deeplearning4j.rl4j.learning.sync.qlearning.QLearning.trainEpoch(QLearning.java:108)
	at org.deeplearning4j.rl4j.learning.sync.SyncLearning.train(SyncLearning.java:53)
	at com.mes.schedule.rl.deepQL.DeepQLManager.schedule(DeepQLManager.java:144)
	at com.mes.schedule.service.ScheduleDataAccess.doDeepQLSchedule(ScheduleDataAccess.java:1490)
	at com.mes.schedule.service.ScheduleDataAccess$$FastClassByCGLIB$$aae69355.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:642)
	at com.mes.schedule.service.ScheduleDataAccess$$EnhancerByCGLIB$$e83887e.doDeepQLSchedule(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.bstek.dorado.data.method.MethodAutoMatchingUtils.invokeMethod(MethodAutoMatchingUtils.java:602)
	at com.bstek.dorado.data.method.MethodAutoMatchingUtils.invokeMethod(MethodAutoMatchingUtils.java:695)
	at com.bstek.dorado.view.service.AbstractRemoteServiceProcessor.invokeByParameterType(AbstractRemoteServiceProcessor.java:310)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0-SNAPSHOT
* RL4J-1.0.0-SNAPSHOT
* Windows 7

Aha! Link: https://skymindai.aha.io/features/ND4J-102

**Comment by saudet** [comment] 2019-03-12 08:42
Try to give more memory to your Java process.

**Comment by saudet** [comment] 2019-03-12 08:43
Or is this a duplicate of #7125?

**Closed** 2019-03-18 07:33 UTC
