### ISSUE TITLE
iterations is set to 0 after updater restoration and score is NaN

### ISSUE THREAD

**Issue by frakc** [deeplearning4j/deeplearning4j#4441] opened 2017-12-20 11:42 UTC
#### Issue Description
expected: model continues to train from saved point
actual: model does not train at all

At first i run `feedforward()` method to initialise, train and save network. Then I run `update()` in a loop.
I save network with
        ```ModelSerializer.writeModel(net, File(pathToNN), true)```
then restore it with
        ```val net = ModelSerializer.restoreMultiLayerNetwork(pathToNN,true)```
and provide iterator which is initialised in exactly same way.

log
Epoch 400, number of batches completed 57
Score at iteration 22700 is 0.05135663793453861
feedforward() fineshed
update() started
Score at iteration 0 is 0.05206126573727092
Epoch 1, number of batches completed 57
Score at iteration 100 is NaN

code
https://gist.github.com/frakc/5ed8a6ca42392dcbf224de2ea18bf976

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.9.1
* Ubuntu 17.04

**Comment by AlexDBlack** [comment] 2017-12-21 01:11
I'm going to close this.

First: the 'score at iteration 0' issue was merely a reporting issue, fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/4444

Second: I'm unable to reproduce the NaN issue without the actual data used.
@frakc I would suggest posting UI screenshots here: https://gitter.im/deeplearning4j/deeplearning4j/tuninghelp
https://deeplearning4j.org/visualization

Specifically, I need screenshots of the overview page, and the full model page for say the final layer (OutputLayer). For both before and after the model saving/loading.

**Closed by AlexDBlack** 2017-12-21 01:11 UTC
