### ISSUE TITLE
Keras import : java.lang.ClassCastException between org.deeplearning4j.nn.conf.layers.recurrent.LastTimeStep and org.deeplearning4j.nn.conf.layers.FeedForwardLayer

### ISSUE THREAD

**Issue by h2o64** [deeplearning4j/deeplearning4j#8924] opened 2020-05-06 08:48 UTC
#### Issue Description
 I am importing a Keras model that you can find on [this colab ](https://colab.research.google.com/drive/1tV5cFexR1iJJPI3ylFnWFtF2lMiMLiOa) using the following code :
```
// Import model
ComputationGraph model = KerasModelImport.importKerasModelAndWeights("/path/to/model.h5", true);
System.out.println(model.summary());
```
and it returns me
```
Exception in thread "main" java.lang.ClassCastException: class org.deeplearning4j.nn.conf.layers.recurrent.LastTimeStep cannot be cast to class org.deeplearning4j.nn.conf.layers.FeedForwardLayer (org.deeplearning4j.nn.conf.layers.recurrent.LastTimeStep and org.deeplearning4j.nn.conf.layers.FeedForwardLayer are in unnamed module of loader 'app')
	at org.deeplearning4j.nn.modelimport.keras.layers.recurrent.KerasLSTM.setWeights(KerasLSTM.java:449)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:302)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:183)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:155)
	at org.lara.rnn.Main.main(Main.java:10)
```
#### Version Information

* Deeplearning4j version : 1.0.0-beta6
* Platform information : Ubuntu 19.04 (64 Bits)
* CUDA version : not used
* NVIDIA driver version : not used

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace : https://gist.github.com/h2o64/7a1b9e6ac31869451512d01795326823
* pom.xml : https://gist.github.com/h2o64/14762fb7a1b91c2c885f339980db5b2e

**Comment by h2o64** [comment] 2020-05-06 09:31
This has been tested in the 1.0.0-SNAPSHOT of today and still outputs the same

**Comment by treo** [comment] 2020-05-06 10:12
It is using tf.keras functionality, so it isn't unexpected that it doesn't work with beta6, but I would have expected it to work with SNAPSHOTS.

Do you get the **exactly same** stacktrace with snapshots?

**Comment by h2o64** [comment] 2020-05-06 10:39
Hi, thank you for such a fast answer. Here is the stacktrace with 1.0.0-SNAPSHOT
```
Exception in thread "main" java.lang.ClassCastException: class org.deeplearning4j.nn.conf.layers.recurrent.LastTimeStep cannot be cast to class org.deeplearning4j.nn.conf.layers.FeedForwardLayer (org.deeplearning4j.nn.conf.layers.recurrent.LastTimeStep and org.deeplearning4j.nn.conf.layers.FeedForwardLayer are in unnamed module of loader 'app')
	at org.deeplearning4j.nn.modelimport.keras.layers.recurrent.KerasLSTM.setWeights(KerasLSTM.java:449)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:302)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:183)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:155)
	at org.lara.rnn.Main.main(Main.java:10
```
which is very very similar. Here is the [pom.xml ](https://gist.github.com/h2o64/769ec9cb0fa6ca86bfdd6ae31516f902 )that I use.

UPDATE: I compared _release/1.0.0-beta6_ branch against _master_ branch and those lines are indeed the same.

**Comment by h2o64** [comment] 2020-05-06 15:26
@treo 
After a lot of research, I think I understand the problem.
Here are my two LSTM layers
```
MaskZeroLayer(BaseWrapperLayer(underlying=LSTM(super=AbstractLSTM(super=BaseRecurrentLayer(super=FeedForwardLayer(super=BaseLayer(activationFn=tanh, weightInitFn=org.deeplearning4j.nn.weights.WeightInitXavierUniform@1, biasInit=0.0, gainInit=NaN, regularization=[], regularizationBias=[], iUpdater=null, biasUpdater=null, weightNoise=null, gradientNormalization=null, gradientNormalizationThreshold=NaN), nIn=0, nOut=200, timeDistributedFormat=null), weightInitFnRecurrent=org.deeplearning4j.nn.weights.WeightInitDistribution@3ff00076, rnnDataFormat=NWC), forgetGateBiasInit=1.0, gateActivationFn=sigmoid, helperAllowFallback=true), forgetGateBiasInit=1.0, gateActivationFn=sigmoid)))
MaskZeroLayer(LSTM(super=AbstractLSTM(super=BaseRecurrentLayer(super=FeedForwardLayer(super=BaseLayer(activationFn=tanh, weightInitFn=org.deeplearning4j.nn.weights.WeightInitXavierUniform@1, biasInit=0.0, gainInit=NaN, regularization=[], regularizationBias=[], iUpdater=null, biasUpdater=null, weightNoise=null, gradientNormalization=null, gradientNormalizationThreshold=NaN), nIn=0, nOut=200, timeDistributedFormat=null), weightInitFnRecurrent=org.deeplearning4j.nn.weights.WeightInitDistribution@3ff00076, rnnDataFormat=NWC), forgetGateBiasInit=1.0, gateActivationFn=sigmoid, helperAllowFallback=true), forgetGateBiasInit=1.0, gateActivationFn=sigmoid))
```
I printed them right after their creation in https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasModel.java#L218 like that
```
if (layer instanceof KerasLSTM)
    System.out.println(layer);
```
Both of them are instances of _BaseWrapperLayer_ but it's a double _BaseWrapperLayer_ because of the _MaskZeroLayer_ I think. Indeed when I do
```
if (layer instanceof KerasLSTM)
   if (((KerasLSTM) layer).getLSTMLayer() instanceof BaseWrapperLayer) {
      BaseWrapperLayer bwl = (BaseWrapperLayer) (((KerasLSTM) layer).getLSTMLayer());
      if (bwl.getUnderlying() instanceof BaseWrapperLayer)
         System.out.println("OK");
   }
```
It returns me
```
OK
```
The fix would be to unpack all the underlying layers during _setWeights_

**Comment by h2o64** [comment] 2020-05-07 14:00
So I fixed this bug as follows,
```
diff --git a/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/recurrent/KerasLSTM.java b/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/recurrent/KerasLSTM.java
index d2b9f42ff9..739d8dde4f 100644
--- a/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/recurrent/KerasLSTM.java
+++ b/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/recurrent/KerasLSTM.java
@@ -446,6 +446,8 @@ public class KerasLSTM extends KerasLayer {
         FeedForwardLayer ffl;
         if(this.layer instanceof BaseWrapperLayer){
             BaseWrapperLayer bwl = (BaseWrapperLayer)this.layer;
+            while(bwl.getUnderlying() instanceof BaseWrapperLayer)
+                bwl = (BaseWrapperLayer) bwl.getUnderlying();
             ffl = (FeedForwardLayer)bwl.getUnderlying();
         } else {
             ffl = (FeedForwardLayer) this.layer;
```
and now I get this :
```
Exception in thread "main" org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: MergeVertex cannot merge activations of different types: first type = RNN, input type 2 = FF
	at org.deeplearning4j.nn.conf.graph.MergeVertex.getOutputType(MergeVertex.java:139)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.getLayerActivationTypes(ComputationGraphConfiguration.java:537)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.addPreProcessors(ComputationGraphConfiguration.java:450)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1202)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraphConfiguration(KerasModel.java:394)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:415)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:404)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:156)
```
It sounds very similar to https://github.com/eclipse/deeplearning4j/issues/4743, maybe @maxpumperla could help ?
~~It sounds like it's a problem with _MaskZero_ again... Waiting for confirmation~~ After removing the `mask_zero=True` parameters in my LSTM layers, I get the exact same error.
Thank you
PS: Here is the model without `mask_zero` [model.zip](https://github.com/eclipse/deeplearning4j/files/4593785/model.zip)

**Comment by treo** [comment] 2020-05-07 15:53
Thanks a lot for digging this deep.  Are you still using a beta6 based version? Or since you've actually did some changes to the code, have you moved to compiling from source and using master?

@AlexDBlack what do you think here?

**Comment by h2o64** [comment] 2020-05-07 17:46
> Thanks a lot for digging this deep. Are you still using a beta6 based version? Or since you've actually did some changes to the code, have you moved to compiling from source and using master?
> 
> @AlexDBlack what do you think here?

I am using master as you advised. I'm compiling the library myself in order to debug. (I just tested my model without `mask_zero` on the latest snapshot and I get the same `InvalidInputTypeException` with the same stacktrace.)

**Comment by agibsonccc** [comment] 2021-01-27 05:10
Confirmed this doesn't happen anymore. Closing.

**Closed as completed by agibsonccc** 2021-01-27 05:10 UTC
Labels: Bug, DL4J Keras
