### ISSUE TITLE
Error with SparkDl4jMultiLayer's fit method on Mac OSX Yosemite

### ISSUE THREAD

**Issue by dmmiller612** [deeplearning4j/deeplearning4j#2347] opened 2016-11-21 03:11 UTC
This is tricky to pinpoint the exact issue because it does not come with a stacktrace. The actual error I am receiving is this: 

`16/11/20 21:56:42 INFO Executor: Running task 1.0 in stage 16.0 (TID 80)
16/11/20 21:56:42 INFO Executor: Running task 0.0 in stage 16.0 (TID 79)
16/11/20 21:56:42 INFO ShuffleBlockFetcherIterator: Getting 2 non-empty blocks out of 2 blocks
16/11/20 21:56:42 INFO ShuffleBlockFetcherIterator: Getting 2 non-empty blocks out of 2 blocks
16/11/20 21:56:42 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 1 ms
16/11/20 21:56:42 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 1 ms
java(32550,0x12ff08000) malloc: *** error for object 0x7fc6f2a0db88: incorrect checksum for freed object - object was probably modified after being freed.`

I have tried the obvious such as starting/restarting my computer, tried different parameters, and other related things but have had no success. With that in mind, the below information is all that I could find.

1. My code at the moment looks like (although I am messing around to try and get this to work):
`TrainingMaster tm = new ParameterAveragingTrainingMaster.Builder(32)
                .averagingFrequency(10)
                .saveUpdater(true)
                .workerPrefetchNumBatches(2)
                .batchSizePerWorker(32)
                .repartionData(Repartition.Always)
                .repartitionStrategy(RepartitionStrategy.SparkDefault)
                .build();
         SparkDl4jMultiLayer sparkNetwork = new SparkDl4jMultiLayer(SparkConfig.getSparkContext(), conf, tm);`

2. When running sparkNetwork.fit(JavaRDD<DataSet> data), I get the error in different places, but it seems to be centralized in one method. The method is in executeTrainingPathsHelper in the ParameterAveragingTrainingMaster class. It most frequently gets hit when calling the SparkUtils.balancedRandomSplit method.

3. I am using Spark 1.6.1 with Deeplearning Spark's dependency:
`        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>dl4j-spark_2.11</artifactId>
            <version>0.6.0</version>
        </dependency>`

4. The normal MultiLayerNetwork works fine with the same config (minus sparknet and trainingmaster).

5. My spark-submit arguments are:
`spark-submit --class com.deep.FiveDayJob --master local[2] --driver-memory 6g --executor-memory 4g target/testing-jar-with-dependencies.jar`
I have tried using more threads (and 1), but haven't got past the issue.

I am still digging deeper, and I wouldn't even be surprised if the problem is even my machine. I just thought it was a bit odd that this was happening, so I decided to file a ticket.

**Comment by raver119** [comment] 2016-11-21 07:50
This issue is supposed to be fixed on current master.
You'll have to either wait for next release, or build things from sources.

**Closed by raver119** 2016-11-21 07:50 UTC

**Comment by dmmiller612** [comment] 2016-11-21 14:08
Do you happen to know if this only affects mac? Is it also a problem in an earlier version?

**Comment by raver119** [comment] 2016-11-21 14:12
Both answers are hard/impossible to answer for me.

We only know that release 0.6.0 had few bugs:
1) OpenBLAS gemm bug, reproducible on Power8 machines mostly.
2) This bug, you're referring to.

Both bugs are considered fixed now, and since this bug wasn't reproducible on my mac, i can't tell if earlier versions were affected. So i'd just suggest you to wait for new release, which is going to happen right now.

**Comment by dmmiller612** [comment] 2016-11-21 14:14
👍 Thanks!
