### ISSUE TITLE
Make convolution layer work with 1D arrays

### ISSUE THREAD

**Issue by dwr-psandhu** [deeplearning4j/deeplearning4j#2821] opened 2017-02-04 03:25 UTC
Use case:

Use a convolution layer in which the input is time series(s) each of which are 1-D ( these are essentially filters with defined kernel size and strides along the time dimension). The CNN example and code is setup for 2-D images and does not map easily to this use case

This issue arose out of the gitter channel chat . My attempt to do this is here https://gist.github.com/dwr-psandhu/d1d05323c23c0e805c6de60d897ec6fe and a sample file of time series with first column of input and second column of target is here https://gist.github.com/dwr-psandhu/912082af7523d6950e72039a1c656536

**Comment by turambar** [comment] 2017-02-22 08:01
Not sure I follow the issue: are you saying that the example you provided above *doesn't work* (haven't tested your code, sorry!) or are you simply saying that it's non-obvious from the API how to do it?

**Comment by dwr-psandhu** [comment] 2017-02-22 17:13
I would say an example would be a start. I have a regression of one or more time series onto another time series and I have not been able to adapt the image example. 
The convolution on the input time series would be over time ( very similar to time domain filtering).

**Comment by agibsonccc** [comment] 2017-02-28 03:57
We *should* be having a pooling over time example next release? @turambar

**Comment by turambar** [comment] 2017-02-28 08:19
@agibsonccc yes, though that does not appear to impact this example. @dwr-psandhu can you confirm that this example does not work (I apologize that I haven't been able to test it myself -- I'm currently traveling), and if not, can you post the error you're getting? I don't see any obvious flaws in your code.

**Comment by turambar** [comment] 2017-02-28 23:51
@dwr-psandhu Here's a modified version of the MultiTimestepRegression example that uses a 1D temporal convolutional layer instead of an RNN: https://gist.github.com/turambar/b0e1f7eba07e2f0964e2849912093946

You'll see that the trick is to re-define your 2D sequence as a 3D image (see [here](https://gist.github.com/turambar/b0e1f7eba07e2f0964e2849912093946#file-temporalconvolutionregressionexample-java-L122)), which requires you to reshape the features and targets returned by the SequenceDataSetIterator (see [here](https://gist.github.com/turambar/b0e1f7eba07e2f0964e2849912093946#file-temporalconvolutionregressionexample-java-L171)).

I'm inviting @AlexDBlack @eraly to give this a quick glance to make sure it's not obviously wrong. Assuming they say it's (at least, technically) correct, I will close this.

**Comment by turambar** [comment] 2017-03-01 00:03
@AlexDBlack @eraly @agibsonccc @raver119 @EdeMeijer I think this is correct, but it's definitely not elegant. The problem is that conceptually, our recurrent layers expect rank 3 inputs, outputs, and (optional) masks (minibatch, features, length), and likewise, our specialized "sequence" data classes (record readers and data set iterators) return those things. However, convolutional layers expect rank 4 inputs (minibatch, channels, height, width) and non-sequence outputs.

To make this more intuitive, I think we should probably add a dedicated 1D ConvolutionalLayer (even if it just wraps the current ConvolutionalLayer) that takes an RNN-style rank 3 input (and maybe has its own preprocessor under the hood).

Of course, that would be lot of wasted computation vs. a dedicated 1D convolutional layer, so we might want to add the latter at some point. Also, do we need to do something regarding masks (for variable length sequences in the same minibatch)?

Finally, another reason to consider a dedicated layer: the above formulation of a temporal convolutional layer learns a filter for each feature map -- either a multivariate filter that combines all the variables or a univariate filter that is shared across variables but applied to each independently. There is another variant in which we learn an independent univariate filter for each variable.

**Comment by dwr-psandhu** [comment] 2017-03-01 22:56
@turambar I ran your example. I had to lower the learning rate to avoid getting NaNs on the time series evaluation R^2. 
I also got this error which is past the training but perhaps is left over code from the example copied from ? Are you not getting this error?

> Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Got rank 3 array as input to ConvolutionLayer (layer name = (not named), layer index = 0) with shape [10, 1, 20]. Expected rank 4 array with shape [minibatchSize, layerInputDepth, inputHeight, inputWidth].
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:229)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:305)
	at org.deeplearning4j.nn.layers.BaseLayer.activate(BaseLayer.java:405)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:2208)
	at org.deeplearning4j.examples.recurrent.regression.TemporalConvolutionRegressionExample.main(TemporalConvolutionRegressionExample.java:218)

**Comment by turambar** [comment] 2017-03-01 23:16
I chose an arbitrary architecture -- there's no guarantee it will work well, and yes, that's vestigial code that should be changed as per earlier in the file.

I'll leave those changes as an exercise for you. ;) If you need help tuning the model, please visit the `tuning` channel. Closing.

**Closed by turambar** 2017-03-01 23:16 UTC
Labels: help wanted, keras

**Comment by turambar** [comment] 2017-03-06 07:05
@dwr-psandhu True 1D convolutional and pooling layers are implemented and undergoing testing. If you're interested, here's the PR: https://github.com/deeplearning4j/deeplearning4j/pull/2976.

**Comment by turambar** [comment] 2017-07-24 23:52
Duplicate: https://github.com/deeplearning4j/deeplearning4j/issues/3101
