### ISSUE TITLE
Exception Zoo model GoogLenet FC1 layer when trying to train with own samples 

### ISSUE THREAD

**Issue by SangeethaManiam** [deeplearning4j/deeplearning4j#4427] opened 2017-12-18 11:24 UTC
Description:
Tried to import GoogLenet zoo model  as a fresh model and tried to train with my own samples.The following exception occurred "Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Input that is not a matrix; expected matrix (rank 2), got rank 4 array with shape [2, 1024, 7, 7]. Missing preprocessor or wrong input type? (layer name: fc1, layer index: 83)

Dl4j version : 0.9.1 . 
Windows 10
CUDA is not used
NVIDIA not used
Note : This issue is raised in Gitter on Jun 15. So it may be in previous version.  

My code is in : https://gist.github.com/SangeethaManiam/fc6613166aa903c9780aa63a8e3ba6c1
Full stack trace : https://gist.github.com/SangeethaManiam/eeb815b49dd53f1ad91e382c5c87374c

**Comment by crockpotveggies** [comment] 2017-12-18 16:46
Thanks for bringing this to our attention. GoogLeNet needs an update (considering this an extension/duplicate of https://github.com/deeplearning4j/deeplearning4j/issues/4182) and I am waiting for some final updates on master for the next release. Will close and reference this in the other issue.

**Closed by crockpotveggies** 2017-12-18 16:46 UTC
