### ISSUE TITLE
libopenblas_nolapack.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sergmain** [deeplearning4j/deeplearning4j#6132] opened 2018-08-10 15:30 UTC
Hello, 

I've just tried to run my application on beta2 and I've got the follow exception:
Caused by: java.lang.UnsatisfiedLinkError: /app/.javacpp/cache/openblas-0.3.0-1.4.2-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjniopenblas_nolapack.so: libopenblas_nolapack.so.0: cannot open shared object file: No such file or directory

You can find full stacktrace here - https://gist.github.com/sergmain/0685cda1456721595637def8ca347662

Few days ago, I opened an issue https://github.com/deeplearning4j/deeplearning4j/issues/6083 
Since then the issue was fixed and beta2 was released.

I rolled back to beta and my application started to work.

there is stub project for reproducing this problem on heroku
https://github.com/sergmain/dl4j-uber-jar
It doesn't contain actual keras model in this repo but you can use any.

Summary:
beta - working
beta2 - not working
target OS - Heroku's PaaS
target pratform for DL4J is specified in /.mvn/jvm.config

**Comment by saudet** [comment] 2018-08-10 22:30
Could you set the "org.bytedeco.javacpp.logger" system property to "slf4j", with a logger set to debug,  and post the log again? Thanks!

**Comment by sergmain** [comment] 2018-08-11 08:45
Here - https://gist.github.com/sergmain/d42dd786b3d9325f94b53dee376f8d19

Btw, developers from bytedeco should rewrite its logging system. Using system property to configure application is bad practice.

**Comment by agibsonccc** [comment] 2018-08-11 10:05
@sergmain We maintain bytdececo too.  We also use system properties to configure nd4j as well. I'm not sure where you got that from, but you just dissed a good number of the top java libraries used by more than half the ecosystem. When  you've built your successful library, you can show us how to do it :).

**Comment by sergmain** [comment] 2018-08-11 13:01
There are such things as JEE aplication servers, servlet containers, portals, OSGi container (not sure about it, actualy) which use single JVM to run numbers af application. In such environment using system properties is a bad practice.

About relating to topic. @saudet asked me to make some sets and rerun test. It took time to realize what does it mean "set the "org.bytedeco.javacpp.logger" system property to "slf4j" and even I had to check out completely repo of javacpp and look in the code to understand how to do that.

**Comment by agibsonccc** [comment] 2018-08-11 13:31
@sergmain yes we run things there too.Most libraries do not make the assumptions about those things anymore. There are also desktop application with plugins. Generally, system properties are for once per startup global state. In practice this isn't a problem and has more benefits than problems (and frankly as a library author myself, there is just no general purpose way to do this, the alternative is a bunch of random 1 off configuration files. Again, we are not changing it and your suggestions are not relevant.

Beyond that, instead of complaining, file an issue on the docs and I'm sure he'd be happy to update it if you have a concrete suggestion on making things better. You're not helping us help you by acting the way you are. Please ease up and just let us do what we need to do to help you.

**Comment by saudet** [comment] 2018-08-11 22:24
@sergmain Yes, this is a global setting, it's not meant to be changed per application. In any case, JNI does not support being loaded from multiple class loaders, so JavaCPP and ND4J need to be loaded by a shared class loader anyway.

It seems there is something strange with the URL class. These 2 lines:
> Extracting jar:file:/app/target/dl4j-uber-jar.jar!/BOOT-INF/lib/mkl-dnn-0.15-1.4.2-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libmklml_intel.so
> Loading /app/.javacpp/cache/mkl-dnn-0.15-1.4.2-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmklml_intel.so

Should actually be:
> Extracting jar:file:/app/target/dl4j-uber-jar.jar!/BOOT-INF/lib/mkl-dnn-0.15-1.4.2-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libmklml_intel.so#libopenblas_nolapack.so.0
> Loading /app/.javacpp/cache/mkl-dnn-0.15-1.4.2-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libopenblas_nolapack.so.0

What's the exact version of the JDK as returned by `java -version`?

**Comment by sergmain** [comment] 2018-08-11 22:57
@saudet , properties is here - https://gist.github.com/sergmain/9263e5f56254e19434878714515a74bb

heroku project on github as well, so you can request the help directly form heroku team
https://github.com/heroku

**Comment by saudet** [comment] 2018-08-11 23:07
There doesn't seem to be anything funny with this environment, not sure it's an issue with Heroku. What happens if you use your uber JAR locally with a simple `main()` method? Does it succeed?

**Comment by sergmain** [comment] 2018-08-11 23:15
Yes, it's working, but my dev enviroment is windows. I'd like to point out to the fact that 1.0.0-beta is working in heroku.

**Comment by sergmain** [comment] 2018-08-11 23:25
idk what does that mean - "That will happen with you exclude the MKL-DNN dependency."
project which I use for testing is here https://github.com/sergmain/dl4j-uber-jar

**Comment by saudet** [comment] 2018-08-12 02:25
`org.nd4j.linalg.factory.Nd4j.create(1)` works for me on Linux with the libs it bundles. Might be related to Spring then. Could you try to load JavaCPP and ND4J as shared libraries?

**Comment by agibsonccc** [comment] 2018-08-12 04:55
@sergmain could you try the uber jar with shade plugin instead maybe? I know what we're showing you here for troubleshooting is new. If you don't want to worry about some of the things sam is telling you, try doing it the way we do it in the standalone examples project:  https://github.com/deeplearning4j/dl4j-examples/blob/master/standalone-sample-project/pom.xml

**Comment by saudet** [comment] 2018-08-14 02:08
In any case, if MKL-DNN isn't a concern, we can exclude it from your project like this in the `pom.xml` file:
```xml
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
            <version>${nd4j.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bytedeco.javacpp-presets</groupId>
                    <artifactId>mkl-dnn</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
And it will work just like 1.0.0-beta.

**Comment by saudet** [comment] 2018-08-15 06:35
@sergmain Could you also post the log from JavaCPP?

**Comment by saudet** [comment] 2018-08-15 06:38
Also, does this happen only with Spring? Or does it happen with other containers or just raw Java on Heroku's PaaS?

**Comment by sergmain** [comment] 2018-08-15 09:30
@saudet the last gist contains log from javacpp. Or you need other log info?

I don't use dl4j with any other containers nor PaaS, so idk. btw, on windows it's working.
"Also, does this happen only with Spring?" -  my application is Spring based only.

**Comment by saudet** [comment] 2018-08-16 00:15
So it works with Spring on Windows?

**Comment by herofe** [comment] 2018-08-21 15:46
I'm having the same problem, running with spring framework and beta2 on a docker instance based on amazon linux 2018.03 with java8.

Not solved yet, but workaround for a testing instances for me was to spin up a normal ec2 instance with same OS as my docker instance and run the application, look in the directory .javacpp and from there copy the missing library files from the ec2 instance to /usr/lib on the docker instance before starting the app.

For me the missing libs where;
libopenblas_nolapack.so.0
libmklml_intel.so
libiomp5.so

All found in .javacpp/cache/lib, must be some packages not included on my docker instance that are installed on the ec2 instance?

**Comment by saudet** [comment] 2018-08-22 07:43
@borkox observed the same issue with Spring on Windows, so it looks like this issue is related to Spring only. Is anyone able to reproduce outside Spring?

**Comment by herofe** [comment] 2018-08-23 12:54
I managed to corner the problem a bit more.
I'm running same code with spring on two different amazon instances, and its failing on one and working on one.

The difference is installed cuda and intel mkl-dnn on the working instance.

For beta2 I also had to exclude mkl-dnn in the pom as indicated.

Working amazon ami: Deep Learning Base AMI (Amazon Linux) Version 9.0 (ami-8abca260)
Not working amazon ami: amzn-ami-hvm-2018.03.0.20180811-x86_64-gp2 (ami-047bb4163c506cd98)

**Comment by saudet** [comment] 2018-08-25 05:08
There are other differences like `glibc 2.17`... Is there a Docker image out there for which it fails to work properly? That would be the easiest way to debug this.

**Comment by herofe** [comment] 2018-08-25 07:08
Yes. This Docker is not working for me. 

FROM amazonlinux:2018.03

**Comment by saudet** [comment] 2018-08-25 07:09
@herofe Thanks! Would you also have a small project that I can execute in it?

**Comment by herofe** [comment] 2018-08-25 07:16
Nothing that I can share out of the box. Would need to pull out the pom and one or two java file in a new project and test if that fails. Can help with that next week if you need it.

**Comment by saudet** [comment] 2018-08-25 07:32
There's https://github.com/sergmain/dl4j-uber-jar, I wonder why I'd have to run exactly to get it to fail...

**Comment by borkox** [comment] 2018-08-25 07:34
I think I found the reason.
I started a debug session like this:
`"c:\Program Files\Java\jdk1.8.0_60\bin\java.exe" -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar target\rltrader-1.0-SNAPSHOT.jar`

Then looking at `class org.bytedeco.javacpp.Loader.class
method static String load(Class cls, Properties properties, boolean pathsFirst)` I noticed that 2 two DLL libraries are loaded ok, but the third isnt loaded because the paths of the extracted libraries are not correct. I will share images.

![image](https://user-images.githubusercontent.com/21053237/44616081-16511f80-a852-11e8-9c92-d290ac798e5d.png)
![image](https://user-images.githubusercontent.com/21053237/44616090-341e8480-a852-11e8-9f98-2b8ea2106f53.png)
![image](https://user-images.githubusercontent.com/21053237/44616110-75af2f80-a852-11e8-8b4a-cf1f7edf0e6e.png)

**Comment by saudet** [comment] 2018-08-25 07:38
Yes, it's not extracted correctly, but the cause of why that happens is unclear. It sounds like the container is hijacking the java.net.URL class and replacing it with a buggy version that doesn't support fragments.

**Comment by sergmain** [comment] 2018-08-25 09:02
@saudet Maybe this is important info about heroku environment:
"Why are my file uploads missing/deleted?"
https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

That's why I create a temp model file in ./target in my dl4j-user-jar sample. 
https://github.com/sergmain/dl4j-uber-jar/blob/a903ce7abffeb5dd1549a4a579fd5f544cd6425d/src/main/java/com/xxx/ModelService.java#L26

**Comment by borkox** [comment] 2018-08-25 09:04
Samuel, I was not sure if this is correct, see my picture:
![image](https://user-images.githubusercontent.com/21053237/44616786-0a1f8f00-a85f-11e8-8f45-084be4c737b4.png)

**Comment by borkox** [comment] 2018-08-25 09:11
Well, at least the next picture sounds strange to me
![image](https://user-images.githubusercontent.com/21053237/44616825-dee96f80-a85f-11e8-88f7-0f5e2082133e.png)

How comes that obenblas lib is resolved to mklml.dll
The long line urls which is not visible on the screenshot is:
file:/D:/work/rltrader-copy/rltrader/target/rltrader-1.0-SNAPSHOT.jar!/BOOT-INF/lib/openblas-0.3.0-1.4.2-windows-x86_64.jar!/org/bytedeco/javacpp/windows-x86_64/libopenblas.dll

**Comment by sergmain** [comment] 2018-08-25 09:30
with -Dorg.bytedeco.javacpp.cachedir=./target/.javacpp the error is the same

**Comment by sergmain** [comment] 2018-08-25 10:02
list of actual libraries:
https://gist.github.com/sergmain/5c4eb435af43e2dabc89e4113ccbb4b3

**Comment by sergmain** [comment] 2018-08-25 11:59
libs with ldd info
https://gist.github.com/sergmain/18cd2138e837220839e416025e4601cd

**Comment by saudet** [comment] 2018-08-26 03:59
@sergmain @borkox When you run it outside Spring, it runs correctly, right? So that's how it should work inside Spring as well, but it doesn't, why? What's the difference?

**Comment by sergmain** [comment] 2018-08-26 08:09
"When you run it outside Spring, it runs correctly, right?:, Nop
ldd(1) - Linux man page
In the usual case, ldd invokes the standard dynamic linker (see ld.so(8)) with the LD_TRACE_LOADED_OBJECTS environment variable set to 1, which causes the linker to display the library dependencies.
https://linux.die.net/man/1/ldd

**Comment by borkox** [comment] 2018-08-26 08:28
Non deterministic behaviour can happen when you iterate values from a map or when you iterate keys from a map.

**Comment by borkox** [comment] 2018-08-26 08:32
It runs well outside spring, but we wouldn't spend this time to debug if we liked to void spring.

**Comment by saudet** [comment] 2018-08-26 08:32
@sergmain Ok, even better, do you have a Docker image and a small project that I could use to debug this here?

@borkox Map, which map?

**Comment by sergmain** [comment] 2018-08-26 08:54
@saudet Nop, I don't have any

**Comment by borkox** [comment] 2018-08-26 09:47
Samuel, I was talking in principle that non deterministic behaviour can come from several different places, like iterating a map, an order in a packed ZIP file, not a concrete thing for our case. If you see my screenshots, I pointed out that "libopenblas it sees that lib is already loaded from some other place". Isn't that the track we should follow?

**Comment by sergmain** [comment] 2018-08-26 10:54
@saudet I think, bug is here:
https://github.com/bytedeco/javacpp/blob/c50d69f896332e6817cb371fdfc43b86fbbedc85/src/main/java/org/bytedeco/javacpp/Loader.java#L1141

You should do it in 2-way:
- exatract all assets, create symbolic link
- load all assets

**Comment by saudet** [comment] 2018-08-26 11:12
@sergmain That's not related to this issue, but if you would like to change this, feel free to send a pull request and let's evaluate it.

**Comment by borkox** [comment] 2018-08-26 14:38
[example.zip](https://github.com/deeplearning4j/deeplearning4j/files/2321593/example.zip)

I created a small project which is doing nothing but is failing with unsatisfied linkage error. Samuel can use this to debug in windows environment. I deleted the target folder, because it was 800 MB. Samuel, if you need the built jar I will attach it here. So there can be unnecessary libs, I am sorry , but I just deleted everything from my original failing project and just put static initializer to trigger the error.

I hope will help to debug the issue.

The main class is extremely simple: 
```
package com.example;


import org.nd4j.linalg.api.buffer.DataBuffer;
import org.nd4j.linalg.factory.Nd4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App implements CommandLineRunner {

    static{
        Nd4j.EPS_THRESHOLD = 1e-7;
        //Double precision for the gradient checks.
        // See also http://nd4j.org/userguide.html#miscdatatype
        Nd4j.setDataType(DataBuffer.Type.DOUBLE);
    }

    @Override
    public void run(String... args) throws Exception {

    }
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

}

```

So first you need to build it : 
`mvn clean install`

And then you run it with run.bat

For easines I put run_debug.bat which will suspend the VM until you connect with debugger.

**Comment by saudet** [comment] 2018-08-27 00:50
@borkox Thanks! I can reproduce the issue with that here. So, it is related to Spring...

**Comment by saudet** [comment] 2018-08-27 01:29
I found the issue. The issue is with Spring overriding the protocol handler for JAR files with `org.springframework.boot.loader.jar.Handler`, which doesn't support fragments. When running, for example, `System.out.println(new java.net.URL("jar:file:/myjar.jar!/file#foo"));` with Spring we get `jar:file:/myjar.jar!/file`, which is incorrect, but without Spring we get the correct output of `jar:file:/myjar.jar!/file#foo`.

Is there a version of Spring you guys can use that doesn't have this bug? Or is this a "feature" of Spring and we'll need to work around this?

**Comment by borkox** [comment] 2018-08-27 06:41
Hi Samuel. If that's the case, then how would you explain that the same version of this is working on linux ? With Spring again. For me problem is with Windows only.

**Comment by saudet** [comment] 2018-08-27 06:43
It fails in exactly the same way for me on Linux.

**Comment by herofe** [comment] 2018-08-27 07:11
Googled and found this from spring-boot project, looks like the problem saudet found with the spring Handler stripping fragments?

https://github.com/spring-projects/spring-boot/issues/14011

Looks like its included in spring-boot 1.5.16, which is the latest snapshot. I will check later this week to se if its fixing the issue.

**Comment by sergmain** [comment] 2018-08-27 19:19
Checked this issue with Spring boot v2.1.0.M2 and it was fixed. Fixed in all snapshot versions too.

**Comment by saudet** [comment] 2018-09-02 02:13
I'll close this for now, but let me know if there is more to this issue, thanks!

**Closed by saudet** 2018-09-02 02:13 UTC
Labels: ND4J, Question

**Comment by lutogniew** [comment] 2018-09-16 21:56
So I've decided to build OpenBLAS myself to see if this would fix the issue. I followed the instructions here:

https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio

The only difference being in the configure line - we want a "nolapack" DLL, so I guess the line should be:

    cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DBUILD_WITHOUT_LAPACK=yes -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release

Note all the commands should be executed from the Anaconda prompt. If you get failures with `clang-cl.exe` being unable to compile the test program, make sure you have no whitespace in the absolute path to OpenBLAS project directory - clang seems not to support those.

Now, putting the resulting lib as `libopenblas_nolapack.dll` in `.javacpp/cache` did nothing - even though Dependency Walker now showed that everything's alright with `jniopenblas_nolapack.dll`, Loader still complained. Running the app with `-Djava.library.path=""` didn't help either.

However, putting the DLL as `libopenblas_nolapack.dll` in one of the directories listed in `java.library.path` when calling `java -XshowSettings:properties -version` suddenly made the Loader happy. I succesfully loaded a Word2Vec file that previously failed because of missing dependencies.

I've also naively tried making symlinks pointing at `libopenblas.dll`, `mklml.dll` on the off chance that it works - of course it didn't.

So there's a workaround. I've no idea if the DLL is built properly, but it seems to work. Perhaps it'll help someone.

I'd still love to know what's the official way of making it work though.

**Comment by saudet** [comment] 2018-09-17 01:17
If the problem doesn't occur outside Spring, then the issue is with Spring.

**Comment by sergmain** [comment] 2018-09-17 09:01
@lutogniew could you try spring-boot-2.1.0-M3 ?
Also try to add jvm.config like this - 
https://github.com/sergmain/dl4j-uber-jar/blob/master/.mvn/jvm.config

for windows - javacpp.platform=windows-x86_64

**Comment by lutogniew** [comment] 2018-09-17 16:15
Okay, found the issue. It was the `org.springframework.boot` Gradle plugin. Version `2.0.4.RELEASE` breaks the app, version `2.0.5.RELEASE` makes it work - even with Spring Boot `2.1.0.M2`. Boot `2.1.0.M3` works too (but doesn't work with plugin `2.0.4.RELEASE` either).

**So:**

- with Boot Gradle plugin `2.0.4.RELEASE` none of the versions `2.0.4.RELEASE`, `2.0.5.RELEASE`, `2.1.0.M2` nor `2.1.0.M3` of Spring Boot work.
- with Boot Gradle plugin `2.0.5.RELEASE` all of the versions `2.0.4.RELEASE` (the one that I've used and failed originally), `2.0.5.RELEASE`, `2.1.0.M2` and `2.1.0.M3` work for me.

Checked different configurations a few times.

@sergmain Thank you for pointing me in the right direction!

Thanks guys.
