### ISSUE TITLE
NaN score

### ISSUE THREAD

**Issue by Lewerow** [deeplearning4j/deeplearning4j#257] opened 2015-05-19 14:02 UTC
I'm running IrisExample on current master with little modifications. Here's the code:

       public static void main(String[] args) throws IOException {
        Nd4j.MAX_SLICES_TO_PRINT = -1;
        Nd4j.MAX_ELEMENTS_PER_SLICE = -1;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .iterations(100).layer(new RBM())
                .weightInit(WeightInit.DISTRIBUTION).dist(new NormalDistribution(0, 0.01))
                .activationFunction("tanh").momentum(0.1).dropOut(0.0f)
                .optimizationAlgo(OptimizationAlgorithm.GRADIENT_DESCENT)
                .constrainGradientToUnitNorm(false)
                .visibleUnit(RBM.VisibleUnit.GAUSSIAN).hiddenUnit(RBM.HiddenUnit.RECTIFIED)
                .lossFunction(LossFunctions.LossFunction.EXPLL)
                .learningRate(0.1f)
                .nIn(4).nOut(3).list(2)
                .hiddenLayerSizes(new int[]{20})
                .override(new ClassifierOverride(1)).build();

        MultiLayerNetwork d = new MultiLayerNetwork(conf);
        d.init();
        d.setListeners(Arrays.asList((IterationListener) new ScoreIterationListener(1)));

        DataSetIterator iter = new IrisDataSetIterator(150, 150);

        DataSet next = iter.next(150);

        Nd4j.writeTxt(next.getFeatureMatrix(), "iris.txt", "\t");

        next.normalizeZeroMeanZeroUnitVariance();
        next.scaleMinAndMax(0.1, 0.9);
        next.shuffle();

        DataSet train = next;

        d.fit(train);

        DataSet test = next;

        Evaluation eval = new Evaluation();
        INDArray output = d.output(test.getFeatureMatrix());
        eval.eval(test.getLabels(),output);
        log.info("Score " + eval.stats());
    }

during execution, I receive the following output:
```
o.d.o.l.ScoreIterationListener - Score at iteration 0 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 1 is NaN
...

Actual Class 0 was predicted with Predicted 0 with count 50 times

Actual Class 1 was predicted with Predicted 0 with count 50 times

Actual Class 2 was predicted with Predicted 0 with count 50 times

==========================F1 Scores========================================
 0.16666666666666666
===========================================================================
```
I also get an error:
```
o.n.l.j.JCublasBackend - unable to load JCublas backend
java.lang.UnsatisfiedLinkError: Could not load the native library.
Error while loading native library "JCublas-windows-x86_64" with base name "JCublas"
Operating system name: Windows 7
Architecture         : amd64
Architecture bit size: 64
```
can it be the cause? I doubt it, as after changing lossFunction to `SQUARED_LOSS` scores are no longer NaN's. Is it possible to drop execution if it is known that "it won't work", preferably with some error message describing the problem?

Same problem occurs when using `MCXENT`, `EXPLL`, `NEGATIVELOGLIKELYHOOD` and `XENT`. While I can understand that predictions are totally not working because I've messed up something with configuration, these NaNs seem to be a bug.

**Comment by KeironO** [comment] 2015-05-21 13:35
Have you correctly installed of the pre-requisites for the dl4j framework?

Scroll down on this page and there are instructions for Microsoft Windows. http://deeplearning4j.org/gettingstarted.html

**Comment by Lewerow** [comment] 2015-05-21 13:56
Wouldn't missing dependencies cause some crash or exceptions? How can I verify whether everything is installed fine?

**Comment by KeironO** [comment] 2015-05-21 14:50
Well you're having some sort of error from the JVM aren't you?

First of all, make sure all pre-requisites are installed.

**Comment by Lewerow** [comment] 2015-05-21 15:28
You mean the "cannot find cublas" one? I managed to remove it, but it didn't help. I didn't spot any other JVM error.

**Comment by KeironO** [comment] 2015-05-21 15:44
Just played around with it and I was able to get 0.68 on a F-score with some extremely simplistic alterations.

Take a look at your configuration. I would also advise you to take a look at this - http://www.cs.toronto.edu/~hinton/absps/guideTR.pdf.

**Comment by Lewerow** [comment] 2015-05-21 15:53
0,68 like in manual, with totally ignored third class;) ? I also was able to achieve it with minor changes, no problem.
Anyway, I'm not worried about low F-scores, I was worried about this NaNs ;)

is it possible to provide some "configuration validator" for DL4J, so that it'll be possible to check everything in a simple way? because right now there is virtually no possibility to "be sure" - I've installed MinGW, added it in path, copied LAPACK and BLAS there, installed Anaconda and got DL4J from sources, so I have no idea what can be wrong. Any suggestions how to check this?

**Comment by agibsonccc** [comment] 2015-05-21 15:55
I will close this. Let's open another thread and talk about that a bit.

**Closed by agibsonccc** 2015-05-21 15:55 UTC

**Comment by agibsonccc** [comment] 2015-05-21 15:58
Re nans: this is caused by numerical underflow.

Nd4j has a neat knobs called Nd4j.ENFORCE_NUMERICAL_STABILITY = true

This performs a linear scan and purges nans from results everytime a matrix is returned. This can be expensive bit handy in debugging.
