### ISSUE TITLE
org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/api/complex/IComplexDouble

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#6068] opened 2018-08-03 09:32 UTC
Creating this issue as per the discussion yesterday. I re-tried the build today for this issue. Removed nd4j dependencies: `rm -rf ~/.m2/repository/org/nd4j` and re-build the project again:`mvn -U clean package. 
`
I'm still getting the below error:

root@instance-1:/home/Deeplearning4J# java -jar target/dl4j-1.0-SNAPSHOT.jar
09:28:22.171 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/api/complex/IComplexDouble
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5529)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5477)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:210)
        at org.datavec.image.transform.PipelineImageTransform.<init>(PipelineImageTransform.java:93)
        at org.datavec.image.transform.PipelineImageTransform.<init>(PipelineImageTransform.java:85)
        at org.datavec.image.transform.PipelineImageTransform.<init>(PipelineImageTransform.java:73)
        at examples.AnimalClassifier.main(AnimalClassifier.java:72)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.api.complex.IComplexDouble
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more
root@instance-1:/home/Deeplearning4J# ^C
root@instance-1:/home/Deeplearning4J#

**Comment by raver119** [comment] 2018-08-03 09:35
you'd better rebuilt whole stack including datavec. That might be how outdated stuff gets into your classpath

**Comment by rahul-raj** [comment] 2018-08-03 09:42
I actually did as suggested by Adam yesterday.
Removed all nd4j dependencies first. Since it complains about nd4j dependency class, I guess that would be enough. 
Then re-built the maven using snapshot download.

**Comment by AlexDBlack** [comment] 2018-08-03 09:43
This still has to be old/outdated snapshots on your local machine.
I just downloaded the latest nd4j-api sources JAR - and the text "IComplex" doesn't appear anywhere in org.nd4j.linalg.factory.Nd4j.java

https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-api/1.0.0-SNAPSHOT/nd4j-api-1.0.0-20180803.092041-6136-sources.jar
https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-api/1.0.0-SNAPSHOT/

**Comment by raver119** [comment] 2018-08-03 09:45
I'm recompiling Nd4j multiple times per day, no issues here as well. So it MUST be stale deps on your box being pulled in.

**Comment by sshepel** [comment] 2018-08-03 10:56
@rahul-raj  have you tried to remove deeplearning4j and datavec groups from local cache and rebuild your project, as suggested above?
```
rm -rf ~/.m2/repository/org/deeplearning4j
rm -rf ~/.m2/repository/org/datavec
```

**Comment by rahul-raj** [comment] 2018-08-03 11:09
@sshepel 
I'm re-building accordingly. Guess this would fix my issue. I will update the results here in few mins. Thank you!

**Comment by rahul-raj** [comment] 2018-08-03 11:15
Here is what I followed:

```
rm -rf ~/.m2/repository/org/deeplearning4j
rm -rf ~/.m2/repository/org/datavec
rm -rf ~/.m2/repository/org/nd4j
mvn -U clean package
```

And here is what I get again:

```
root@instance-1:/home/Deeplearning4J# java -jar target/dl4j-1.0-SNAPSHOT.jar
11:13:43.140 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/api/complex/IComplexDouble
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5529)
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5477)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:210)
        at org.datavec.image.transform.PipelineImageTransform.<init>(PipelineImageTransform.java:93)
        at org.datavec.image.transform.PipelineImageTransform.<init>(PipelineImageTransform.java:85)
        at org.datavec.image.transform.PipelineImageTransform.<init>(PipelineImageTransform.java:73)
        at examples.AnimalClassifier.main(AnimalClassifier.java:72)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.api.complex.IComplexDouble
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by sshepel** [comment] 2018-08-03 11:23
@rahul-raj is there any chance that you are using local proxy (internal) for snapshots?

**Comment by rahul-raj** [comment] 2018-08-03 11:28
@sshepel 
Nope, not using any proxy for snapshots.
Here is the pom.xml:
https://github.com/rahul-raj/Problem-Solving/blob/master/pom.xml

**Comment by sshepel** [comment] 2018-08-03 11:52
@rahul-raj could you please update this line https://github.com/rahul-raj/Problem-Solving/blob/master/pom.xml#L75 to cuda-9.2, same for your dev VM.

**Comment by rahul-raj** [comment] 2018-08-03 12:08
@sshepel 
Installing cuda 9.2 in the server at the moment. I will get back to you once I'm done.
Thank you.

**Comment by rahul-raj** [comment] 2018-08-03 12:45
@sshepel 
Awesome, Finally that fixed my issue 👍 
Thanks a lot for the tip :)
I have few other observations that may require further discussion and may be another issue creation. But that would be out of topic for this issue thread. Let me know if it's ok to discuss that here, otherwise I'm good to close this out for now.

**Comment by AlexDBlack** [comment] 2018-08-03 12:49
OK, great. I'll close this.

@sshepel So the cause here is that cuda 9.1 snapshots are out of date for some reason?

**Closed by AlexDBlack** 2018-08-03 12:49 UTC

**Comment by sshepel** [comment] 2018-08-03 13:05
@rahul-raj awesome!
@AlexDBlack the problem is that we dropped support of `cuda-9.1` and switched to `cuda-9.2` (so, latest snapshots updated only for `cuda 8, 9, 9.2` not `9.1`), but `cuda-9.1` artifacts are still exists on `OSS Nexus`.
That is why when @rahul-raj tried to build his project with `cuda-9.1`, maven fetched artifacts for `cuda-9.1` that are still exists, but for the rest dependencies artifacts were with the latest code base.

**Comment by AlexDBlack** [comment] 2018-08-03 13:08
Ah, got it. I didn't realize that we had done that already.
Time for me to upgrade to 9.2 too :)
