### ISSUE TITLE
Unsupported keras layer type Lambda. Please file an issue at

### ISSUE THREAD

**Issue by jesuino** [deeplearning4j/deeplearning4j#4530] opened 2018-01-21 20:49 UTC
#### Issue Description

I generated the h5 file as described here:

https://github.com/allanzelener/YAD2K/issues/57

I also tried to use a JSON config along with the weights in a separated file. All I have is this:

~~~
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Lambda. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:259)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:158)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:92)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:123)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:179)
	at org.fxapps.ml.deeplearning.LoadKerasYOLO.main(LoadKerasYOLO.java:30)
~~~

#### Version Information

* Deeplearning4j version

0.9.2-SNAPSHOT

**Comment by saudet** [comment] 2018-01-22 01:24
Duplicate of issue #4256

**Closed by saudet** 2018-01-22 01:24 UTC
Labels: duplicate, keras2
