### ISSUE TITLE
Deeplearning4j memory leakage

### ISSUE THREAD

**Issue by SergeyZYX** [deeplearning4j/deeplearning4j#3483] opened 2017-06-05 12:22 UTC
I deployed an application using Deeplearning4j, it starts with 8Gb memory usage and after about 48h it runs out of memory (32Gb). In a loop it creates new instance of MultiLayerNetwork, do some calculations than drops it. Ends up with java process consuming entire memory, the leakage is somehow outside of java heap.

I took and modified your official example UCISequenceClassificationExample to reproduce the error.
The following example will end up consuming all memory (depends on RAM and CPU) in 40+ hours.

Also I took screenshots of average memory usage of this example, and it shows the process uses 200mb more memory after 1 hour of run.

Deeplearning4j 0.8-SNAPSHOT
CentOS 7 x64
2x Intel Xeon E5-2420
32Gb RAM
Blas vendor MKL

![px](https://cloud.githubusercontent.com/assets/28604810/26783705/aad2561c-4a0a-11e7-91a8-4a75958b9dac.png)

[NetLeak.txt](https://github.com/deeplearning4j/deeplearning4j/files/1051974/NetLeak.txt)

**Comment by raver119** [comment] 2017-06-05 12:24
Show your pom.xml please.

**Comment by raver119** [comment] 2017-06-05 12:27
Also, please add some info about your JVM. Vendor, version etc.

**Comment by raver119** [comment] 2017-06-05 12:29
And, depending on jvm params, such fluctuations aren't symptoms of leak. JVM can easily use more or less rum, in bounds defined by Xmx.

**Comment by SergeyZYX** [comment] 2017-06-05 12:31
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

also tested with 

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

[pom.txt](https://github.com/deeplearning4j/deeplearning4j/files/1051983/pom.txt)

**Comment by SergeyZYX** [comment] 2017-06-05 12:32
my run params:
-Xms1G -Xmx28G

**Comment by raver119** [comment] 2017-06-05 12:37
Aha, that explains.

DL4j uses off-heap memory, and it's usually bad idea to allow > 50% total RAM, because JVM might be happy to use that amount eventually, and at the same time we might the same amount in off-heap memory. So, run with -Xmx16G instead, and you should be fine.

**Comment by raver119** [comment] 2017-06-05 12:38
Alternatively, you can set smaller Xmx, and configure our max off-heap allocation via jcpp variables

**Comment by SergeyZYX** [comment] 2017-06-05 12:43
I tried already with -Xmx14G not helped. Probably I should play with jcpp variables. Do you have any manual on it?

**Comment by raver119** [comment] 2017-06-05 12:44
Show me full console output with your crash. As full as possible, sure :)

**Comment by raver119** [comment] 2017-06-05 12:44
And what task you had when you've spotted issue? Images, by any chance?

**Comment by SergeyZYX** [comment] 2017-06-05 12:54
Jun  2 03:59:28 localhost kernel: 54910 total pagecache pages
Jun  2 03:59:28 localhost kernel: 36346 pages in swap cache
Jun  2 03:59:28 localhost kernel: Swap cache stats: add 1637683, delete 1601337, find 3848110/3896195
Jun  2 03:59:28 localhost kernel: Free swap  = 0kB
Jun  2 03:59:28 localhost kernel: Total swap = 4194300kB
Jun  2 03:59:28 localhost kernel: 8379742 pages RAM
Jun  2 03:59:28 localhost kernel: 0 pages HighMem/MovableOnly
Jun  2 03:59:28 localhost kernel: 194943 pages reserved
Jun  2 03:59:28 localhost kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Jun  2 03:59:28 localhost kernel: [  534]     0   534    32802     8214      68       44             0 systemd-journal
Jun  2 03:59:28 localhost kernel: [  549]     0   549    11097       78      22      274         -1000 systemd-udevd
Jun  2 03:59:28 localhost kernel: [  554]     0   554    29723        0      28       85             0 lvmetad
Jun  2 03:59:28 localhost kernel: [  747]     0   747    13854      112      25        1         -1000 auditd
Jun  2 03:59:28 localhost kernel: [  766]     0   766     4855       55      13       41             0 irqbalance
Jun  2 03:59:28 localhost kernel: [  768]     0   768   138290      167      88     3033             0 tuned
Jun  2 03:59:28 localhost kernel: [  769]   998   769   132432      600      58     1271             0 polkitd
Jun  2 03:59:28 localhost kernel: [  770]     0   770     6062       41      15       43             0 systemd-logind
Jun  2 03:59:28 localhost kernel: [  771]     0   771    77442     4938      79       97             0 rsyslogd
Jun  2 03:59:28 localhost kernel: [  777]   997   777     2131        7       9       29             0 lsmd
Jun  2 03:59:28 localhost kernel: [  782]    81   782     6633       59      17       67          -900 dbus-daemon
Jun  2 03:59:28 localhost kernel: [  808]     0   808    31968       21      19      125             0 smartd
Jun  2 03:59:28 localhost kernel: [  813]     0   813    26370       38      53      207         -1000 sshd
Jun  2 03:59:28 localhost kernel: [  818]     0   818    53153       24      57      391             0 abrtd
Jun  2 03:59:28 localhost kernel: [  820]   996   820    28962       30      26       68             0 chronyd
Jun  2 03:59:28 localhost kernel: [  822]     0   822    52571        9      56      331             0 abrt-watch-log
Jun  2 03:59:28 localhost kernel: [  830]     0   830    31555       80      18       75             0 crond
Jun  2 03:59:28 localhost kernel: [  832]     0   832     6461        5      16       47             0 atd
Jun  2 03:59:28 localhost kernel: [ 1104]     0  1104    22780       18      43      243             0 master
Jun  2 03:59:28 localhost kernel: [ 1106]    89  1106    22850       23      45      240             0 qmgr
Jun  2 03:59:28 localhost kernel: [ 2414]     0  2414    27509        1      10       32             0 agetty
Jun  2 03:59:28 localhost kernel: [ 7543]    26  7543    58601       45      52      238             0 postgres
Jun  2 03:59:28 localhost kernel: [ 7544]    26  7544    48537       29      42      242             0 postgres
Jun  2 03:59:28 localhost kernel: [ 7546]    26  7546    58627     3090      63      267             0 postgres
Jun  2 03:59:28 localhost kernel: [ 7547]    26  7547    58601     2357      63      249             0 postgres
Jun  2 03:59:28 localhost kernel: [ 7548]    26  7548    58601       21      46      257             0 postgres
Jun  2 03:59:28 localhost kernel: [ 7549]    26  7549    58806      147      62      350             0 postgres
Jun  2 03:59:28 localhost kernel: [ 7550]    26  7550    48577       51      42      241             0 postgres
Jun  2 03:59:28 localhost kernel: [62911]  1000 62911    28280        0      13       49             0 sh
Jun  2 03:59:28 localhost kernel: [62912]  1000 62912  9208519  5193261   11969   849278             0 java
Jun  2 03:59:28 localhost kernel: [49851]  1000 49851    28280        0      14       49             0 sh
Jun  2 03:59:28 localhost kernel: [49861]  1000 49861  6090553  2781163    5965   185660             0 java
Jun  2 03:59:28 localhost kernel: [10185]    89 10185    22806      258      46        0             0 pickup
Jun  2 03:59:28 localhost kernel: [44803]     0 44803    25839      237      53        0             0 sshd
Jun  2 03:59:28 localhost kernel: [42289]    26 42289    58778      226      47      197             0 postgres
Jun  2 03:59:28 localhost kernel: Out of memory: Kill process 62912 (java) score 655 or sacrifice child
Jun  2 03:59:28 localhost kernel: Killed process 62912 (java) total-vm:36834076kB, anon-rss:20773044kB, file-rss:0kB, shmem-rss:0kB

**Comment by SergeyZYX** [comment] 2017-06-05 12:54
it used 35Gb with  -Xmx14G

**Comment by SergeyZYX** [comment] 2017-06-05 12:55
no, it's plain data no images

**Comment by raver119** [comment] 2017-06-05 12:57
Is it hard requirement to re-instantiate the network, to cause oom?

**Comment by raver119** [comment] 2017-06-05 13:00
If yes, the first suspect will be RNG i think. I'll check it out.

**Comment by SergeyZYX** [comment] 2017-06-05 13:03
it took about 40+ hours, today I stop the process myself when I saw memory usage 99% and just restart with fresh copy, otherwise it should crash.

**Comment by raver119** [comment] 2017-06-05 13:05
Can you please check, if this issue is reproducible for you with 0.8.1-SNAPSHOT?

**Comment by SergeyZYX** [comment] 2017-06-05 13:07
ok i'll check

**Comment by raver119** [comment] 2017-06-05 13:23
No ideas what leaks for you yet, but after 100 "runs", i have the same 928MB allocated on GPU as after first run. So, if something is wrong, it's definitely not happening with CUDA backend, and probably not happening with ND4J, since underlying mechanics is +- the same for both backends :/

**Comment by raver119** [comment] 2017-06-05 13:27
Same 928MB after 200 runs. Will check CPU then...

**Comment by SergeyZYX** [comment] 2017-06-05 13:37
are you running 0.8.1-SNAPSHOT? yes, please check cpu.

**Comment by raver119** [comment] 2017-06-05 13:39
Yes, i'm on current master. So, slightly beyond snapshot, but that doesn't matters

**Comment by raver119** [comment] 2017-06-05 14:02
Well, with CPU backend i've found something i don't like, but that's not your case, minor issue was introduced at 0.8.1... However, nice to fix.

Besides that only thing i've found - stuff looks ok for both CPU & CUDA :/

**Comment by raver119** [comment] 2017-06-05 14:11
I'll keep your app running tonight, maybe we'll see something at morning... But looks stable so far

**Comment by raver119** [comment] 2017-06-05 19:45
11827 runs after - still runs. JVM profiling shows nothing major. overall memory use is slightly below allowed 3GB.

**Comment by raver119** [comment] 2017-06-05 19:46
![screenshot from 2017-06-05 22-46-25](https://cloud.githubusercontent.com/assets/12250879/26800145/d615263e-4a40-11e7-9faa-67491688571a.png)

**Comment by SergeyZYX** [comment] 2017-06-06 02:45
ok, it won't appear if nothing changed for hours. today I try to reproduce it with 0.8.1-SNAPSHOT.

**Comment by raver119** [comment] 2017-06-06 05:47
32469 runs finished, unfortunately can't run longer: i have to reboot to windows.

Please show me your original code, that caused your issue.

**Comment by SergeyZYX** [comment] 2017-06-06 10:57
this example is a cut of my original code running on slice of my data
[netleak.zip](https://github.com/deeplearning4j/deeplearning4j/files/1054680/netleak.zip)
I started it on server now. It consumes 37% of memory now, will see tomorrow.

**Comment by raver119** [comment] 2017-06-06 14:02
Ugh.

That's not a leak. That's java mechanics. You're submitting Callable task to ExecutorService.
You HAVE to fetch data from it, otherwise it's waiting it forever (or if queue is blocking, untill queue is full)

**Comment by SergeyZYX** [comment] 2017-06-06 15:09
of course i am fetching and releasing it. here i use no fetch cause i made an infinite loop just for example. 45% of memory for now after 4 hours. i guess it will run out of memory somewhere,

**Comment by raver119** [comment] 2017-06-06 15:17
Show me real code please, because guessing isn't any productive.

**Comment by SergeyZYX** [comment] 2017-06-06 15:37
The project is very big. In this file calculateDNAPerformance() is the only function in a whole project which has a call to DL4j. It uses as evaluation. I have an alternate evaluate option, and it works without leakage.

[BaseEvolution.txt](https://github.com/deeplearning4j/deeplearning4j/files/1055522/BaseEvolution.txt)

anyway, if infinite loop app will work well for 48h+ means I have wrong memory settings for DL4j, sorry.

**Comment by raver119** [comment] 2017-06-06 16:30
Any chance for data dimensionality changes between runs?

**Comment by SergeyZYX** [comment] 2017-06-06 17:50
data dimensionality depends on exact DNA we are evaluating and could vary

**Comment by raver119** [comment] 2017-06-06 17:58
Aha. Add some more details please :)

I'm speaking specifically about DataSet features/labels dimensionality here.

**Comment by SergeyZYX** [comment] 2017-06-06 18:03
DNA could have different columns number, so features/labels could change, yes

**Comment by SergeyZYX** [comment] 2017-06-06 18:10
as for RNN we have 3d (X,Y,Z) data, so for a single colony Y (columns) is variable but X&Z are fixed. between colonies X&Z could vary. different colonies runs in separate threads.

**Comment by raver119** [comment] 2017-06-06 18:14
Okay, i'll check various caches then.

**Comment by SergeyZYX** [comment] 2017-06-07 02:42
mem usage grows very slowly but stable, 51.3% as for now.
jvmtop shows heap max 12.7Gb
started with -Xmx 14G

**Comment by saudet** [comment] 2017-06-07 02:50
It might help to know if this is memory not deallocated by JavaCPP, and thus ND4J. We can check that by calling the `org.bytedeco.javacpp.Pointer.totalBytes()` static method.

**Comment by SergeyZYX** [comment] 2017-06-07 12:12
still slowly climbing 52.9% now
java HeapMax 12.7Gb - no change, the reason is outside of heap.
i stop it.

**Comment by raver119** [comment] 2017-06-07 12:26
Can you show me screenshots (or better dump) from any java profiler? I'm interested in objects within heap.

Yourkit profiler dump would be best fit here

**Comment by saudet** [comment] 2017-06-07 12:50
Ok, so we know it's off-heap memory, but I'm wondering if it's being tracked by JavaCPP, which would indicate a bug in ND4J, or not, which might indicate an issue with the OS, as with https://github.com/bytedeco/javacpp-presets/issues/423 .

**Comment by SergeyZYX** [comment] 2017-06-08 13:27
I have modified NetLeak example to output org.bytedeco.javacpp.Pointer.totalBytes()
[NetLeak.txt](https://github.com/deeplearning4j/deeplearning4j/files/1061094/NetLeak.txt)

and that's what I found in output:
09:17:50.827 [pool-1-thread-3] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
09:17:51.082 [pool-1-thread-3] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 6
09:17:51.553 [pool-1-thread-3] INFO  org.reflections.Reflections - Reflections took 424 ms to scan 1 urls, producing 29 keys and 189 values 
09:17:52.923 [pool-1-thread-3] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 6
09:17:52.931 [pool-1-thread-3] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
09:17:52.932 [pool-1-thread-3] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [24]; Memory: [7.1GB];
09:17:52.932 [pool-1-thread-3] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
09:17:57.546 [pool-1-thread-2] INFO  org.reflections.Reflections - Reflections took 4231 ms to scan 4 urls, producing 4309 keys and 24049 values 
09:17:58.567 [pool-1-thread-6] INFO  org.reflections.Reflections - Reflections took 391 ms to scan 1 urls, producing 373 keys and 1449 values 
09:18:03.231 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 490563229 byte(s)
09:18:03.318 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 494068497 byte(s)
09:18:03.739 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 508059381 byte(s)
09:18:06.816 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 830956937 byte(s)
09:18:06.904 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 838832941 byte(s)
09:18:07.216 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 858230421 byte(s)
09:18:10.492 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 1200077517 byte(s)
09:18:10.495 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 1200234157 byte(s)
09:18:10.541 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 1201964781 byte(s)
09:18:13.710 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 1535898081 byte(s)
09:18:14.115 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 1561784353 byte(s)
09:18:14.179 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 1562910209 byte(s)
09:18:17.037 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 1893605125 byte(s)
09:18:17.154 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 1907688933 byte(s)
09:18:17.238 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 1911769009 byte(s)
09:18:32.910 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 2066754481 byte(s)
09:18:33.072 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 2081103949 byte(s)
09:18:33.511 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 2105404953 byte(s)
09:18:36.477 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 2432031037 byte(s)
09:18:36.480 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 2432326205 byte(s)
09:18:36.725 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 2447219461 byte(s)
09:18:39.625 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 2769158033 byte(s)
09:18:39.692 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 2773403725 byte(s)
09:18:40.464 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 2792932797 byte(s)
09:18:43.219 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 3106540281 byte(s)
09:18:43.250 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 3108703069 byte(s)
09:18:43.645 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 3129794061 byte(s)
09:18:46.449 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 3426387077 byte(s)
09:18:46.740 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 3455260861 byte(s)
09:18:47.616 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 3507017149 byte(s)
09:19:04.706 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 3592325737 byte(s)
09:19:04.931 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 3608944493 byte(s)
09:19:05.099 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 3617493573 byte(s)
09:19:08.041 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 3937727597 byte(s)
09:19:08.294 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 3963582857 byte(s)
09:19:08.378 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 3968170869 byte(s)
09:19:11.481 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 4279735745 byte(s)
09:19:11.928 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 4313512397 byte(s)
09:19:12.241 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 4329774385 byte(s)
09:19:15.096 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 4644794001 byte(s)
09:19:15.517 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 4671655705 byte(s)
09:19:15.756 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 4681395545 byte(s)
09:19:18.679 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 4991541333 byte(s)
09:19:18.829 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 5007978201 byte(s)
09:19:19.199 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5024786485 byte(s)
09:19:50.687 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 5047346337 byte(s)
09:19:52.178 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 5236410229 byte(s)
13:45:33.356 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5272850289 byte(s)
13:58:26.982 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 5312774353 byte(s)
13:58:27.463 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 5361951833 byte(s)
14:05:12.233 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5363670025 byte(s)
14:06:20.775 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 5377207353 byte(s)
14:07:28.711 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5393544673 byte(s)
14:09:09.604 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5425845557 byte(s)
14:20:22.312 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 5468312293 byte(s)
14:20:23.967 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5481160057 byte(s)
14:29:00.567 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 5490013045 byte(s)
14:33:31.881 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 5502909333 byte(s)
14:39:42.319 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5528103421 byte(s)
14:46:22.335 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 5534613313 byte(s)
14:46:22.612 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5544040337 byte(s)
14:48:38.273 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 5559463429 byte(s)
14:50:17.298 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5643002973 byte(s)
15:03:01.470 [pool-1-thread-5] INFO  com.ddx.netleak.NetLeak - 5663616469 byte(s)
15:03:01.626 [pool-1-thread-3] INFO  com.ddx.netleak.NetLeak - 5674072121 byte(s)
15:03:01.822 [pool-1-thread-1] INFO  com.ddx.netleak.NetLeak - 5684587785 byte(s) 

It holds 4 hours running from 09:19 to 13:45 and than starting to allocate more.

raver119, Yourkit is not free, if you can recommend java profiler which is free and can output to file or console, it would be great. I can dump whole process memory or any part of it in linux, but I can't figure out where is heap/noheap part of it.

**Comment by raver119** [comment] 2017-06-08 13:33
Yourkit offers free trial for 15 days, and that's the best possible profiler.

There's also jvisualvm profiler, bundled with jdk, it has support for snapshots too. However, yourkit is way better, and if you can use free trial - that would be awesome.

**Comment by SergeyZYX** [comment] 2017-06-17 16:17
Sorry, I was on vacation, couldn't write here.

I started 2 NetLeak applications (netleak.zip) with following params:
-Xmx8G
and connected Yourkit on em.

MAX (org.bytedeco.javacpp.Pointer.totalBytes) was around 6Gb on each
Heap MAX (by Yourkit) 3.4Gb
Non-Heap MAX (by Yourkit) 42Mb
Everything was just fine, BUT, each thread consuming more and more memory as time progressed, and
finally they both consumed 50% of total ram each and both oomed.
It took 80+ hours.
Under real load on different datasets it happens faster.

**Comment by SergeyZYX** [comment] 2017-06-17 16:31
![bf](https://user-images.githubusercontent.com/28604810/27254585-f7b5ab24-539b-11e7-9812-29a2dfddd889.png)

**Comment by SergeyZYX** [comment] 2017-06-17 16:35
This is under real application, the picture is fine
![rl](https://user-images.githubusercontent.com/28604810/27254593-50751f60-539c-11e7-9f1f-ee96b90cf356.png)
but 
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Cannot allocate new IntPointer(10): totalBytes = 759M, physicalBytes = 14G

**Comment by raver119** [comment] 2017-06-18 08:42
Can i have memory snapshot/dump from yourkit?

**Comment by SergeyZYX** [comment] 2017-06-18 09:33
https://yadi.sk/d/ql05qVZj3KEAMF

**Comment by saudet** [comment] 2017-06-18 14:26
It sounds like problems with memory fragmentation...

**Comment by raver119** [comment] 2017-06-18 15:16
Mmmm, i think i can write simple app & micro nd4j tweak, that'll notify on each and every allocation & deallocation that happen in native codebase. At least for CUDA backend that's trivial. And simple perl/bash/whatever script that'll do summary of all malloc/free calls each hour. If stuff sums up to 0 at the end of process - it's not a leak then.

**Comment by raver119** [comment] 2017-06-18 15:16
Hm. Actually no, i want that in ND4j codebase as debugging option!

**Comment by saudet** [comment] 2017-06-19 03:15
Are you saying that you cannot reproduce the issue with the example code?

A low value for `Pointer.totalBytes()` indicates that something else is probably leaking memory, not ND4J. Test the other components in your application for any leaks there.

**Comment by SergeyZYX** [comment] 2017-06-19 07:15
Yes, Pointer.totalBytes(), stop growing at some point. I guess it's reproducible on example, but I didn't test it till the end. Netleak.zip is pretty much an official example but with piece of my dataset. I made dirty workaround, just restarting the process, before it reaches critical point, now it works just fine)

**Comment by saudet** [comment] 2017-06-20 01:47
When the memory gets too fragmented, it can cause memory allocation and deallocation to slow down too much to the point of generating OutOfMemoryError. As mentioned above though, the new "workspace" feature that is in 0.8.1-SNAPSHOT should help with that.

**Comment by AlexDBlack** [comment] 2018-04-25 09:12
Closing this as obsolete - considerable improvements to memory management have been made since this issue was last looked at.

**Closed by AlexDBlack** 2018-04-25 09:12 UTC
Labels: bug
