### ISSUE TITLE
MultiLayerNetwork score method vs. ComputationGraph score method memory issue

### ISSUE THREAD

**Issue by Rolnire** [deeplearning4j/deeplearning4j#9117] opened 2020-10-27 08:44 UTC
Hello, 
I am using **TinyYOLO** as MultiLayerNetwork and as ComputationGraph. For calculating score of minibatch I am using score method. With MLN everything works well, memory usage is stable. However, if I change MLN to CG (same architecture, same params.), score method is not working well anymore. Memory usage is unstable and I am getting OOM exception. I found out, with MLN there is open memory WS when invoking computeBackpropGradiendAndScore() on output layer (Yolo2OutputLayer), but in case of CG there is **not** open memory WS. So I guess, that every created INDArray in that method is created out of any memory WSs.

I have this issue with CPU and GPU backend, however on GPU backend this is more relevant, because of limited GPU memory.

DL4J version is beta7, also tried SNAPSHOT
CUDA version 10.2
NVIDIA driver version 440.33.01

And there is my pom with CPU backend:

	<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>eu.extech.deep_learning</groupId>
	<artifactId>Dl4j-cpulibs</artifactId>
	<version>1.0.0-beta7</version>
	<packaging>pom</packaging>

	<name>Dl4j-cpulibs</name>
	<url>http://maven.apache.org</url>

	<properties>
		<nd4j.backend>nd4j-native</nd4j.backend>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<shadedClassifier>bin</shadedClassifier>

		<java.version>1.8</java.version>
		<nd4j.version>1.0.0-SNAPSHOT</nd4j.version>
		<dl4j.version>1.0.0-SNAPSHOT</dl4j.version>
		<datavec.version>1.0.0-SNAPSHOT</datavec.version>
		<arbiter.version>1.0.0-SNAPSHOT</arbiter.version>
		<rl4j.version>1.0.0-SNAPSHOT</rl4j.version>

		
		<dl4j.spark.version>1.0.0-beta7_spark_1</dl4j.spark.version>
		<datavec.spark.version>1.0.0-beta7_spark_1</datavec.spark.version>

		
		<scala.binary.version>2.11</scala.binary.version>

		<hadoop.version>2.2.0</hadoop.version>  
		<guava.version>19.0</guava.version>
		<logback.version>1.2.3</logback.version>
		<jfreechart.version>1.0.13</jfreechart.version>
		<jcommon.version>1.0.23</jcommon.version>
		<maven-compiler-plugin.version>3.6.1</maven-compiler-plugin.version>
		<maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
		<exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
		<maven.minimum.version>3.3.1</maven.minimum.version>
		<javafx.version>2.2.3</javafx.version>
		<aws.sdk.version>1.11.109</aws.sdk.version>
		<jackson.version>2.5.1</jackson.version>
		<scala.plugin.version>3.2.2</scala.plugin.version>

		<jersey.version>2.30.1</jersey.version>
		<jetty.version>9.4.27.v20200227</jetty.version>
	</properties>

	<repositories>
		<repository>
			<id>maven.restlet.org</id>
			<name>maven.restlet.org</name>
			<url>http://maven.restlet.org</url>
		</repository>

		<repository>
			<id>objectdb</id>
			<name>ObjectDB Repository</name>
			<url>https://m2.objectdb.com</url>
		</repository>

		<repository>
			<id>snapshots-repo</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>daily</updatePolicy>  
			</snapshots>
		</repository>
	</repositories>

	<parent>
		<groupId>org.deeplearning4j</groupId>
		<artifactId>deeplearning4j-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

	<dependencies>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>${nd4j.backend}</artifactId>
			<version>${nd4j.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.bytedeco</groupId>
					<artifactId>leptonica-platform</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
			</exclusions>
		</dependency> 

		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-nlp</artifactId>
			<version>${dl4j.version}</version>
		</dependency>

		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-zoo</artifactId>
			<version>${dl4j.version}</version>
		</dependency>

		
		<dependency>
			<groupId>com.workday</groupId>
			<artifactId>timeseries-forecast</artifactId>
			<version>1.1.1</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>${jetty.version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
			<version>${jetty.version}</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-server</artifactId>
			<version>${jersey.version}</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-jettison</artifactId>
			<version>${jersey.version}</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.containers</groupId>
			<artifactId>jersey-container-servlet-core</artifactId>
			<version>${jersey.version}</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.inject</groupId>
			<artifactId>jersey-hk2</artifactId>
			<version>${jersey.version}</version>
		</dependency>

		<dependency>
			<groupId>com.objectdb</groupId>
			<artifactId>objectdb</artifactId>
			<version>2.8.2</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>javax.persistence</artifactId>
			<version>2.1.0</version>
		</dependency>

		<dependency>
			<groupId>javax.transaction</groupId>
			<artifactId>jta</artifactId>
			<version>1.1</version>
		</dependency>

		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-ui</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>1.0.1</version>
				<executions>
					<execution>
						<id>enforce-default</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireMavenVersion>
									<version>[${maven.minimum.version},)</version>
									<message>********** Minimum Maven Version is
										${maven.minimum.version}. Please upgrade Maven before
										continuing (run "mvn --version" to check). **********</message>
								</requireMavenVersion>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>

			
			<plugin>
				<groupId>net.revelc.code.formatter</groupId>
				<artifactId>formatter-maven-plugin</artifactId>
				<version>2.0.0</version>
				<configuration>
					
					<directories>
						<directory>dl4j-examples</directory>
						<directory>dl4j-spark-examples</directory>
						<directory>datavec-examples</directory>
						<directory>dl4j-cuda-specific-examples</directory>
						<directory>nd4j-examples</directory>
						<directory>rl4j-examples</directory>
						<directory>arbiter-examples</directory>
						<directory>lstm-hdfs</directory>
					</directories>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.lewisd</groupId>
				<artifactId>lint-maven-plugin</artifactId>
				<version>0.0.11</version>
				<configuration>
					<failOnViolation>true</failOnViolation>
					<onlyRunRules>
						<rule>DuplicateDep</rule>
						<rule>RedundantPluginVersion</rule>
						<rule>VersionProp</rule>
						<rule>DotVersionProperty</rule>
					</onlyRunRules>
				</configuration>
				<executions>
					<execution>
						<id>pom-lint</id>
						<phase>validate</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
		</plugins>

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>com.lewisd</groupId>
										<artifactId>lint-maven-plugin</artifactId>
										<versionRange>[0.0.11,)</versionRange>
										<goals>
											<goal>check</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>

What do you think about it? Is it fine, or am I doing something wrong? Thank you in advance for your time :)

Edit: training workspace mod and inference workspace mod are **ENABLED** in both cases (MLN and CG)

**Comment by agibsonccc** [comment] 2021-04-15 05:45
Closing this since I'm imagining the author moved on. For future readers here, to make this more actionable I would have needed more specifics to reproduce an issue. Code will mean an issue gets acted on faster. Otherwise we  look at these kinds of issues on a best effort basis. We always have to reverse engineer the author's perception of the issue, the actual code they wrote, and the actual situation. That overhead makes some issues hard to look in to depending on the workload going on at the time.

**Closed as completed by agibsonccc** 2021-04-15 05:45 UTC
