### ISSUE TITLE
Training a neural network from zero (data cleaning, transforming, ...) to hero hero (model evaluation) 

### ISSUE THREAD

**Issue by silahi** [deeplearning4j/deeplearning4j#9232] opened 2021-03-13 20:34 UTC
#### Using dl4j for Logistic regression from zero to hero

I have built an example that demonstrates how to use deeplearning 4j
These are the key points covered in this example :

#### Version Information  

* Deeplearning4j version beta7
* Platform information : Windows  
* Local Processing

#### Additional Information
I think have covered all important points so for more details see : [Logistic Regression using dl4j](https://github.com/silahi/Logistic-Regression-using-dl4j-step-by-step)
 

 
[Readme.zip](https://github.com/eclipse/deeplearning4j/files/6135488/Readme.zip)

**Comment by agibsonccc** [comment] 2021-04-01 03:53
@sleicht  could you submit a pull request to the https://github.com/eclipse/deeplearning4j-examples? Open source projects on github in general tend to work like that. We can't put code or examples up without someone signing the ECA as well. If you're up for that, we're happy to publish the example + readme in the dl4j repo.

**Comment by sleicht** [comment] 2021-04-01 08:09
@agibsonccc: I think you meant @silahi and not me, right?

**Comment by agibsonccc** [comment] 2021-04-01 08:12
Yeah sorry auto complete..

**Comment by silahi** [comment] 2021-04-01 21:11
@agibsonccc I'm not ready yet for the ECA ! But I can always continue pushing in my forked repo while waiting !

**Comment by agibsonccc** [comment] 2021-04-01 23:25
@silahi  I'm not sure what you think the ECA is, but it's just a button you click with an eclipse account. It takes 2 seconds and doesn't have any sort of implications or liabilities to you.  It's needed for us to review your pull request regardless. We can't consider code from someone without that. I'm closing this since it's not a bug. If you want to discuss this further, please move over to our community forum: https://community.konduit.ai/

**Closed as completed** 2021-04-01 23:25 UTC
