### ISSUE TITLE
java.io.UTFDataFormatException Malformed input around byte 0 when restoring MultiLayerNetwork

### ISSUE THREAD

**Issue by sascha08-15** [deeplearning4j/deeplearning4j#6499] opened 2018-09-30 10:44 UTC
The problem is not 100% reproducible on my code basis. However, others seem to experience the same issue. The code, I used to save the model is as follows:

```
        LocalFileModelSaver saver2 = new LocalFileModelSaver(config.training.earlyStoppingSavePath);
        EarlyStoppingConfiguration<MultiLayerNetwork> esConf =
                new EarlyStoppingConfiguration.Builder<MultiLayerNetwork>().epochTerminationConditions( 
                        new MaxEpochsTerminationCondition(config.training.epochs)) 
                        .evaluateEveryNEpochs(1)
                        .iterationTerminationConditions(
                                new InvalidScoreIterationTerminationCondition(),
                                new MaxTimeIterationTerminationCondition(maxTime, TimeUnit.MINUTES))
                        .scoreCalculator(new DataSetLossCalculator(iterator, false))
                        .modelSaver(saver2)
                        .build();
```

I observed especially issues in terminating the process prematurely, (CTRL+C) and ended up with a corrupt ZIP File.

The exception is thrown when subsequently trying to load such a corrupt model with `ModelSerializer.restoreMultiLayerNetwork`

**Comment by AlexDBlack** [comment] 2018-09-30 23:37
> I observed especially issues in terminating the process prematurely, (CTRL+C) and ended up with a corrupt ZIP File.
> The exception is thrown when subsequently trying to load such a corrupt model with ModelSerializer.restoreMultiLayerNetwork

I'm not sure what the problem is here. If you kill the JVM while it's saving a network, causing it to be corrupted, and then try to load that corrupted network, of course you'll have problems.

What are you suggesting here? What would be the expected/corrected behaviour in this case?

**Comment by AlexDBlack** [comment] 2018-10-03 03:50
I'm tempted to close this. I'm not sure what we could do in this situation.

Perhaps a better exception ("File X may be corrupt") might help, but the problem is detecting that.
The only idea I have in that respect might be to write say an MD5 hash in the model zip file, for each component. If it's missing - or if it doesn't match - then maybe the model zip file is corrupt.
That would give us a better (more useful, easier to understand) exception, but it still wouldn't stop your program from crashing in the first place due to the bad file.

**Closed** 2018-10-11 06:51 UTC
