### ISSUE TITLE
Malmo environment not loading

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#8769] opened 2020-03-09 12:20 UTC
#### Issue Description

The malmo environment fails to initialize here:
https://github.com/eclipse/deeplearning4j/blob/master/rl4j/rl4j-malmo/src/main/java/org/deeplearning4j/malmo/MalmoEnv.java#L56

Debugging shows that the file exists, but the system.load call fails.

Malmo environment was installed from 
Malmo-0.37.0-Windows-64bit_withBoost_Python3.7

Does Rl4J require a specific Malmo version? 

@saudet Could you please have a look?

**Comment by saudet** [comment] 2020-03-09 12:39
You'll need to call System.load() on the DLL for JNI that comes with Malmo.

**Comment by saudet** [comment] 2020-03-09 12:40
Duplicate of #7222

**Closed as completed** 2020-03-09 12:41 UTC
Labels: Duplicate, RL4J
