### ISSUE TITLE
Cannot get DQN from policy

### ISSUE THREAD

**Issue by schrum2** [deeplearning4j/deeplearning4j#4155] opened 2017-10-07 05:18 UTC
In this file, https://github.com/deeplearning4j/rl4j/blob/273564b2e35294a83893688b9033013fe24129b6/rl4j-core/src/main/java/org/deeplearning4j/rl4j/policy/DQNPolicy.java , why is getNeuralNet() protected? After loading a policy from a saved file, I need access to the DQN in order to train it further.

**Comment by saudet** [comment] 2017-10-07 13:37
Duplicate of https://github.com/deeplearning4j/rl4j/issues/69

**Closed by saudet** 2017-10-07 13:37 UTC
Labels: duplicate
