### ISSUE TITLE
no opencv_imgproc342 in java.library.path after update to beta2

### ISSUE THREAD

**Issue by hurschler** [deeplearning4j/deeplearning4j#6202] opened 2018-08-18 14:26 UTC
Hi

After my update to version beta2 I got this exception on the second line of Code:

        NativeImageLoader loader = new NativeImageLoader(224, 224, 3);
        INDArray image = loader.asMatrix(new ClassPathResource("20171220_194540.jpg").getFile());

	at org.bytedeco.javacpp.Loader.load(Loader.java:941)
	at org.bytedeco.javacpp.Loader.load(Loader.java:882)
	at org.bytedeco.javacpp.helper.opencv_core$AbstractArray.<clinit>(opencv_core.java:109)
	at org.datavec.image.loader.NativeImageLoader.streamToMat(NativeImageLoader.java:256)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:227)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:221)
	
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc342 in java.library.path

On the maven build-path ist opencv-3.4.2-1.4.2

Thanks

André

**Comment by saudet** [comment] 2018-08-18 21:40
There should be a cause to that cause, could you show the whole stack trace as well as your pom.xml file? And on which platform is this happening?

**Comment by saudet** [comment] 2018-08-18 21:51
I'll just go and mark this as a duplicate of https://github.com/bytedeco/javacpp-presets/issues/604.

**Closed** 2018-08-18 21:51 UTC
Labels: Duplicate
