### ISSUE TITLE
ComputationGraph.feedForward Null Pointer exception.

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#4913] opened 2018-04-10 00:49 UTC
#### Issue Description
Please see: https://github.com/deeplearning4j/dl4j-examples/issues/659

We got a developer unfriendly Null Pointer Exception after the 1.0.0-alpha release. The example has been fixed.  It is not clear why the original code fails, could be a bug but the error message can be better.

**Comment by AlexDBlack** [comment] 2018-04-19 04:05
It's definitely not a bug; there was some changes to how input fields are cleared in some of the feed-forward methods (to avoid having invalid arrays (out of workspace scope) sitting around, which can crash the JVM if used).
I totally agree that we could have a better exception here - I'll add a check + error message in the backprop methods.

**Comment by AlexDBlack** [comment] 2018-04-19 04:39
I've added additional checks + a useful exception here: https://github.com/deeplearning4j/deeplearning4j/pull/4900
That will be merged soon.

**Closed by AlexDBlack** 2018-04-19 04:39 UTC
