### ISSUE TITLE
Tensorflow model trained in keras and loaded in deeplearning4j is giving NaN as output. Also, the run in Java frequently fails with SIGSEGV.

### ISSUE THREAD

**Issue by a27kash** [deeplearning4j/deeplearning4j#3069] opened 2017-03-18 15:04 UTC
this is my code 
        
        ComputationGraph network = KerasModelImport.importKerasModelAndWeights
                ("model.h5", false);

        NativeImageLoader loader = new NativeImageLoader(150, 150, 3);
        INDArray image = loader.asMatrix(new File(Resources.getResource("image.jpg").getFile()));

        INDArray[] output = network.output(false, image);
        System.out.println(output[0]);

the output comes as

         [NaN, NaN, NaN]

**Comment by turambar** [comment] 2017-03-24 04:56
@a27kash we need details if we're going to be able to investigate this. Can you provide the model hdf5 file or at least a model configuration JSON?

**Comment by a27kash** [comment] 2017-03-24 07:58
I'm sharing the configuration of model trained in Keras and configuration of model loaded in DeepLearning4J (as ComputationGraph). The .h5 file is too big to be uploaded (180 MB+ after compression). Please let me know if there's something else I need to provide.

[modelConfigs.zip](https://github.com/deeplearning4j/deeplearning4j/files/867201/modelConfigs.zip)

**Comment by a27kash** [comment] 2017-03-24 09:21
I have uploaded the .h5 file on Google Drive. Link : https://drive.google.com/open?id=0B9BCz-ofRaMTVDF6U2dkRmJfUWc

**Comment by turambar** [comment] 2017-03-24 14:46
@a27kash got it. Will take a look over next few days. In the meantime, I encourage you to turn on your debugger and step through and see what you can find, as well!

**Comment by maxpumperla** [comment] 2017-08-01 09:12
@a27kash do you still have this problem?

**Comment by maxpumperla** [comment] 2017-08-14 09:27
@a27kash I'm trying to reproduce your example, I also do get those SIGSEGV errors frequently.

However the `h5` file seems to be corrupted:

```
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: H5A.c line 438 in H5Aopen(): unable to load attribute info from object header for attribute: 'weight_names'
    major: Attribute
    minor: Unable to initialize object
```

Can you maybe provide the python script you're using? I want to see if I can construct a "minimum failing model" (yours is very large).

**Comment by maxpumperla** [comment] 2017-08-14 09:32
@a27kash also note that #3597 was resolved with https://github.com/deeplearning4j/deeplearning4j/pull/3842, which might solve your problem as well.

**Comment by maxpumperla** [comment] 2018-04-19 13:44
closing this due to inactivity, can't replicate the issue anyway.

**Closed by maxpumperla** 2018-04-19 13:44 UTC
Labels: bug, keras
